SET TERM ^ ;
alter  PROCEDURE PROC_INS_COTIZACION_MAST (
    FECHA timestamp,
    FECHA_VENCE timestamp,
    CODIGO_CTE integer,
    CODIGO_VENDEDOR integer,
    OBSERVACION varchar(60),
    MONEDA char(1),
    VALOR_TOTAL numeric(15,2),
    STATUS char(1),
    FECHA_IN timestamp,
    IN_POR varchar(12),
    FECHA_MOD timestamp,
    MOD_POR varchar(12),
    NUMERO_FACTURA SMALLINT,
  NUMERO_DOC_PAGO VARCHAR(20) CHARACTER SET NONE,
  SERIE_NCF_ASIGNADO SMALLINT,
  MONTO_BRUTO NUMERIC(15, 2),
  PORC_DESCUENTO SMALLINT,
  MONTO_DESCUENTO NUMERIC(15, 2),
  MONTO_INICIAL NUMERIC(15, 2),
  NOMBRE_CLIENTE_GENERAL VARCHAR(60) CHARACTER SET NONE,
  MONTO_PAGADO NUMERIC(15, 2),
  MONTO_CAMBIO NUMERIC(15, 2),
  MONTO_TOTAL_ITBIS NUMERIC(15, 2),
  MONTODESCGASTOSADMIN NUMERIC(15, 2),
  MONTODESCITBISGASTOSADMIN NUMERIC(15, 2),
  MONTODESCTRANSP NUMERIC(15, 2),
  MONTODESCDIRTECNICA NUMERIC(15, 2),
  MONTODESCITBISDIRTECNICA NUMERIC(15, 2),
  MONTODESCIMPREVISTO NUMERIC(15, 2),
  MONTODESCITBISIMPREVISTO NUMERIC(15, 2),
  TIPO_FACTURA SMALLINT,
  APLICA_TIPODESC SMALLINT )
RETURNS (
    NUMERO_TRNS integer )
AS
declare variable xnumero integer;
BEGIN
  
  Select Gen_id(GEN_NUM_COTIZA_MAST,1) From rdb$database
  Into :NUMERO_TRNS;
  
  xNumero =:NUMERO_TRNS;

  INSERT INTO COTIZACION_MAST (
    NUMERO,
    FECHA,
    FECHA_VENCE,
    CODIGO_CTE,
    CODIGO_VENDEDOR,
    OBSERVACION,
    MONEDA,
    VALOR_TOTAL,
    STATUS,
    FECHA_IN,
    IN_POR,
    FECHA_MOD,
    MOD_POR,
NUMERO_FACTURA,
  NUMERO_DOC_PAGO,
  SERIE_NCF_ASIGNADO,
  MONTO_BRUTO,
  PORC_DESCUENTO,
  MONTO_DESCUENTO ,
  MONTO_INICIAL,
  NOMBRE_CLIENTE_GENERAL,
  MONTO_PAGADO,
  MONTO_CAMBIO,
  MONTO_TOTAL_ITBIS,
  MONTODESCGASTOSADMIN,
  MONTODESCITBISGASTOSADMIN,
  MONTODESCTRANSP ,
  MONTODESCDIRTECNICA,
  MONTODESCITBISDIRTECNICA,
  MONTODESCIMPREVISTO ,
  MONTODESCITBISIMPREVISTO,
  TIPO_FACTURA,
  APLICA_TIPODESC)
  VALUES (
    :XNUMERO,
    :FECHA,
    :FECHA_VENCE,
    :CODIGO_CTE,
    :CODIGO_VENDEDOR,
    :OBSERVACION,
    :MONEDA,
    :VALOR_TOTAL,
    :STATUS,
    :FECHA_IN,
    :IN_POR,
    :FECHA_MOD,
    :MOD_POR,
    :NUMERO_FACTURA,
  :NUMERO_DOC_PAGO,
  :SERIE_NCF_ASIGNADO,
  :MONTO_BRUTO,
  :PORC_DESCUENTO,
  :MONTO_DESCUENTO ,
  :MONTO_INICIAL,
  :NOMBRE_CLIENTE_GENERAL,
  :MONTO_PAGADO,
  :MONTO_CAMBIO,
  :MONTO_TOTAL_ITBIS,
  :MONTODESCGASTOSADMIN,
  :MONTODESCITBISGASTOSADMIN,
  :MONTODESCTRANSP ,
  :MONTODESCDIRTECNICA,
  :MONTODESCITBISDIRTECNICA,
  :MONTODESCIMPREVISTO ,
  :MONTODESCITBISIMPREVISTO,
  :TIPO_FACTURA,
  :APLICA_TIPODESC
);
  SUSPEND;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE PROC_INS_COTIZACION_MAST TO  DIVISON;



-- TODO:
-- * add triggers and their ddl
-- * for each trigger, look for dependent generators via dependecies

