alter table VENTAS_MAST 
add MONTODESCGASTOSADMIN numeric(15,2),
  add MONTODESCITBISGASTOSADMIN numeric(15,2),
  add MONTODESCTRANSP numeric(15,2),
  add MONTODESCDIRTECNICA numeric(15,2),
  add MONTODESCITBISDIRTECNICA numeric(15,2),
  add MONTODESCIMPREVISTO numeric(15,2),
  add MONTODESCITBISIMPREVISTO numeric(15,2);