CREATE TABLE CONF_DESC_FACTURAS
(
  TIPO smallint NOT NULL,
  DESCRIPCION varchar(60),
  PORCIENTO numeric(15,2),
  FECHAINI timestamp,
  FECHAFIN timestamp,
  STATUS char(1)
);

CREATE UNIQUE INDEX IDX_CONF_DESC_FACTURAS1 ON CONF_DESC_FACTURAS (TIPO);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONF_DESC_FACTURAS TO  DIVISON WITH GRANT OPTION;

