CREATE TABLE VENTAS_DET_RECOVER
(
  ID CAMPO_ENTERO,
  SERIE CAMPO_ENTERO NOT NULL,
  FECHA timestamp NOT NULL,
  NUMERO CAMPO_ENTERO NOT NULL,
  CODIGO_PROD CAMPO_VARCHAR40,
  CODIGO_BARRA CAMPO_VARCHAR20,
  DESCRIPCION CAMPO_VARCHAR60,
  CANTIDAD NUMERICO_15_2,
  PRECIO NUM_FLOTANTE,
  PORC_DESC_DET NUM_FLOTANTE,
  ITBI_DET NUM_FLOTANTE,
  VALOR_SERVICIO_DET NUMERICO_15_2,
  VALOR_TOTAL_DET NUMERICO_15_2,
  NUM_FACTURA CAMPO_DOBLE_PREC,
  STATUS_DET CAMPO_CHAR1,
  FECHA_IN CAMPO_FECHA_HORA,
  IN_POR CAMPO_VARCHAR12,
  FECHA_MOD CAMPO_FECHA_HORA,
  MOD_POR CAMPO_VARCHAR12,
  CANT_REGRESO NUMERICO_15_2,
  CANT_PROMO NUMERICO_15_2,
  MONTO_DIETA NUMERICO_15_2,
  MONTO_AJUSTE NUMERICO_15_2,
  SERIE_PROD varchar(50),
  STATUS_CNT char(1),
  TIPO_UNIDAD CAMPO_ENTERO,
  ITBIS_EXENTO smallint,
  TIPO_VENTA smallint,
  DESCRIPCIONPRODUCTO CAMPO_MEMO,
  TIPO_OPE smallint,
  PRECIO_LEVEL smallint,
  COD_USUARIO CAMPO_ENTERO
);

CREATE UNIQUE INDEX IDX_VENTAS_DET_RECOVER1 ON VENTAS_DET_RECOVER (SERIE,FECHA,ID);
CREATE INDEX IDX_VENTAS_DET_RECOVER2 ON VENTAS_DET_RECOVER (FECHA);
CREATE INDEX IDX_VENTAS_DET_RECOVER3 ON VENTAS_DET_RECOVER (TIPO_OPE);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VENTAS_DET_RECOVER TO  DIVISON WITH GRANT OPTION;

