SET TERM ^ ;
CREATE PROCEDURE proc_PORC_APL_COTIZA_SERV_I(
  NUMERO_TRN INTEGER,
  PORCGADMIN NUMERIC(15, 2),
  PORCITBISGADMIN NUMERIC(15, 2),
  PORCTRANS NUMERIC(15, 2),
  PORCDIRTEC NUMERIC(15, 2),
  PORCITBISDIRTEC NUMERIC(15, 2),
  PORCIMPREVISTO NUMERIC(15, 2),
  PORCITBISIMPREVISTO NUMERIC(15, 2))
AS
BEGIN
  INSERT INTO PORC_APLICADO_COTIZA_SERV (
    NUMERO_TRN,
    PORCGADMIN,
    PORCITBISGADMIN,
    PORCTRANS,
    PORCDIRTEC,
    PORCITBISDIRTEC,
    PORCIMPREVISTO,
    PORCITBISIMPREVISTO)
  VALUES (
    :NUMERO_TRN,
    :PORCGADMIN,
    :PORCITBISGADMIN,
    :PORCTRANS,
    :PORCDIRTEC,
    :PORCITBISDIRTEC,
    :PORCIMPREVISTO,
    :PORCITBISIMPREVISTO);
END^
SET TERM ; ^
