set term !! ;
CREATE TRIGGER GEN_NUMERO_TRNCNT_DETALLE
FOR TRNCNT_DETALLE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  if (NEW.SERIE is NULL) 
  then NEW.SERIE = GEN_ID(GEN_NUMERO_TRNCNT_DETALLE, 1);
END!!
set term ; !!


