set term !! ;
CREATE TRIGGER GEN_NUMERO_TRNCNT_MASTER 
FOR TRNCNT_MASTER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  if (NEW.NUMERO is NULL) 
  then NEW.NUMERO = GEN_ID(GEN_NUMERO_TRNCNT_MASTER, 1);
END!!
set term ; !!


