SET TERM ^ ;
alter PROCEDURE proc_TRANS_CXC_U1(
  SERIE DOUBLE PRECISION,
  CIA_KEY INTEGER,
  TIPO_DOC INTEGER,
  MONEDA CHAR(1),
  FECHA DATE,
  NUMERO_DOC INTEGER,
  CODIGO_CLIENTE INTEGER,
  CODIGO_SERV INTEGER,
  CONCEPTO VARCHAR(60),
  VALOR_DOCUMENTO NUMERIC(15, 2),  
  FECHA_MOD DATE,
  MOD_POR VARCHAR(12),
  NUMERO_TRN_VENTA INTEGER
  )
AS
BEGIN
  UPDATE TRANS_CXC
  SET
    CIA_KEY = :CIA_KEY,
    MONEDA = :MONEDA,
    FECHA = :FECHA,
    NUMERO_DOC = :NUMERO_DOC,
    CODIGO_CLIENTE = :CODIGO_CLIENTE,
    CODIGO_SERV = :CODIGO_SERV,
    CONCEPTO = :CONCEPTO,
    VALOR_DOCUMENTO = :VALOR_DOCUMENTO,
    FECHA_MOD = :FECHA_MOD,
    MOD_POR = :MOD_POR,
    NUMERO_TRN_VENTA = :NUMERO_TRN_VENTA
  
  WHERE
  (SERIE = :SERIE) AND 
  (NUMERO_DOC=:NUMERO_DOC) and
  (CIA_KEY =:CIA_KEY) and
  (TIPO_DOC = :TIPO_DOC);
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE proc_TRANS_CXC_U1 TO  DIVISON;

GRANT EXECUTE
 ON PROCEDURE proc_TRANS_CXC_U1 TO  sysdba;