SET TERM ^ ;
ALTER PROCEDURE PROC_UPDATEVENTAS_MAST_U1 (
    NUMERO integer,
    FECHA timestamp,
    CIA_KEY integer,
    CODIGO_CTE integer,
    CODIGO_VENDEDOR integer,
    FORMA_PAGO smallint,
    OBSERVACION varchar(60),
    MONEDA char(1),
    VALOR_TOTAL_DET numeric(15,2),
    STATUS char(1),
    FECHA_MOD timestamp,
    MOD_POR varchar(12),
    NUMERO_FACTURA integer,
    NUMERO_DOC_PAGO varchar(20),
    SERIE_NCF_ASIGNADO integer,
    MONTO_BRUTO numeric(15,2),
    PORC_DESCUENTO integer,
    MONTO_DESCUENTO numeric(15,2),
    MONTO_INICIAL numeric(15,2),
    NOMBRE_CLIENTE_GENERAL varchar(60),
    MONTO_PAGADO numeric(15,2),
    MONTO_CAMBIO numeric(15,2),
    MONTO_TOTAL_ITBIS numeric(15,2),
    MONTODESCGASTOSADMIN numeric(15,2),
    MONTODESCITBISGASTOSADMIN numeric(15,2),
    MONTODESCTRANSP numeric(15,2),
    MONTODESCDIRTECNICA numeric(15,2),
    MONTODESCITBISDIRTECNICA numeric(15,2),
    MONTODESCIMPREVISTO numeric(15,2),
    MONTODESCITBISIMPREVISTO numeric(15,2) )
AS
BEGIN
  UPDATE VENTAS_MAST
  SET
    FECHA = :FECHA,
    CIA_KEY = :CIA_KEY,
    CODIGO_CTE = :CODIGO_CTE,
    --CODIGO_VENDEDOR = :CODIGO_VENDEDOR,
    FORMA_PAGO = :FORMA_PAGO,
    OBSERVACION = :OBSERVACION,
    MONEDA = :MONEDA,
    VALOR_TOTAL_DET = :VALOR_TOTAL_DET,
    STATUS = :STATUS,

    FECHA_MOD = :FECHA_MOD,
    MOD_POR = :MOD_POR,
    NUMERO_FACTURA = :NUMERO_FACTURA,
    --NUMERO_DOC_PAGO = :NUMERO_DOC_PAGO,
    --SERIE_NCF_ASIGNADO = :SERIE_NCF_ASIGNADO,
    MONTO_BRUTO = :MONTO_BRUTO,
    PORC_DESCUENTO = :PORC_DESCUENTO,
    MONTO_DESCUENTO = :MONTO_DESCUENTO,
    MONTO_INICIAL = :MONTO_INICIAL,
    NOMBRE_CLIENTE_GENERAL = :NOMBRE_CLIENTE_GENERAL,
    MONTO_PAGADO = :MONTO_PAGADO,
    MONTO_CAMBIO = :MONTO_CAMBIO,
    MONTO_TOTAL_ITBIS = :MONTO_TOTAL_ITBIS,
    MONTODESCGASTOSADMIN = :MONTODESCGASTOSADMIN,
    MONTODESCITBISGASTOSADMIN = :MONTODESCITBISGASTOSADMIN,
    MONTODESCTRANSP = :MONTODESCTRANSP,
    MONTODESCDIRTECNICA = :MONTODESCDIRTECNICA,
    MONTODESCITBISDIRTECNICA = :MONTODESCITBISDIRTECNICA,
    MONTODESCIMPREVISTO = :MONTODESCIMPREVISTO,
    MONTODESCITBISIMPREVISTO = :MONTODESCITBISIMPREVISTO
  WHERE
  (NUMERO = :NUMERO);
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE PROC_UPDATEVENTAS_MAST_U1 TO  DIVISON;

