SET TERM ^ ;
CREATE PROCEDURE proc_updatecxc_U1
RETURNS(
  SERIE DOUBLE PRECISION,
  CIA_KEY SMALLINT,
  TIPO_DOC INTEGER,
  MONEDA CHAR(1) CHARACTER SET NONE,
  FECHA DATE,
  NUMERO_DOC SMALLINT,
  CODIGO_CLIENTE SMALLINT,
  CONCEPTO VARCHAR(60) CHARACTER SET NONE,
  VALOR_DOCUMENTO NUMERIC(15, 2))
AS
BEGIN
  FOR
    SELECT 
      TRANS_CXC.SERIE,
      TRANS_CXC.CIA_KEY,
      TRANS_CXC.TIPO_DOC,
      TRANS_CXC.MONEDA,
      TRANS_CXC.FECHA,
      TRANS_CXC.NUMERO_DOC,
      TRANS_CXC.CODIGO_CLIENTE,
      TRANS_CXC.CONCEPTO,
      TRANS_CXC.VALOR_DOCUMENTO
    FROM
      TRANS_CXC

    INTO
      :SERIE,
      :CIA_KEY,
      :TIPO_DOC,
      :MONEDA,
      :FECHA,
      :NUMERO_DOC,
      :CODIGO_CLIENTE,
      :CONCEPTO,
      :VALOR_DOCUMENTO
  DO
  BEGIN
    SUSPEND;
  END
END^
SET TERM ; ^
