SET TERM ^ ;
alter  PROCEDURE Proc_PORC_APLICADO_FCT_SERV_S1
(xNUMERO_TRN INTEGER)
RETURNS(  
  PORCGADMIN NUMERIC(15, 2),
  PORCITBISGADMIN NUMERIC(15, 2),
  PORCTRANS NUMERIC(15, 2),
  PORCDIRTEC NUMERIC(15, 2),
  PORCITBISDIRTEC NUMERIC(15, 2),
  PORCIMPREVISTO NUMERIC(15, 2),
  PORCITBISIMPREVISTO NUMERIC(15, 2))
AS
BEGIN
  FOR SELECT
             PORCGADMIN,
             PORCITBISGADMIN,
             PORCTRANS,
             PORCDIRTEC,
             PORCITBISDIRTEC,
             PORCIMPREVISTO,
             PORCITBISIMPREVISTO
  FROM PORC_APLICADO_FCT_SERV
  where numero_trn =:xNUMERO_TRN 
  INTO 
       :PORCGADMIN,
       :PORCITBISGADMIN,
       :PORCTRANS,
       :PORCDIRTEC,
       :PORCITBISDIRTEC,
       :PORCIMPREVISTO,
       :PORCITBISIMPREVISTO
  DO
    BEGIN
      SUSPEND;
    END
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE Proc_PORC_APLICADO_FCT_SERV_S1 TO  DIVISON;

GRANT EXECUTE
 ON PROCEDURE Proc_PORC_APLICADO_FCT_SERV_S1 TO  sysdba;



