SET TERM ^ ;
CREATE PROCEDURE proc_PORC_APLICADO_FCT_SERV_I1(
  NUMERO_TRN INTEGER,
  PORCGADMIN NUMERIC(15, 2),
  PORCITBISGADMIN NUMERIC(15, 2),
  PORCTRANS NUMERIC(15, 2),
  PORCDIRTEC NUMERIC(15, 2),
  PORCITBISDIRTEC NUMERIC(15, 2),
  PORCIMPREVISTO NUMERIC(15, 2),
  PORCITBISIMPREVISTO NUMERIC(15, 2))
AS
BEGIN
  INSERT INTO PORC_APLICADO_FCT_SERV (
    NUMERO_TRN,
    PORCGADMIN,
    PORCITBISGADMIN,
    PORCTRANS,
    PORCDIRTEC,
    PORCITBISDIRTEC,
    PORCIMPREVISTO,
    PORCITBISIMPREVISTO)
  VALUES (
    :NUMERO_TRN,
    :PORCGADMIN,
    :PORCITBISGADMIN,
    :PORCTRANS,
    :PORCDIRTEC,
    :PORCITBISDIRTEC,
    :PORCIMPREVISTO,
    :PORCITBISIMPREVISTO);
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE proc_PORC_APLICADO_FCT_SERV_I1 TO  DIVISON;

GRANT EXECUTE
 ON PROCEDURE proc_PORC_APLICADO_FCT_SERV_I1 TO  sysdba;



