SET TERM ^ ;
CREATE PROCEDURE proc_updateFACTURAS_U1(
  SERIE DOUBLE PRECISION,
  NUMERO DOUBLE PRECISION,
  MONEDA CHAR(2),
  TIPO SMALLINT,
  CODIGO_CTE INTEGER,
  FECHA DATE,
  DESCRIPCION VARCHAR(40),
  MONTO_FACT NUMERIC(15, 2),
  RCXC CHAR(1),
  RCNT CHAR(1),
  STATUS CHAR(1),
  FECHA_MOD DATE,
  MOD_POR VARCHAR(12),
  FECHA_VENCE DATE,
  TIPO_FACTURA SMALLINT,
  APLICA_TIPODESC SMALLINT)
AS
BEGIN
  UPDATE FACTURAS
  SET
    CODIGO_CTE = :CODIGO_CTE,
    FECHA = :FECHA,
    DESCRIPCION = :DESCRIPCION,
    MONTO_FACT = :MONTO_FACT,
    RCXC = :RCXC,
    RCNT = :RCNT,
    STATUS = :STATUS,    
    FECHA_MOD = :FECHA_MOD,
    MOD_POR = :MOD_POR,
    FECHA_VENCE = :FECHA_VENCE,
    TIPO_FACTURA = :TIPO_FACTURA,
    APLICA_TIPODESC = :APLICA_TIPODESC
  WHERE
  (SERIE = :SERIE) AND 
  (NUMERO = :NUMERO) AND 
  (MONEDA = :MONEDA) AND 
  (TIPO = :TIPO);
END^
SET TERM ; ^
GRANT EXECUTE
 ON PROCEDURE stp_updateFACTURAS_U1 TO  DIVISON;

GRANT EXECUTE
 ON PROCEDURE stp_updateFACTURAS_U1 TO  DIVISON;
