SET TERM ^ ;
ALTER TRIGGER SETMASTERNUMEROTODETALLE ACTIVE
BEFORE INSERT POSITION 0
AS 
DECLARE orgXNUMERO Integer;
BEGIN 
    /* enter trigger code here */ 
   SELECT NUMERO
    FROM TRNCNT_MASTER
    WHERE NUMERO_SUBLOC=new.NUMERO_SUBLOC AND OFFICE_ID=new.SYNC_STATUS
    INTO
    :orgXNUMERO;
    
   if (inserting or NEW.SERIE is NULL) 
    then NEW.numero =orgXNUMERO;
    
END^
SET TERM ; ^
