INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (1,'1','11/08/2007',NULL,2,'ABANICO DE MESA UNIVERSAL          ZM-14',-76,1000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (2,'21','02/26/2008','XG7NC903AAL004808',1,'NIPPONIA C90 (E. 319) AZUL',1,32500,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (3,'22','02/26/2008','XG7NC903AAL004868',1,'NIPPONIA NC90 NEGRO (E. 319)',1,32500,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (4,'23','02/26/2008','XG7NAX100GD103944',1,'NIPPONIA AX100 AZUL (E. 298)',1,31000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (5,'2','11/08/2007',NULL,2,'ABANICO DE PEDESTAL               ZF-16',-9,1375,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (7,'24','02/26/2008','XG7NAX100GD103951',1,'NIPPONIA AX100 AZUL (E. 298)',1,31000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (8,'3','01/10/2008',NULL,2,'ESTUFA DE MESA AMER. CREMA        170-N',-22,1700,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (9,'4','01/10/2008',NULL,2,'ESTUFA DE GAS AMERICAN BCA      1000-N',-3,5500,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (10,'5','01/10/2008',NULL,2,'EQUIPO DE MUSICA SONY       MHC-EC55',-4,8000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (11,'6','01/10/2008',NULL,2,'LAVADORA CREMA DAEWOO DW-K500C',1,5800,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (12,'7','01/10/2008',NULL,2,'LAVADORA BLANCA DAEWOO DW-5010',2,9200,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (13,'8','11/08/2008',NULL,2,'LICUADORA AMERICAN LQ-200',2,1300,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (14,'9','11/08/2007',NULL,2,'NEVERA CREMA GENERAL ELECT.  (TA-10Z04)',1,13500,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (15,'10','01/10/2008',NULL,2,'RADIO GRABADOR SUPERSONIC  (SC-703CD)',2,2900,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (16,'11','01/10/2008',NULL,2,'RADIO GRABADOR SUPERSONIC (SC-2020CD)',2,3100,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (17,'12','01/10/2008',NULL,2,'RADIO GRABADOR SUPERSONIC (SC-1010CD)',0,2900,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (18,'13','01/10/2008',NULL,2,'RADIO GRABADOR SUPER SONIC (SC-717CD)',2,2500,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (19,'14','01/10/2008',NULL,2,'TELEVISOR DAEWOO (DTQ-14D4SSF)',2,6000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (20,'15','01/10/2008',NULL,2,'TELEVISOR DAEWOO (DTQ-2130SS)',2,8500,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (21,'16','01/10/2008',NULL,2,'WAFLERA OSTER (CG-120)',2,2000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (22,'17','01/10/2008',NULL,2,'WAFLERA UNIVERSAL (WA-25)',1,1700,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (23,'18','11/08/2007',NULL,2,'PLANCHA ELECTRICA OSTER (5003-12)',4,650,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (24,'19','11/08/2007',NULL,2,'PLANCHA ELECTRICA UNIVERSAL (Z-95)',5,500,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (25,'20','01/10/2008',NULL,2,'VIDEO DIGITAL TOSHIBA (SD-K770KU)',2,3300,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (26,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (27,'25','02/26/2008','XG7NAX100GD103024',1,'NIPPONIA AX100 ROJO (E. 275)',0,23008.62,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (29,'26','02/26/2008','XG7NAX100GD103747',1,'NIPPONIA AX100 NEGRO (E. 298)',1,31000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (30,'27','02/26/2008','XG7NAX100GD104572',1,'NIPPONIA AX100-DISCO ROJO (E. 315)',1,32000,'A',0,NULL,NULL);
INSERT INTO INVENTARIO_PRODUCTO
  (CODIGO,CODIGO_TEXTO,FECHA,CODIGO_BARRA,TIPO,DESCRIPCION,CANTIDAD,PRECIO,PAGA_ITBI,PRECIO_MINIMO,REFERENCIA,STATUS)
VALUES
  (31,NULL,'03/20/2008',NULL,NULL,NULL,NULL,NULL,'A',0,NULL,NULL);
