unit UDatmodDatosGenerales;

interface

uses
  SysUtils, Classes, DB, IBCustomDataSet, IBQuery, RxMemDS, IBStoredProc,
  IBTable, IBSQL;

type
  TdmDatos = class(TDataModule)
    qryTasa: TIBQuery;
    dsqryTasa: TDataSource;
    qryTasaSERIE: TIntegerField;
    qryTasaVALORMONEDA: TFloatField;
    qryTasaSIMBOLO: TIBStringField;
    qryOrdenMaster: TIBDataSet;
    qryOrdenDet: TIBDataSet;
    qryOrdenMasterNUMERO: TIntegerField;
    qryOrdenMasterCODIGO_PROVEE: TIntegerField;
    qryOrdenMasterFECHA: TDateTimeField;
    qryOrdenMasterFPAGO: TSmallintField;
    qryOrdenMasterCOD_CAJA_CHICA: TIntegerField;
    qryOrdenMasterCODIGO_BANCO: TIntegerField;
    qryOrdenMasterCUENTABANCO: TIBStringField;
    qryOrdenMasterOBSERVACION: TIBStringField;
    qryOrdenMasterMONTO: TFloatField;
    qryOrdenMasterSTATUS: TIBStringField;
    qryOrdenMasterIN_POR: TIBStringField;
    qryOrdenMasterFECHA_IN: TDateTimeField;
    qryOrdenMasterMOD_POR: TIBStringField;
    qryOrdenMasterFECHA_MOD: TDateTimeField;
    qryOrdenMasterTIPO_INV: TSmallintField;
    qryOrdenMasterSTATUS_CNT: TIBStringField;
    qryOrdenMasterNUM_ORDEN: TIntegerField;
    qryOrdenMasterSTATUS_ORD: TIBStringField;
    qryOrdenMasterAREA_ORDEN: TIntegerField;
    qryOrdenDetSERIE: TFloatField;
    qryOrdenDetNUMERO: TIntegerField;
    qryOrdenDetCOD_SERV_PROD: TIntegerField;
    qryOrdenDetDEPARTAMENTO: TIntegerField;
    qryOrdenDetCANTIDAD: TFloatField;
    qryOrdenDetVALOR: TFloatField;
    qryOrdenDetSTATUS: TIBStringField;
    qryOrdenDetIN_POR: TIBStringField;
    qryOrdenDetFECHA_IN: TDateTimeField;
    qryOrdenDetMOD_POR: TIBStringField;
    qryOrdenDetFECHA_MOD: TDateTimeField;
    qryOrdenDetNUMERO_DOCUMENTO: TIntegerField;
    qryOrdenDetNUMERO_FACTURA: TIntegerField;
    qryOrdenDetCOD_CTA_CONCEPTO: TIntegerField;
    qryOrdenDetTIPOSERVICIO: TIntegerField;
    qryOrdenDetSUBTIPOSERV: TIntegerField;
    qryOrdenDetNO_SERIE_RES: TIntegerField;
    qryOrdenDetCODIGO_CONDUCTOR: TIntegerField;
    qryOrdenDetSERIE_CDC: TIntegerField;
    qryOrdenDetCODIGO_SERVCOSTO: TIntegerField;
    qryOrdenDetNUMEROOLD: TIntegerField;
    qryOrdenDetPRECIO: TFloatField;
    qryOrdenDetAREA_ORDEN: TIntegerField;
    dsqryOrdenMaster: TDataSource;
    dsqryOrdenDet: TDataSource;
    qryInv: TIBQuery;
    qryInvCODIGO: TIntegerField;
    qryInvCODIGO_TEXTO: TIBStringField;
    rxqryInv: TRxMemoryData;
    rxqryInvCODIGO: TIntegerField;
    rxqryInvCODIGO_TEXTO: TStringField;
    rxqryInvDESCRIPCION: TStringField;
    rxqryInvPRECIO_COMPRA: TCurrencyField;
    dsrxqryInv: TDataSource;
    qryInvREFERENCIA: TIBStringField;
    rxqryInvREFERENCIA: TStringField;
    qryInvPRECIO_COMPRA: TFloatField;
    qryInvPAGA_ITBI: TSmallintField;
    rxqryInvPAGA_ITBI: TSmallintField;
    qryDatosOrdenImp: TIBQuery;
    qryDatosOrdenImpDet: TIBQuery;
    qryDatosOrdenImpDetSERIE: TFloatField;
    qryDatosOrdenImpDetNUMERO: TIntegerField;
    qryDatosOrdenImpDetCOD_SERV_PROD: TIntegerField;
    qryDatosOrdenImpDetDEPARTAMENTO: TIntegerField;
    qryDatosOrdenImpDetCANTIDAD: TFloatField;
    qryDatosOrdenImpDetVALOR: TFloatField;
    qryDatosOrdenImpDetSTATUS: TIBStringField;
    qryDatosOrdenImpDetIN_POR: TIBStringField;
    qryDatosOrdenImpDetFECHA_IN: TDateTimeField;
    qryDatosOrdenImpDetMOD_POR: TIBStringField;
    qryDatosOrdenImpDetFECHA_MOD: TDateTimeField;
    qryDatosOrdenImpDetNUMERO_DOCUMENTO: TIntegerField;
    qryDatosOrdenImpDetNUMERO_FACTURA: TIntegerField;
    qryDatosOrdenImpDetCOD_CTA_CONCEPTO: TIntegerField;
    qryDatosOrdenImpDetTIPOSERVICIO: TIntegerField;
    qryDatosOrdenImpDetSUBTIPOSERV: TIntegerField;
    qryDatosOrdenImpDetNO_SERIE_RES: TIntegerField;
    qryDatosOrdenImpDetCODIGO_CONDUCTOR: TIntegerField;
    qryDatosOrdenImpDetSERIE_CDC: TIntegerField;
    qryDatosOrdenImpDetCODIGO_SERVCOSTO: TIntegerField;
    qryDatosOrdenImpDetPRECIO: TFloatField;
    qryDatosOrdenImpDetAREA_ORDEN: TIntegerField;
    qryDatosOrdenImpDetITBI_DET: TFloatField;
    qryDatosOrdenImpDetPORC_DESC_DET: TFloatField;
    qryDatosOrdenImpDetMONTO_DESCUENTO: TFloatField;
    stpInsOrdenMast: TIBStoredProc;
    qryDatosOrdenImpNUMERO: TIntegerField;
    qryDatosOrdenImpCODIGO_PROVEE: TIntegerField;
    qryDatosOrdenImpFECHA: TDateTimeField;
    qryDatosOrdenImpFPAGO: TSmallintField;
    qryDatosOrdenImpCOD_CAJA_CHICA: TIntegerField;
    qryDatosOrdenImpCODIGO_BANCO: TIntegerField;
    qryDatosOrdenImpCUENTABANCO: TIBStringField;
    qryDatosOrdenImpOBSERVACION: TIBStringField;
    qryDatosOrdenImpMONTO: TFloatField;
    qryDatosOrdenImpSTATUS: TIBStringField;
    qryDatosOrdenImpIN_POR: TIBStringField;
    qryDatosOrdenImpFECHA_IN: TDateTimeField;
    qryDatosOrdenImpMOD_POR: TIBStringField;
    qryDatosOrdenImpFECHA_MOD: TDateTimeField;
    qryDatosOrdenImpTIPO_INV: TSmallintField;
    qryDatosOrdenImpSTATUS_CNT: TIBStringField;
    qryDatosOrdenImpNUM_ORDEN: TIntegerField;
    qryDatosOrdenImpSTATUS_ORD: TIBStringField;
    qryDatosOrdenImpAREA_ORDEN: TIntegerField;
    qryPrecioXUnidad: TIBDataSet;
    qryPrecioXUnidadID_PROD: TIntegerField;
    qryPrecioXUnidadID_UNIDAD: TIntegerField;
    qryPrecioXUnidadPRECIO: TFloatField;
    qryPrecioXUnidadCOD_USUARIO: TIntegerField;
    qryPrecioXUnidadFECHA_IN: TDateTimeField;
    qryPrecioXUnidadFECHA_UPDATE: TDateTimeField;
    dsqryPrecioXUnidad: TDataSource;
    tblTipoUnidad: TIBTable;
    dstblTipoUnidad: TDataSource;
    qryInvTIPO_UNIDAD: TIntegerField;
    qryInvPRECIO: TFloatField;
    qryInvCANTIDAD: TFloatField;
    qryOrdenMasterCIA_KEY: TIntegerField;
    qryInvDESCRIPCION: TIBStringField;
    stpInsOrdenDet: TIBStoredProc;
    qryDatosOrdenImpDetOBSERVACION: TIBStringField;
    qryOrdenDetMONTO_DESCUENTO: TFloatField;
    qryOrdenDetITBI_DET: TFloatField;
    qryOrdenDetPORC_DESC_DET: TFloatField;
    qryOrdenDetOBSERVACION: TIBStringField;
    qryDatosOrdenImpCIA_KEY: TIntegerField;
    qryDatosOrdenImpNUMERO_NCF: TIBStringField;
    qryDatosOrdenImpDESCRIPCION: TIBStringField;
    qryDatosOrdenImpCIUDAD: TIBStringField;
    qryDatosOrdenImpCALYYNUM: TIBStringField;
    qryDatosOrdenImpTELEFONO: TIBStringField;
    qryDatosOrdenImpFAX: TIBStringField;
    qryDatosOrdenImpEMAIL: TIBStringField;
    qryDatosOrdenImpMOVIL1: TIBStringField;
    qryDatosOrdenImpMOVIL2: TIBStringField;
    qryDatosOrdenImpTELEFONO2: TIBStringField;
    qryDatosOrdenImpTELEFONO3: TIBStringField;
    qryDatosOrdenImpEXTENSIONES: TIBStringField;
    qryDatosOrdenImpCIA_KEY1: TIntegerField;
    qryDatosOrdenImpNOMBRE_ABR: TIBStringField;
    qryDatosOrdenImpCONTACTO: TIBStringField;
    qryDatosOrdenImpPAIS: TIBStringField;
    qryDatosOrdenImpRNC_PROVEEDOR: TIBStringField;
    stpInsSolOrdenMast: TIBStoredProc;
    stpInsSolOrdenDet: TIBStoredProc;
    qryDatosSolOrdenImpDet: TIBQuery;
    qryDatosSolOrdenImp: TIBQuery;
    qryDatosSolOrdenImpNUMERO: TIntegerField;
    qryDatosSolOrdenImpCODIGO_PROVEE: TIntegerField;
    qryDatosSolOrdenImpFECHA: TDateTimeField;
    qryDatosSolOrdenImpFPAGO: TSmallintField;
    qryDatosSolOrdenImpCOD_CAJA_CHICA: TIntegerField;
    qryDatosSolOrdenImpCODIGO_BANCO: TIntegerField;
    qryDatosSolOrdenImpCUENTABANCO: TIBStringField;
    qryDatosSolOrdenImpOBSERVACION: TIBStringField;
    qryDatosSolOrdenImpMONTO: TFloatField;
    qryDatosSolOrdenImpSTATUS: TIBStringField;
    qryDatosSolOrdenImpIN_POR: TIBStringField;
    qryDatosSolOrdenImpFECHA_IN: TDateTimeField;
    qryDatosSolOrdenImpMOD_POR: TIBStringField;
    qryDatosSolOrdenImpFECHA_MOD: TDateTimeField;
    qryDatosSolOrdenImpTIPO_INV: TSmallintField;
    qryDatosSolOrdenImpSTATUS_CNT: TIBStringField;
    qryDatosSolOrdenImpNUM_ORDEN: TIntegerField;
    qryDatosSolOrdenImpSTATUS_ORD: TIBStringField;
    qryDatosSolOrdenImpAREA_ORDEN: TIntegerField;
    qryDatosSolOrdenImpCIA_KEY: TIntegerField;
    qryDatosSolOrdenImpNUMERO_NCF: TIBStringField;
    qryDatosSolOrdenImpDESCRIPCION: TIBStringField;
    qryDatosSolOrdenImpCIUDAD: TIBStringField;
    qryDatosSolOrdenImpCALYYNUM: TIBStringField;
    qryDatosSolOrdenImpTELEFONO: TIBStringField;
    qryDatosSolOrdenImpFAX: TIBStringField;
    qryDatosSolOrdenImpEMAIL: TIBStringField;
    qryDatosSolOrdenImpMOVIL1: TIBStringField;
    qryDatosSolOrdenImpMOVIL2: TIBStringField;
    qryDatosSolOrdenImpTELEFONO2: TIBStringField;
    qryDatosSolOrdenImpTELEFONO3: TIBStringField;
    qryDatosSolOrdenImpEXTENSIONES: TIBStringField;
    qryDatosSolOrdenImpCIA_KEY1: TIntegerField;
    qryDatosSolOrdenImpNOMBRE_ABR: TIBStringField;
    qryDatosSolOrdenImpCONTACTO: TIBStringField;
    qryDatosSolOrdenImpPAIS: TIBStringField;
    qryDatosSolOrdenImpRNC_PROVEEDOR: TIBStringField;
    qryDatosSolOrdenImpDetSERIE: TFloatField;
    qryDatosSolOrdenImpDetNUMERO: TIntegerField;
    qryDatosSolOrdenImpDetCOD_SERV_PROD: TIntegerField;
    qryDatosSolOrdenImpDetDEPARTAMENTO: TIntegerField;
    qryDatosSolOrdenImpDetOBSERVACION: TIBStringField;
    qryDatosSolOrdenImpDetCANTIDAD: TFloatField;
    qryDatosSolOrdenImpDetVALOR: TFloatField;
    qryDatosSolOrdenImpDetSTATUS: TIBStringField;
    qryDatosSolOrdenImpDetIN_POR: TIBStringField;
    qryDatosSolOrdenImpDetFECHA_IN: TDateTimeField;
    qryDatosSolOrdenImpDetMOD_POR: TIBStringField;
    qryDatosSolOrdenImpDetFECHA_MOD: TDateTimeField;
    qryDatosSolOrdenImpDetNUMERO_DOCUMENTO: TIntegerField;
    qryDatosSolOrdenImpDetNUMERO_FACTURA: TIntegerField;
    qryDatosSolOrdenImpDetCOD_CTA_CONCEPTO: TIntegerField;
    qryDatosSolOrdenImpDetTIPOSERVICIO: TIntegerField;
    qryDatosSolOrdenImpDetSUBTIPOSERV: TIntegerField;
    qryDatosSolOrdenImpDetNO_SERIE_RES: TIntegerField;
    qryDatosSolOrdenImpDetCODIGO_CONDUCTOR: TIntegerField;
    qryDatosSolOrdenImpDetSERIE_CDC: TIntegerField;
    qryDatosSolOrdenImpDetCODIGO_SERVCOSTO: TIntegerField;
    qryDatosSolOrdenImpDetNUMEROOLD: TIntegerField;
    qryDatosSolOrdenImpDetPRECIO: TFloatField;
    qryDatosSolOrdenImpDetAREA_ORDEN: TIntegerField;
    qryDatosSolOrdenImpDetITBI_DET: TFloatField;
    qryDatosSolOrdenImpDetPORC_DESC_DET: TFloatField;
    qryDatosSolOrdenImpDetMONTO_DESCUENTO: TFloatField;
    qrySolOrdenMaster: TIBDataSet;
    QrySolOrdenDet: TIBDataSet;
    qrySolOrdenMasterNUMERO: TIntegerField;
    qrySolOrdenMasterCODIGO_PROVEE: TIntegerField;
    qrySolOrdenMasterFECHA: TDateTimeField;
    qrySolOrdenMasterFPAGO: TSmallintField;
    qrySolOrdenMasterCOD_CAJA_CHICA: TIntegerField;
    qrySolOrdenMasterCODIGO_BANCO: TIntegerField;
    qrySolOrdenMasterCUENTABANCO: TIBStringField;
    qrySolOrdenMasterOBSERVACION: TIBStringField;
    qrySolOrdenMasterMONTO: TFloatField;
    qrySolOrdenMasterSTATUS: TIBStringField;
    qrySolOrdenMasterIN_POR: TIBStringField;
    qrySolOrdenMasterFECHA_IN: TDateTimeField;
    qrySolOrdenMasterMOD_POR: TIBStringField;
    qrySolOrdenMasterFECHA_MOD: TDateTimeField;
    qrySolOrdenMasterTIPO_INV: TSmallintField;
    qrySolOrdenMasterSTATUS_CNT: TIBStringField;
    qrySolOrdenMasterNUM_ORDEN: TIntegerField;
    qrySolOrdenMasterSTATUS_ORD: TIBStringField;
    qrySolOrdenMasterAREA_ORDEN: TIntegerField;
    qrySolOrdenMasterCIA_KEY: TIntegerField;
    qrySolOrdenMasterNUMERO_NCF: TIBStringField;
    QrySolOrdenDetSERIE: TFloatField;
    QrySolOrdenDetNUMERO: TIntegerField;
    QrySolOrdenDetCOD_SERV_PROD: TIntegerField;
    QrySolOrdenDetDEPARTAMENTO: TIntegerField;
    QrySolOrdenDetOBSERVACION: TIBStringField;
    QrySolOrdenDetCANTIDAD: TFloatField;
    QrySolOrdenDetVALOR: TFloatField;
    QrySolOrdenDetSTATUS: TIBStringField;
    QrySolOrdenDetIN_POR: TIBStringField;
    QrySolOrdenDetFECHA_IN: TDateTimeField;
    QrySolOrdenDetMOD_POR: TIBStringField;
    QrySolOrdenDetFECHA_MOD: TDateTimeField;
    QrySolOrdenDetNUMERO_DOCUMENTO: TIntegerField;
    QrySolOrdenDetNUMERO_FACTURA: TIntegerField;
    QrySolOrdenDetCOD_CTA_CONCEPTO: TIntegerField;
    QrySolOrdenDetTIPOSERVICIO: TIntegerField;
    QrySolOrdenDetSUBTIPOSERV: TIntegerField;
    QrySolOrdenDetNO_SERIE_RES: TIntegerField;
    QrySolOrdenDetCODIGO_CONDUCTOR: TIntegerField;
    QrySolOrdenDetSERIE_CDC: TIntegerField;
    QrySolOrdenDetCODIGO_SERVCOSTO: TIntegerField;
    QrySolOrdenDetNUMEROOLD: TIntegerField;
    QrySolOrdenDetPRECIO: TFloatField;
    QrySolOrdenDetAREA_ORDEN: TIntegerField;
    QrySolOrdenDetITBI_DET: TFloatField;
    QrySolOrdenDetPORC_DESC_DET: TFloatField;
    QrySolOrdenDetMONTO_DESCUENTO: TFloatField;
    tblMarcaVehiculo: TIBTable;
    tblMarcaVehiculoIDMARCA: TSmallintField;
    tblMarcaVehiculoDESCRIPCION: TIBStringField;
    dstblMarcaVehiculo: TDataSource;
    dstblTipoVehiculo: TDataSource;
    tblTipoVehiculo: TIBTable;
    tblTipoVehiculoIDTIPOVEH: TSmallintField;
    tblTipoVehiculoDESCRIPCION: TIBStringField;
    tblPolizaMaster: TIBDataSet;
    tblPolizaDet: TIBDataSet;
    tblPolizaMasterNUMERO: TIntegerField;
    tblPolizaMasterCOD_PROVEEDOR: TIntegerField;
    tblPolizaMasterPOLIZA: TIBStringField;
    tblPolizaMasterFECHA: TDateTimeField;
    tblPolizaMasterSTATUS: TIBStringField;
    tblPolizaMasterCOD_USUARIO: TIntegerField;
    tblPolizaMasterFECHA_IN: TDateTimeField;
    tblPolizaMasterIN_POR: TIBStringField;
    tblPolizaMasterFECHA_MOD: TDateTimeField;
    tblPolizaMasterMOD_POR: TIBStringField;
    tblPolizaDetSERIE: TIntegerField;
    tblPolizaDetNUMERO: TIntegerField;
    tblPolizaDetINICIOVIGENCIA: TDateTimeField;
    tblPolizaDetFINVIGENCIA: TDateTimeField;
    tblPolizaDetIDMARCA: TSmallintField;
    tblPolizaDetIDTIPOVEH: TSmallintField;
    tblPolizaDetNOMBREASEGURADO: TIBStringField;
    tblPolizaDetAPELLIDOASEGURADO: TIBStringField;
    tblPolizaDetREGISTRO: TIBStringField;
    tblPolizaDetCHASSIS: TIBStringField;
    tblPolizaDetFIANZAJUDICIAL: TFloatField;
    tblPolizaDetANO_VEHICULO: TIntegerField;
    tblPolizaDetSTATUS: TIBStringField;
    tblPolizaDetCOD_USUARIO: TIntegerField;
    tblPolizaDetFECHA_IN: TDateTimeField;
    tblPolizaDetIN_POR: TIBStringField;
    tblPolizaDetFECHA_MOD: TDateTimeField;
    tblPolizaDetMOD_POR: TIBStringField;
    dstblPolizaMaster: TDataSource;
    dstblPolizaDet: TDataSource;
    tblPolizaDetNO_VEHICULO: TIntegerField;
    qryRepPoliza: TIBQuery;
    qryRepPolizaNUMERO: TIntegerField;
    qryRepPolizaCOD_PROVEEDOR: TIntegerField;
    qryRepPolizaPOLIZA: TIBStringField;
    qryRepPolizaFECHA: TDateTimeField;
    qryRepPolizaSTATUS: TIBStringField;
    qryRepPolizaCOD_USUARIO: TIntegerField;
    qryRepPolizaFECHA_IN: TDateTimeField;
    qryRepPolizaIN_POR: TIBStringField;
    qryRepPolizaFECHA_MOD: TDateTimeField;
    qryRepPolizaMOD_POR: TIBStringField;
    qryRepPolizaNOMBREPROVEEDOR: TIBStringField;
    qryRepPolizaDEt: TIBQuery;
    qryRepPolizaDEtSERIE: TIntegerField;
    qryRepPolizaDEtNUMERO: TIntegerField;
    qryRepPolizaDEtINICIOVIGENCIA: TDateTimeField;
    qryRepPolizaDEtFINVIGENCIA: TDateTimeField;
    qryRepPolizaDEtIDMARCA: TSmallintField;
    qryRepPolizaDEtIDTIPOVEH: TSmallintField;
    qryRepPolizaDEtNOMBREASEGURADO: TIBStringField;
    qryRepPolizaDEtAPELLIDOASEGURADO: TIBStringField;
    qryRepPolizaDEtREGISTRO: TIBStringField;
    qryRepPolizaDEtCHASSIS: TIBStringField;
    qryRepPolizaDEtFIANZAJUDICIAL: TFloatField;
    qryRepPolizaDEtANO_VEHICULO: TIntegerField;
    qryRepPolizaDEtSTATUS: TIBStringField;
    qryRepPolizaDEtCOD_USUARIO: TIntegerField;
    qryRepPolizaDEtFECHA_IN: TDateTimeField;
    qryRepPolizaDEtIN_POR: TIBStringField;
    qryRepPolizaDEtFECHA_MOD: TDateTimeField;
    qryRepPolizaDEtMOD_POR: TIBStringField;
    qryRepPolizaDEtNO_VEHICULO: TIntegerField;
    qryRepPolizaDEtTIPOVEHDESC: TIBStringField;
    qryRepPolizaDEtMARCA: TIBStringField;
    qryViewOrdenCompMast: TIBQuery;
    qryViewOrdenCompDet: TIBQuery;
    qryViewOrdenCompMastBase: TIBQuery;
    qryViewOrdenCompMastBaseNUMERO: TIntegerField;
    qryViewOrdenCompMastBaseCODIGO_PROVEE: TIntegerField;
    qryViewOrdenCompMastBaseFECHA: TDateTimeField;
    qryViewOrdenCompMastBaseFPAGO: TSmallintField;
    qryViewOrdenCompMastBaseCOD_CAJA_CHICA: TIntegerField;
    qryViewOrdenCompMastBaseCODIGO_BANCO: TIntegerField;
    qryViewOrdenCompMastBaseCUENTABANCO: TIBStringField;
    qryViewOrdenCompMastBaseOBSERVACION: TIBStringField;
    qryViewOrdenCompMastBaseMONTO: TFloatField;
    qryViewOrdenCompMastBaseSTATUS: TIBStringField;
    qryViewOrdenCompMastBaseTIPO_INV: TSmallintField;
    qryViewOrdenCompMastBaseSTATUS_CNT: TIBStringField;
    qryViewOrdenCompMastBaseNUM_ORDEN: TIntegerField;
    qryViewOrdenCompMastBaseSTATUS_ORD: TIBStringField;
    qryViewOrdenCompMastBaseAREA_ORDEN: TIntegerField;
    qryViewOrdenCompMastBaseCIA_KEY: TIntegerField;
    qryViewOrdenCompMastBaseNUMERO_NCF: TIBStringField;
    qryViewOrdenCompDetSERIE: TFloatField;
    qryViewOrdenCompDetNUMERO: TIntegerField;
    qryViewOrdenCompDetCOD_SERV_PROD: TIntegerField;
    qryViewOrdenCompDetDEPARTAMENTO: TIntegerField;
    qryViewOrdenCompDetOBSERVACION: TIBStringField;
    qryViewOrdenCompDetCANTIDAD: TFloatField;
    qryViewOrdenCompDetVALOR: TFloatField;
    qryViewOrdenCompDetSTATUS: TIBStringField;
    qryViewOrdenCompDetIN_POR: TIBStringField;
    qryViewOrdenCompDetFECHA_IN: TDateTimeField;
    qryViewOrdenCompDetMOD_POR: TIBStringField;
    qryViewOrdenCompDetFECHA_MOD: TDateTimeField;
    qryViewOrdenCompDetNUMERO_DOCUMENTO: TIntegerField;
    qryViewOrdenCompDetNUMERO_FACTURA: TIntegerField;
    qryViewOrdenCompDetCOD_CTA_CONCEPTO: TIntegerField;
    qryViewOrdenCompDetTIPOSERVICIO: TIntegerField;
    qryViewOrdenCompDetSUBTIPOSERV: TIntegerField;
    qryViewOrdenCompDetNO_SERIE_RES: TIntegerField;
    qryViewOrdenCompDetCODIGO_CONDUCTOR: TIntegerField;
    qryViewOrdenCompDetSERIE_CDC: TIntegerField;
    qryViewOrdenCompDetCODIGO_SERVCOSTO: TIntegerField;
    qryViewOrdenCompDetNUMEROOLD: TIntegerField;
    qryViewOrdenCompDetPRECIO: TFloatField;
    qryViewOrdenCompDetAREA_ORDEN: TIntegerField;
    qryViewOrdenCompDetITBI_DET: TFloatField;
    qryViewOrdenCompDetPORC_DESC_DET: TFloatField;
    qryViewOrdenCompDetMONTO_DESCUENTO: TFloatField;
    dsqryViewOrdenCompMast: TDataSource;
    dsqryViewOrdenCompDet: TDataSource;
    qryViewOrdenCompMastNUMERO: TIntegerField;
    qryViewOrdenCompMastCODIGO_PROVEE: TIntegerField;
    qryViewOrdenCompMastFECHA: TDateTimeField;
    qryViewOrdenCompMastFPAGO: TSmallintField;
    qryViewOrdenCompMastCOD_CAJA_CHICA: TIntegerField;
    qryViewOrdenCompMastCODIGO_BANCO: TIntegerField;
    qryViewOrdenCompMastCUENTABANCO: TIBStringField;
    qryViewOrdenCompMastOBSERVACION: TIBStringField;
    qryViewOrdenCompMastMONTO: TFloatField;
    qryViewOrdenCompMastSTATUS: TIBStringField;
    qryViewOrdenCompMastTIPO_INV: TSmallintField;
    qryViewOrdenCompMastSTATUS_CNT: TIBStringField;
    qryViewOrdenCompMastNUM_ORDEN: TIntegerField;
    qryViewOrdenCompMastSTATUS_ORD: TIBStringField;
    qryViewOrdenCompMastAREA_ORDEN: TIntegerField;
    qryViewOrdenCompMastCIA_KEY: TIntegerField;
    qryViewOrdenCompMastNUMERO_NCF: TIBStringField;
    qryViewOrdenCompMastNOMBREPROVEEDOR: TIBStringField;
    qryOrdenMasterNUMERO_NCF: TIBStringField;
    qryOrdenMasterCODIGO_VENDEDOR: TIntegerField;
    qryDatosOrdenImpCONDICION: TIntegerField;
    qryDatosOrdenImpLIMITE_CREDITO: TFloatField;
    qryDatosOrdenImpFECHA_VENCE: TDateTimeField;
    tblDevolucionAbierta: TIBDataSet;
    tblDevolucionAbiertaNUMERO_DEVOLUCION: TIntegerField;
    tblDevolucionAbiertaMONEDA: TIBStringField;
    tblDevolucionAbiertaCODIGO_CTE: TIntegerField;
    tblDevolucionAbiertaMONTO_PENDIENTE: TFloatField;
    tblDevolucionAbiertaSTATUS: TIBStringField;
    tblDevolucionAbiertaFECHA_IN: TDateTimeField;
    tblDevolucionAbiertaIN_POR: TIBStringField;
    tblDevolucionAbiertaFECHA_MOD: TDateTimeField;
    tblDevolucionAbiertaMOD_POR: TIBStringField;
    tblDevolucionAbiertaNUMERO_TRN_VTA: TIntegerField;
    tblDevolucionAbiertaSERIE_TRNXCX: TIntegerField;
    tblPolizaMasterCODIGO_CTE: TIntegerField;
    qryDatosOrdenImpCONDICIONCREDITO: TIBStringField;
    tblPolizaDetCOLOR: TIBStringField;
    tblPolizaDetCASACONDUCTOR: TSmallintField;
    tblPolizaDetAUTOASISTENCIA: TSmallintField;
    qryRepPolizaCODIGO_CTE: TIntegerField;
    qryRepPolizaDEtCOLOR: TIBStringField;
    qryRepPolizaDEtCASACONDUCTOR: TSmallintField;
    qryRepPolizaDEtAUTOASISTENCIA: TSmallintField;
    qryConfCajaXusuario: TIBDataSet;
    qryConfCajaXusuarioCOD_EMPLEADO: TIntegerField;
    qryConfCajaXusuarioFECHAOPEN: TDateTimeField;
    qryConfCajaXusuarioFECHACLOSE: TDateTimeField;
    qryConfCajaXusuarioCOD_CAJA: TIntegerField;
    qryConfCajaXusuarioSTATUS: TIBStringField;
    qryConfCajaXusuarioID_FISCALPRINTER: TIntegerField;
    dsqryConfCajaXusuario: TDataSource;
    tblImpresoraFiscal: TIBTable;
    tblImpresoraFiscalID_FISCALPRINTER: TIntegerField;
    tblImpresoraFiscalFECHA_ENTRADA: TDateTimeField;
    tblImpresoraFiscalSERIE: TIBStringField;
    tblImpresoraFiscalMARCA: TIBStringField;
    tblImpresoraFiscalMODELO: TIBStringField;
    tblImpresoraFiscalVERSIONAPI: TIBStringField;
    tblImpresoraFiscalSTATUS: TIBStringField;
    tblImpresoraFiscalFECHA_SALIDA: TDateTimeField;
    tblImpresoraFiscalNUM_LOGO: TIntegerField;
    tblImpresoraFiscalPUERTO: TIBStringField;
    tblImpresoraFiscalBAUDRATE: TIntegerField;
    dstblImpresoraFiscal: TDataSource;
    tblTipoDocFiscal_L: TIBTable;
    IntegerField1: TIntegerField;
    IBStringField1: TIBStringField;
    dstblTipoDocFiscal_L: TDataSource;
    tblTipoDocFiscal: TIBTable;
    dstblTipoDocFiscal: TDataSource;
    qryImpresoraFiscalActiva: TIBQuery;
    qryImpresoraFiscalActivaMODELO: TIBStringField;
    tblTipoCF: TIBTable;
    dstblTipoCF: TDataSource;
    tblCaja: TIBTable;
    tblCajaCOD_CAJA: TIntegerField;
    tblCajaFECHA: TDateTimeField;
    tblCajaDESCRIPCION: TIBStringField;
    tblCajaBALANCE_ANT: TFloatField;
    tblCajaBALANCE_ACTUAL: TFloatField;
    tblCajaMONTO_ENTRADA_ACUM: TFloatField;
    tblCajaMONTO_RETIRADO_ACUM: TFloatField;
    tblCajaCOD_USUARIO: TIntegerField;
    tblCajaSTATUS: TIBStringField;
    dstblCaja: TDataSource;
    tblLineaDescDocF: TIBDataSet;
    tblLineaDescDocFIDLINEA: TIntegerField;
    tblLineaDescDocFITEM: TIntegerField;
    tblLineaDescDocFDESCRIPCION: TIBStringField;
    dstblLineaDescDocF: TDataSource;
    sqlLineaDescDocFGenMax: TIBSQL;
    tblNcftipoIFiscal: TIBTable;
    dstblNcftipoIFiscal: TDataSource;
    tblEmpleados: TIBTable;
    tblEmpleadosCODIGO: TIntegerField;
    tblEmpleadosCODIGO_CIA: TIntegerField;
    tblEmpleadosNOMBRE: TIBStringField;
    tblEmpleadosAPELLIDO: TIBStringField;
    tblEmpleadosCEDULA: TIBStringField;
    tblEmpleadosFOTO: TBlobField;
    tblEmpleadosPASSPORT: TIBStringField;
    tblEmpleadosCALLE: TIBStringField;
    tblEmpleadosNUM_CASA: TSmallintField;
    tblEmpleadosCIUDAD: TIBStringField;
    tblEmpleadosPAIS: TIBStringField;
    tblEmpleadosTELEF_CASA: TIBStringField;
    tblEmpleadosTELEF_OFICINA: TIBStringField;
    tblEmpleadosCELULAR: TIBStringField;
    tblEmpleadosEMAIL: TIBStringField;
    tblEmpleadosSEXO: TIBStringField;
    tblEmpleadosESTADO_CIVIL: TIBStringField;
    tblEmpleadosTELEF_REFERENCIA: TIBStringField;
    tblEmpleadosNOMBRE_REFERENCIA: TIBStringField;
    tblEmpleadosFECHA_NAC: TDateTimeField;
    tblEmpleadosNACIONALIDAD: TIBStringField;
    tblEmpleadosFECHA_ENTRADA: TDateTimeField;
    tblEmpleadosFECHA_SALIDA: TDateTimeField;
    tblEmpleadosSALARIO: TFloatField;
    tblEmpleadosTIPO_NOMINA: TSmallintField;
    tblEmpleadosTIPO_EMPLEADO: TSmallintField;
    tblEmpleadosDEPTO_EMP: TSmallintField;
    tblEmpleadosSECCION: TSmallintField;
    tblEmpleadosCARGO: TSmallintField;
    tblEmpleadosPAGA_AFP: TSmallintField;
    tblEmpleadosPAGA_TSS: TSmallintField;
    tblEmpleadosSTATUS: TIBStringField;
    tblEmpleadosFECHA_IN: TDateTimeField;
    tblEmpleadosIN_POR: TIBStringField;
    tblEmpleadosFECHA_MOD: TDateTimeField;
    tblEmpleadosMOD_POR: TIBStringField;
    tblEmpleadosLICENCIA: TIBStringField;
    tblEmpleadosFECHA_VENCE_LICENCIA: TDateTimeField;
    dstblEmpleados: TDataSource;
    tblTipoCFTIPO_CF: TIBStringField;
    tblTipoCFDESCRIPCION: TIBStringField;
    tblTipoDocFiscalTIPO: TIntegerField;
    tblTipoDocFiscalDESCRIPCION: TIBStringField;
    qryConfCajaXusuarioRUTA_TICKET: TIBStringField;
    qryRepPolizaDEtNOMBREASEGURADOCTE: TIBStringField;
    tblImpresoraFiscalRUTA_EXELIBROVENTA: TIBStringField;
    qryImpresoraFiscal: TIBQuery;
    qryImpresoraFiscalID_FISCALPRINTER: TIntegerField;
    qryImpresoraFiscalFECHA_ENTRADA: TDateTimeField;
    qryImpresoraFiscalSERIE: TIBStringField;
    qryImpresoraFiscalMARCA: TIBStringField;
    qryImpresoraFiscalMODELO: TIBStringField;
    qryImpresoraFiscalVERSIONAPI: TIBStringField;
    qryImpresoraFiscalSTATUS: TIBStringField;
    qryImpresoraFiscalFECHA_SALIDA: TDateTimeField;
    qryImpresoraFiscalNUM_LOGO: TIntegerField;
    qryImpresoraFiscalPUERTO: TIBStringField;
    qryImpresoraFiscalBAUDRATE: TIntegerField;
    qryImpresoraFiscalRUTA_EXELIBROVENTA: TIBStringField;
    tblNcftipoIFiscalTIPO_NCF: TIBStringField;
    tblNcftipoIFiscalTIPO_NCF_IFISCAL: TIntegerField;
    tblNcftipoIFiscalDESCRIPCION: TIBStringField;
    tblNcftipoIFiscalDescDocIFiscal: TStringField;
    tblNcftipoIFiscalDescDocFiscal: TStringField;
    tblNcftipoIFiscalTIPO_NCFNCR: TSmallintField;
    tblDescCotizacion: TIBDataSet;
    tblDescCotizacionIDLINEA: TIntegerField;
    tblDescCotizacionITEM: TIntegerField;
    tblDescCotizacionDESCRIPCION: TIBStringField;
    dstblDescCotizacion: TDataSource;
    tblTipoTrnCnt: TIBDataSet;
    tblTipoTrnCntSERIE: TIntegerField;
    tblTipoTrnCntTIPO_PERS: TSmallintField;
    tblTipoTrnCntTIPO_DOC: TSmallintField;
    tblTipoTrnCntIDCRITERIO: TSmallintField;
    tblTipoTrnCntDESCRIPCION: TIBStringField;
    tblTipoTrnCntEJEMPLO: TIBStringField;
    tblTipoTrnCntRETENCION_ISR: TSmallintField;
    tblTipoTrnCntRETENCION_ITBIS: TSmallintField;
    tblTipoTrnCntTASA_ITBIS: TFloatField;
    tblTipoTrnCntTASA_ISR: TFloatField;
    dstblTipoTrnCnt: TDataSource;
    tblCriterioTipodoc: TIBTable;
    tblCriterioTipodocIDCRITERIO: TSmallintField;
    tblCriterioTipodocDESCRIPCION: TIBStringField;
    dstblCriterioTipodoc: TDataSource;
    tblTipoTrnCntFECHA_INICIAL: TDateTimeField;
    tblTipoTrnCntFECHA_FINAL: TDateTimeField;
    qryOrdenMasterSERIE_TIPOTRNCNT: TIntegerField;
    qryOrdenMasterTASA_ITBIS: TFloatField;
    qryOrdenMasterTASA_ISR: TFloatField;
    qryOrdenMasterMONTO_RETENER_ISR: TFloatField;
    qryOrdenMasterMONTO_RETENER_ITBIS: TFloatField;
    tblEmail: TIBDataSet;
    tblEmailIDTIPO: TIntegerField;
    tblEmailSUBJECT: TIBStringField;
    tblEmailPORT: TIntegerField;
    tblEmailUSER_EMAIL: TIBStringField;
    tblEmailUSER_PASSWORD: TIBStringField;
    tblEmailFROMEMAIL: TIBStringField;
    tblEmailTOEMAIL: TIBStringField;
    tblEmailCCEMAIL: TIBStringField;
    tblEmailFECHAIN: TDateTimeField;
    tblEmailIN_POR: TIBStringField;
    tblEmailFECHA_UPDATE: TDateTimeField;
    tblEmailUPD_POR: TIBStringField;
    tblEmailSTATUS: TIBStringField;
    dstblEmail: TDataSource;
    stpInsEmailTracking: TIBStoredProc;
    qryEmailProceso: TIBQuery;
    qryEmailProcesoIDTIPO: TIntegerField;
    qryEmailProcesoSUBJECT: TIBStringField;
    qryEmailProcesoPORT: TIntegerField;
    qryEmailProcesoUSER_EMAIL: TIBStringField;
    qryEmailProcesoUSER_PASSWORD: TIBStringField;
    qryEmailProcesoFROMEMAIL: TIBStringField;
    qryEmailProcesoTOEMAIL: TIBStringField;
    qryEmailProcesoCCEMAIL: TIBStringField;
    qryEmailProcesoFECHAIN: TDateTimeField;
    qryEmailProcesoIN_POR: TIBStringField;
    qryEmailProcesoFECHA_UPDATE: TDateTimeField;
    qryEmailProcesoUPD_POR: TIBStringField;
    qryEmailProcesoSTATUS: TIBStringField;
    qryEmailProcesoEXEMAILTOOL: TIBStringField;
    tblImpresoraFiscalRUTALIBROVENTAS: TIBStringField;
    qryImpresoraFiscalRUTALIBROVENTAS: TIBStringField;
    qryMembrete: TIBQuery;
    qryMembreteCODIGO_CIA: TIntegerField;
    qryMembreteLINE_NO: TIntegerField;
    qryMembreteLINEA1: TIBStringField;
    qryMembreteLINEA2: TIBStringField;
    qryMembreteLINEA3: TIBStringField;
    qryMembreteLINEA4: TIBStringField;
    qryMembreteLINEA5: TIBStringField;
    qryImpresoraFiscalENCABEZADO: TIBStringField;
    tblImpresoraFiscalENCABEZADO: TIBStringField;
    qryDatosOrdenImpDetIDUNIDAD: TIntegerField;
    tblLineaDescDocFDetNotInUse: TIBDataSet;
    tblLineaDescDocFSTATUS: TIBStringField;
    qryImpresoras: TIBQuery;
    tblImpresora: TIBDataSet;
    tblImpresoraIDMODULO: TSmallintField;
    tblImpresoraIDREPORTE: TIntegerField;
    tblImpresoraNOMBRE_IMPRESORA: TIBStringField;
    tblImpresoraIN_POR: TIBStringField;
    tblImpresoraFECHA_IN: TDateTimeField;
    dstblImpresora: TDataSource;
    qryImpresorasIDMODULO: TSmallintField;
    qryImpresorasIDREPORTE: TIntegerField;
    qryImpresorasNOMBRE_IMPRESORA: TIBStringField;
    qryImpresorasIN_POR: TIBStringField;
    qryImpresorasFECHA_IN: TDateTimeField;
    tblDealer: TIBDataSet;
    tblDealerCODIGO_DEALER: TIntegerField;
    tblDealerDESCRIPCION: TIBStringField;
    dstblDealer: TDataSource;
    dstblAgencia: TDataSource;
    tblAgencia: TIBDataSet;
    tblAgenciaCODIGO_AGENCIA: TIntegerField;
    tblAgenciaDESCRIPCION: TIBStringField;
    tblConfComEmp: TIBDataSet;
    tblConfComEmpCODIGO_EMP: TIntegerField;
    tblConfComEmpCODIGO_COMISION: TIntegerField;
    dstblConfComEmp: TDataSource;
    tblConfComEmpNOMBREEMPLEADO: TIBStringField;
    tblConfComEmpIDCATEGORIA: TIntegerField;
    qryEmailProcesoEMAIL_SERVER: TIBStringField;
    tblEmailEMAIL_SERVER: TIBStringField;
    qryCantCambiosStatus: TIBQuery;
    qryCantCambiosStatusCANT_ACCION: TIntegerField;
    qryOrdenDetCANT_OFERTA: TIntegerField;
    qryOrdenDetIDUNIDAD: TIntegerField;
    qryOrdenDetCOD_USUARIO_RECIBE: TIntegerField;
    qryOrdenDetCOD_USUARIO_CREA: TIntegerField;
    tblDatosNotifyGEmail: TIBDataSet;
    tblDatosNotifyGEmailCHASSIS: TIBStringField;
    tblDatosNotifyGEmailCODIGO_CTE: TIntegerField;
    tblDatosNotifyGEmailNUMERO: TIntegerField;
    tblDatosNotifyGEmailNUM_CERTIFICADO: TIntegerField;
    tblDatosNotifyGEmailNUMPOL: TIntegerField;
    tblDatosNotifyGEmailNOTIFY_EMAIL: TSmallintField;
    qryEmailTemplate: TIBQuery;
    qryEmailTemplateID: TIntegerField;
    qryEmailTemplateCIA_KEY: TIntegerField;
    qryEmailTemplateIDTIPO: TIntegerField;
    qryEmailTemplateACCOUNT_ID: TIntegerField;
    qryEmailTemplateBODY: TMemoField;
    qryEmailTemplateSUBJECT: TIBStringField;
    tblTipoAfiliado: TIBTable;
    tblTipoAfiliadoIDTIPO: TIntegerField;
    tblTipoAfiliadoDESCRIPCION: TIBStringField;
    tblTipoAfiliadoRUTACARTABIENVENIDA: TIBStringField;
    tblEmailTemplate: TIBDataSet;
    tblEmailTemplateID: TIntegerField;
    tblEmailTemplateCIA_KEY: TIntegerField;
    tblEmailTemplateIDTIPO: TIntegerField;
    tblEmailTemplateACCOUNT_ID: TIntegerField;
    tblEmailTemplateBODY: TMemoField;
    tblEmailTemplateTIPOEMAIL: TIBStringField;
    tblEmailTemplateSUBJECT: TIBStringField;
    qryBuscarEmailTemplate: TIBQuery;
    qryEmailProcesoLookup: TIBQuery;
    qryEmailProcesoLookupIDTIPO: TIntegerField;
    qryEmailProcesoLookupSUBJECT: TIBStringField;
    tblEmailEXEMAILTOOL: TIBStringField;
    procedure qryInvAfterOpen(DataSet: TDataSet);
    procedure qryDatosOrdenImpAfterScroll(DataSet: TDataSet);
    procedure qryDatosSolOrdenImpAfterScroll(DataSet: TDataSet);
    procedure tblPolizaMasterAfterScroll(DataSet: TDataSet);
    procedure qryRepPolizaAfterScroll(DataSet: TDataSet);
    procedure qryViewOrdenCompMastAfterScroll(DataSet: TDataSet);
    procedure qryOrdenMasterAfterScroll(DataSet: TDataSet);
    procedure tblLineaDescDocFAfterScroll(DataSet: TDataSet);
    procedure tblConfComEmpFilterRecord(DataSet: TDataSet;
      var Accept: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
    codCatSel : Integer;
  end;

var
  dmDatos: TdmDatos;

implementation

uses UDatModConectar;//UDatModCon;

{$R *.dfm}
   
procedure TdmDatos.qryInvAfterOpen(DataSet: TDataSet);
begin
  //rxqryInv.Close;
  //rxqryInv.Open;
  //qryInv.First;
  //While Not qryInv.Eof do
  //begin
  //  rxqryInv.InsertRecord([qryInvCODIGO.Value,qryInvCODIGO_TEXTO.Value,
  //  qryInvDESCRIPCION.Value, qryInvPRECIO_COMPRA.Value, qryInvREFERENCIA.Value,
  //  qryInvPAGA_ITBI.Value]);
  //  qryInv.Next;
  //end;
  //rxqryInv.SortOnFields('descripcion', true, false);
end;

procedure TdmDatos.qryDatosOrdenImpAfterScroll(DataSet: TDataSet);
begin
  qryDatosOrdenImpDet.Close;
  qryDatosOrdenImpDet.Params[0].Value:=qryDatosOrdenImpNUMERO.Value;
  qryDatosOrdenImpDet.Open;
end;

procedure TdmDatos.qryDatosSolOrdenImpAfterScroll(DataSet: TDataSet);
begin
  qryDatosSolOrdenImpDet.Close;
  qryDatosSolOrdenImpDet.Params[0].Value:=qryDatosSolOrdenImpNUMERO.Value;
  qryDatosSolOrdenImpDet.Open;
end;

procedure TdmDatos.tblPolizaMasterAfterScroll(DataSet: TDataSet);
begin
  tblPolizaDet.Close;
  tblPolizaDet.Params[0].Value:= tblPolizaMasterNUMERO.Value;
  tblPolizaDet.Open;
end;

procedure TdmDatos.qryRepPolizaAfterScroll(DataSet: TDataSet);
begin
  qryRepPolizaDet.Close;
  qryRepPolizaDet.params[0].value:= qryRepPolizanumero.Value;
  qryRepPolizaDet.Open;
end;

procedure TdmDatos.qryViewOrdenCompMastAfterScroll(DataSet: TDataSet);
begin
  qryViewOrdenCompDet.Close;
  qryViewOrdenCompDet.Params[0].Value := qryViewOrdenCompMastNUMERO.Value;
  qryViewOrdenCompDet.Open;
end;

procedure TdmDatos.qryOrdenMasterAfterScroll(DataSet: TDataSet);
begin
  dmdatos.qryOrdenDet.Close;
  dmdatos.qryOrdenDet.Params[0].Value := qryOrdenMasterNUMERO.Value;
  dmdatos.qryOrdenDet.Open;
end;

procedure TdmDatos.tblLineaDescDocFAfterScroll(DataSet: TDataSet);
begin
{  tblLineaDescDocFDet.Close;
  tblLineaDescDocFDet.params[0].Value:= tblLineaDescDocFIDLINEA.Value;
  tblLineaDescDocFDet.Open;}
end;

procedure TdmDatos.tblConfComEmpFilterRecord(DataSet: TDataSet;
  var Accept: Boolean);
begin
  if (codCatSel > 0) then
  Accept:= DataSet['IDCATEGORIA'] = codCatSel;
end;

End.
