unit UDatModFactura;

interface

uses
  SysUtils, Classes, DB, IBCustomDataSet, IBTable, IBQuery, IBStoredProc,
  Dialogs, IBSQL;

type
  TdmFactura = class(TDataModule)
    IBDataSetFacturas: TIBDataSet;
    dtIBDataSetFacturas: TDataSource;
    IBDatosFctPago: TIBDataSet;
    dtIBDatosFctPago: TDataSource;
    IBDatosFctPagoFECHA: TDateTimeField;
    IBDatosFctPagoNUMERO: TIntegerField;
    IBDatosFctPagoMONTO_FACT: TFloatField;
    IBDataSetPagoFct: TIBDataSet;
    IBDataSetPagoFctSERIE: TIntegerField;
    IBDataSetPagoFctNUMERO_FACTURA: TIntegerField;
    IBDataSetPagoFctNUMERO_RECIBO: TIntegerField;
    IBDataSetPagoFctMONTO_PAGADO: TFloatField;
    IBDataSetPagoFctSTATUS: TIBStringField;
    IBDataSetPagoFctFECHA_IN: TDateTimeField;
    IBDataSetPagoFctIN_POR: TIBStringField;
    IBDataSetPagoFctFECHA_MOD: TDateTimeField;
    IBDataSetPagoFctMOD_POR: TIBStringField;
    dtIBDataSetPagoFct: TDataSource;
    ibQryViewNCF: TIBQuery;
    ibQryViewNCFID: TIBStringField;
    ibQryViewNCFSERIE: TIBStringField;
    ibQryViewNCFDIV_NEGOCIO: TIBStringField;
    ibQryViewNCFPECF: TIBStringField;
    ibQryViewNCFAICF: TIBStringField;
    ibQryViewNCFTIPO_CF: TIBStringField;
    ibQryViewNCFNCF: TFloatField;
    dstblDgii_SerieNCF: TDataSource;
    tblDgii_SerieNCF: TIBTable;
    tblDgii_SerieNCFNCF: TFloatField;
    tblDgii_SerieNCFFECHA_IN: TDateTimeField;
    tblDgii_SerieNCFFECHA_UPD: TDateTimeField;
    tblDgii_SerieNCFACTIVO: TSmallintField;
    tblDgii_SerieNCFSERIE: TIBStringField;
    tblDgii_SerieNCFDIV_NEGOCIO: TIBStringField;
    tblDgii_SerieNCFPECF: TIBStringField;
    tblDgii_SerieNCFAICF: TIBStringField;
    tblDgii_SerieNCFTIPO_CF: TIBStringField;
    dsibQryViewNCF: TDataSource;
    dstblTipoCF: TDataSource;
    tblTipoCF: TIBTable;
    tblTipoCFTIPO_CF: TIBStringField;
    tblTipoCFDESCRIPCION: TIBStringField;
    QryHistSecNCF: TIBQuery;
    QryHistSecNCFID_SERIE: TIntegerField;
    QryHistSecNCFIDNCF: TIBStringField;
    QryHistSecNCFINICIO_SECUECIA: TIntegerField;
    QryHistSecNCFFIN_SECUENCIA: TIntegerField;
    QryHistSecNCFFECHA_ASIGNACION: TDateTimeField;
    tblQryHistoricoSecNCF: TIBDataSet;
    tblQryHistoricoSecNCFID_SERIE: TIntegerField;
    tblQryHistoricoSecNCFIDNCF: TIBStringField;
    tblQryHistoricoSecNCFINICIO_SECUECIA: TIntegerField;
    tblQryHistoricoSecNCFFIN_SECUENCIA: TIntegerField;
    tblQryHistoricoSecNCFFECHA_ASIGNACION: TDateTimeField;
    ibStpVerificaSEC_NCF: TIBStoredProc;
    stpProcInsFactPendiente: TIBStoredProc;
    IBDataSetFacturasSERIE: TFloatField;
    IBDataSetFacturasNUMERO: TFloatField;
    IBDataSetFacturasMONEDA: TIBStringField;
    IBDataSetFacturasTIPO: TSmallintField;
    IBDataSetFacturasCODIGO_CTE: TIntegerField;
    IBDataSetFacturasFECHA: TDateTimeField;
    IBDataSetFacturasDESCRIPCION: TIBStringField;
    IBDataSetFacturasMONTO_FACT: TFloatField;
    IBDataSetFacturasRCXC: TIBStringField;
    IBDataSetFacturasRCNT: TIBStringField;
    IBDataSetFacturasSTATUS: TIBStringField;
    IBDataSetFacturasFECHA_IN: TDateTimeField;
    IBDataSetFacturasIN_POR: TIBStringField;
    IBDataSetFacturasFECHA_MOD: TDateTimeField;
    IBDataSetFacturasMOD_POR: TIBStringField;
    qryRepItbis: TIBQuery;
    qryRepItbisCODIGO_CTE: TIntegerField;
    qryRepItbisITBI_DET: TFloatField;
    qryRepItbisFECHA: TDateTimeField;
    qryRepItbisMONEDA: TIBStringField;
    qryRepItbisNUMERO: TIntegerField;
    qryRepItbisRNC_NUMERO: TIBStringField;
    qryRepItbisCEDULA: TIBStringField;
    qryRepItbisVALOR_TOTAL_DET: TFloatField;
    qryFactReimpMaster: TIBQuery;
    qryFactReimpDet: TIBQuery;
    qryFactReimpMasterNUMERO: TFloatField;
    qryFactReimpMasterCODIGO_CTE: TIntegerField;
    qryFactReimpMasterFECHA: TDateTimeField;
    qryFactReimpMasterMONTO_FACT: TFloatField;
    qryFactReimpMasterNOMBRE_CTE: TIBStringField;
    qryFactReimpMasterRNC_NUMERO: TIBStringField;
    qryFactReimpMasterTELEF_CONTACTO: TIBStringField;
    qryFactReimpMasterPAIS: TIBStringField;
    qryFactReimpMasterCIUDAD: TIBStringField;
    qryFactReimpMasterDIRECCION_CONT: TIBStringField;
    qryRepItbisNUMERO_NCF: TIBStringField;
    tblProgServIguala: TIBDataSet;
    tblProgServIgualaNUMERO: TIntegerField;
    tblProgServIgualaCODIGO_CTE: TIntegerField;
    tblProgServIgualaFECHA_INI: TDateTimeField;
    tblProgServIgualaFECHA_FIN: TDateTimeField;
    tblProgServIgualaFECHA_ULT_FACT: TDateTimeField;
    tblProgServIgualaCOD_SERVICIO: TIntegerField;
    tblProgServIgualaMONTO: TFloatField;
    tblProgServIgualaCARGAR_ITBIS: TSmallintField;
    tblProgServIgualaSTATUS: TIBStringField;
    tblProgServIgualaCOD_USUARIO_IN: TIntegerField;
    tblProgServIgualaINSERTADO_POR: TIBStringField;
    tblProgServIgualaFECHA_UPDATE: TDateTimeField;
    tblProgServIgualaCOD_USUARIO_UPDATE: TIntegerField;
    tblServProgIgualasTEMP: TIBTable;
    dstblProgServIguala: TDataSource;
    tblServProgIgualasTEMPCODIGO: TSmallintField;
    dstblServProgIgualas: TDataSource;
    qryFactServFReimpMaster: TIBQuery;
    qryFactServFReimpDet: TIBQuery;
    qryFactServFReimpMasterNUMERO: TFloatField;
    qryFactServFReimpMasterCODIGO_CTE: TIntegerField;
    qryFactServFReimpMasterFECHA: TDateTimeField;
    qryFactServFReimpMasterMONTO_FACT: TFloatField;
    qryFactServFReimpMasterNOMBRE_CTE: TIBStringField;
    qryFactServFReimpMasterRNC_NUMERO: TIBStringField;
    qryFactServFReimpMasterTELEF_CONTACTO: TIBStringField;
    qryFactServFReimpMasterPAIS: TIBStringField;
    qryFactServFReimpMasterCIUDAD: TIBStringField;
    qryFactServFReimpMasterDIRECCION_CONT: TIBStringField;
    tblProgServIgualaTIPO_NCF: TIBStringField;
    tblServProgIguala: TIBTable;
    tblServProgIgualaCODIGO: TSmallintField;
    qryServProgIguala: TIBQuery;
    qryServProgIgualaCODIGO: TSmallintField;
    tblProgServIgualaDescripcionServicio: TStringField;
    dsqryServProgIguala: TDataSource;
    dstblServProgIguala: TDataSource;
    tblServProgIgualaDESCRIPCION: TIBStringField;
    qryServProgIgualaDESCRIPCION: TIBStringField;
    qryRepItbis_Esp: TIBQuery;
    qryRepItbis_EspCODIGO_CTE: TIntegerField;
    qryRepItbis_EspITBI_DET: TFloatField;
    qryRepItbis_EspNOMBRE_CTE: TIBStringField;
    qryRepItbis_EspFECHA: TDateTimeField;
    qryRepItbis_EspMONEDA: TIBStringField;
    qryRepItbis_EspVALOR_TOTAL_DET: TFloatField;
    qryRepItbis_EspNUMERO: TIntegerField;
    qryRepItbis_EspRNC_NUMERO: TIBStringField;
    qryRepItbis_EspCEDULA: TIBStringField;
    qryRepItbis_EspNUMERO_NCF: TIBStringField;
    tblProgServIgualaFECHA_IN: TDateTimeField;
    qryFactReimpMasterFECHA_VENCE: TDateTimeField;
    IBDataSetFacturasFECHA_VENCE: TDateTimeField;
    tblServProgIgualasTEMPDESCRIPCION: TIBStringField;
    qryRepItbisNUMERODOC: TIBStringField;
    qryRepItbisTIPODOC: TIBStringField;
    tblConfDescuentoFactura: TIBTable;
    tblConfDescuentoFacturaTIPO: TSmallintField;
    tblConfDescuentoFacturaDESCRIPCION: TIBStringField;
    tblConfDescuentoFacturaPORCIENTO: TFloatField;
    tblConfDescuentoFacturaFECHAINI: TDateTimeField;
    tblConfDescuentoFacturaFECHAFIN: TDateTimeField;
    tblConfDescuentoFacturaSTATUS: TIBStringField;
    dstblConfDescuentoFactura: TDataSource;
    tblConfDescuentoFacturaFORMULA: TIBStringField;
    tblTemplateMaster: TIBDataSet;
    tblTemplateTipoDoc: TIBTable;
    tblTemplateTipoDocIDDOC: TSmallintField;
    tblTemplateTipoDocNOMBRE_TEMPLATE: TIBStringField;
    tblTemplateTipoDocSTATUS: TIBStringField;
    tblTemplateMasterNUMEROID: TIntegerField;
    tblTemplateMasterIDDOC: TSmallintField;
    tblTemplateMasterFECHA: TDateTimeField;
    tblTemplateMasterNOMBRE_ARCHIVO: TIBStringField;
    tblTemplateMasterSTATUS: TIBStringField;
    tblTemplateDet: TIBDataSet;
    dstblTemplateMaster: TDataSource;
    dstblTemplateTipoDoc: TDataSource;
    dstblTemplateDet: TDataSource;
    tblTemplateDetSERIEID: TIntegerField;
    tblTemplateDetNUMEROID: TIntegerField;
    tblTemplateDetNOMBRE_CAMPO: TIBStringField;
    tblTemplateDetDESCRIPCION_LABEL: TIBStringField;
    tblTemplateDetCOLUMNA_NOMBRE: TIBStringField;
    tblTemplateDetFILE_NUMERO: TIBStringField;
    tblTemplateDetSTATUS: TIBStringField;
    tblTemplateTipoDocLookup: TIBTable;
    tblTemplateTipoDocLookupIDDOC: TSmallintField;
    tblTemplateTipoDocLookupNOMBRE_TEMPLATE: TIBStringField;
    tblTemplateTipoDocLookupSTATUS: TIBStringField;
    dstblTemplateTipoDocLookup: TDataSource;
    tblTemplateDetISDETAIL: TSmallintField;
    qryTemplateFactura: TIBQuery;
    qryTemplateFacturaNOMBRE_ARCHIVO: TIBStringField;
    qryTemplateFacturaNOMBRE_TEMPLATE: TIBStringField;
    qryTemplateFacturaSERIEID: TIntegerField;
    qryTemplateFacturaNUMEROID: TIntegerField;
    qryTemplateFacturaNOMBRE_CAMPO: TIBStringField;
    qryTemplateFacturaDESCRIPCION_LABEL: TIBStringField;
    qryTemplateFacturaCOLUMNA_NOMBRE: TIBStringField;
    qryTemplateFacturaFILE_NUMERO: TIBStringField;
    qryTemplateFacturaISDETAIL: TSmallintField;
    qryTemplateFacturaSTATUS: TIBStringField;
    qryVentaFactura: TIBQuery;
    qryVentaFacturaNUMERO: TIntegerField;
    qryVentaFacturaFECHA: TDateTimeField;
    qryVentaFacturaCIA_KEY: TIntegerField;
    qryVentaFacturaCODIGO_CTE: TIntegerField;
    qryVentaFacturaCODIGO_VENDEDOR: TIntegerField;
    qryVentaFacturaFORMA_PAGO: TSmallintField;
    qryVentaFacturaOBSERVACION: TIBStringField;
    qryVentaFacturaMONEDA: TIBStringField;
    qryVentaFacturaVALOR_TOTAL_DET: TFloatField;
    qryVentaFacturaSTATUS: TIBStringField;
    qryVentaFacturaFECHA_IN: TDateTimeField;
    qryVentaFacturaIN_POR: TIBStringField;
    qryVentaFacturaFECHA_MOD: TDateTimeField;
    qryVentaFacturaMOD_POR: TIBStringField;
    qryVentaFacturaNUMERO_FACTURA: TIntegerField;
    qryVentaFacturaNUMERO_DOC_PAGO: TIBStringField;
    qryVentaFacturaSERIE_NCF_ASIGNADO: TIntegerField;
    qryVentaFacturaMONTO_BRUTO: TFloatField;
    qryVentaFacturaPORC_DESCUENTO: TIntegerField;
    qryVentaFacturaMONTO_DESCUENTO: TFloatField;
    qryVentaFacturaMONTO_INICIAL: TFloatField;
    qryVentaFacturaNOMBRE_CLIENTE_GENERAL: TIBStringField;
    qryVentaFacturaMONTO_PAGADO: TFloatField;
    qryVentaFacturaMONTO_CAMBIO: TFloatField;
    qryVentaFacturaMONTO_TOTAL_ITBIS: TFloatField;
    qryVentaFacturaDet: TIBQuery;
    dsqryVentaFactura: TDataSource;
    qryVentaFacturaTIPO_CLIENTE: TSmallintField;
    qryVentaFacturaNOMBRE_CTE: TIBStringField;
    qryVentaFacturaNOMBRE_ABREV: TIBStringField;
    qryVentaFacturaDIRECCION_CONT: TIBStringField;
    qryVentaFacturaTELEF_CONTACTO: TIBStringField;
    qryVentaFacturaFORMA_PAGO1: TSmallintField;
    qryVentaFacturaLIMITE_CREDITO: TFloatField;
    qryVentaFacturaEMAIL: TIBStringField;
    qryVentaFacturaPAIS: TIBStringField;
    qryVentaFacturaCIUDAD: TIBStringField;
    qryVentaFacturaCEDULA: TIBStringField;
    qryVentaFacturaRNC: TIBStringField;
    qryVentaFacturaCANT_DIAS_CREDITO: TSmallintField;
    qryVentaFacturaRNC_NUMERO: TIBStringField;
    qryVentaFacturaCONDICION: TIntegerField;
    qryVentaFacturaPRECIO_ID: TIntegerField;
    qryVentaFacturaDetDESC_TIPO_NCF: TIBStringField;
    qryVentaFacturaDetSERIE: TIntegerField;
    qryVentaFacturaDetCODIGO_PROD: TIBStringField;
    qryVentaFacturaDetCANTIDAD: TFloatField;
    qryVentaFacturaDetPRECIO: TFloatField;
    qryVentaFacturaDetPORC_DESC_DET: TFloatField;
    qryVentaFacturaDetITBI_DET: TFloatField;
    qryVentaFacturaDetVALOR_SERVICIO_DET: TFloatField;
    qryVentaFacturaDetVALOR_TOTAL_DET: TFloatField;
    qryVentaFacturaDetNUMERO_FACTURA: TIntegerField;
    qryVentaFacturaDetSTATUS_DET: TIBStringField;
    qryVentaFacturaDetSERIE_NCF_ASIGNADO: TIntegerField;
    qryVentaFacturaDetNUMERO_NCF: TIBStringField;
    qryVentaFacturaDetMONTO_DESCUENTO: TFloatField;
    qryVentaFacturaDetNUMERO: TIntegerField;
    qryVentaFacturaDetCODIGO_BARRA: TIBStringField;
    qryVentaFacturaDetNUM_FACTURA: TFloatField;
    qryVentaFacturaDetFECHA_IN: TDateTimeField;
    qryVentaFacturaDetIN_POR: TIBStringField;
    qryVentaFacturaDetFECHA_MOD: TDateTimeField;
    qryVentaFacturaDetMOD_POR: TIBStringField;
    qryVentaFacturaDetCANT_REGRESO: TFloatField;
    qryVentaFacturaDetCANT_PROMO: TFloatField;
    qryVentaFacturaDetMONTO_DIETA: TFloatField;
    qryVentaFacturaDetMONTO_AJUSTE: TFloatField;
    qryVentaFacturaDetSERIE_PROD: TIBStringField;
    qryVentaFacturaDetSTATUS_CNT: TIBStringField;
    qryVentaFacturaDetTIPO_UNIDAD: TIntegerField;
    qryVentaFacturaDetITBIS_EXENTO: TSmallintField;
    qryVentaFacturaDetTIPO_VENTA: TSmallintField;
    qryVentaFacturaDetDESCRIPCIONPRODUCTO: TMemoField;
    dsqryVentaFacturaDet: TDataSource;
    qryVentaFactura_0: TIBQuery;
    qryVentaFacturaTIPO_FACTURA: TSmallintField;
    qryVentaFacturaAPLICA_TIPODESC: TSmallintField;
    qryVentaFacturaMONTODESCGASTOSADMIN: TFloatField;
    qryVentaFacturaMONTODESCITBISGASTOSADMIN: TFloatField;
    qryVentaFacturaMONTODESCTRANSP: TFloatField;
    qryVentaFacturaMONTODESCDIRTECNICA: TFloatField;
    qryVentaFacturaMONTODESCITBISDIRTECNICA: TFloatField;
    qryVentaFacturaMONTODESCIMPREVISTO: TFloatField;
    qryVentaFacturaMONTODESCITBISIMPREVISTO: TFloatField;
    qryVentaFacturaSERIEFACTURA: TFloatField;
    qryVentaFacturaNUMEROFACTURA: TFloatField;
    qryVentaFacturaMONEDAFACTURA: TIBStringField;
    qryVentaFacturaTIPOFACTURA: TSmallintField;
    qryDatosTrncxc: TIBQuery;
    IBDataSetFacturasTIPO_FACTURA: TSmallintField;
    IBDataSetFacturasAPLICA_TIPODESC: TSmallintField;
    qryVentaFacturaCONDICIONCREDITO: TIBStringField;
    qryPorcApplicadoenFactServ: TIBQuery;
    qryPorcApplicadoenFactServPORCGADMIN: TFloatField;
    qryPorcApplicadoenFactServPORCITBISGADMIN: TFloatField;
    qryPorcApplicadoenFactServPORCTRANS: TFloatField;
    qryPorcApplicadoenFactServPORCDIRTEC: TFloatField;
    qryPorcApplicadoenFactServPORCITBISDIRTEC: TFloatField;
    qryPorcApplicadoenFactServPORCIMPREVISTO: TFloatField;
    qryPorcApplicadoenFactServPORCITBISIMPREVISTO: TFloatField;
    stpPorcOtrosCargosFactServ: TIBStoredProc;
    stpInsertPorcOtrosCargosFServ: TIBStoredProc;
    qryVentaFacturaNUMERO_NCF: TIBStringField;
    qryVentaFacturaDESCRIPCION_NCF: TIBStringField;
    ibsqlEliminarSerieVentaDet: TIBSQL;
    tblTemplateDetSECCION: TIBStringField;
    qryRepCotizaNew: TIBQuery;
    qryRepCotizaNewTIPO_CLIENTE: TSmallintField;
    qryRepCotizaNewNOMBRE_CTE: TIBStringField;
    qryRepCotizaNewNOMBRE_ABREV: TIBStringField;
    qryRepCotizaNewNOMBRE_FACTURAR: TIBStringField;
    qryRepCotizaNewDIRECCION_CONT: TIBStringField;
    qryRepCotizaNewTELEF_CONTACTO: TIBStringField;
    qryRepCotizaNewFORMA_PAGO: TSmallintField;
    qryRepCotizaNewLIMITE_CREDITO: TFloatField;
    qryRepCotizaNewEMAIL: TIBStringField;
    qryRepCotizaNewPAIS: TIBStringField;
    qryRepCotizaNewCIUDAD: TIBStringField;
    qryRepCotizaNewCEDULA: TIBStringField;
    qryRepCotizaNewRNC: TIBStringField;
    qryRepCotizaNewCANT_DIAS_CREDITO: TSmallintField;
    qryRepCotizaNewRNC_NUMERO: TIBStringField;
    qryRepCotizaNewCONDICION: TSmallintField;
    qryRepCotizaNewPRECIO_ID: TSmallintField;
    qryRepCotizaNewNUMERO: TIntegerField;
    qryRepCotizaNewFECHA: TDateTimeField;
    qryRepCotizaNewCIA_KEY: TSmallintField;
    qryRepCotizaNewFECHA_VENCE: TDateTimeField;
    qryRepCotizaNewCODIGO_CTE: TSmallintField;
    qryRepCotizaNewCODIGO_VENDEDOR: TSmallintField;
    qryRepCotizaNewOBSERVACION: TIBStringField;
    qryRepCotizaNewMONEDA: TIBStringField;
    qryRepCotizaNewVALOR_TOTAL: TFloatField;
    qryRepCotizaNewSTATUS: TIBStringField;
    qryRepCotizaNewFECHA_IN: TDateTimeField;
    qryRepCotizaNewIN_POR: TIBStringField;
    qryRepCotizaNewFECHA_MOD: TDateTimeField;
    qryRepCotizaNewMOD_POR: TIBStringField;
    qryRepCotizaNewNUMERO_FACTURA: TSmallintField;
    qryRepCotizaNewNUMERO_DOC_PAGO: TIBStringField;
    qryRepCotizaNewSERIE_NCF_ASIGNADO: TSmallintField;
    qryRepCotizaNewMONTO_BRUTO: TFloatField;
    qryRepCotizaNewPORC_DESCUENTO: TSmallintField;
    qryRepCotizaNewMONTO_DESCUENTO: TFloatField;
    qryRepCotizaNewMONTO_INICIAL: TFloatField;
    qryRepCotizaNewNOMBRE_CLIENTE_GENERAL: TIBStringField;
    qryRepCotizaNewMONTO_PAGADO: TFloatField;
    qryRepCotizaNewMONTO_CAMBIO: TFloatField;
    qryRepCotizaNewMONTO_TOTAL_ITBIS: TFloatField;
    qryRepCotizaNewMONTODESCGASTOSADMIN: TFloatField;
    qryRepCotizaNewMONTODESCITBISGASTOSADMIN: TFloatField;
    qryRepCotizaNewMONTODESCTRANSP: TFloatField;
    qryRepCotizaNewMONTODESCDIRTECNICA: TFloatField;
    qryRepCotizaNewMONTODESCITBISDIRTECNICA: TFloatField;
    qryRepCotizaNewMONTODESCIMPREVISTO: TFloatField;
    qryRepCotizaNewMONTODESCITBISIMPREVISTO: TFloatField;
    qryRepCotizaNewTIPO_FACTURA: TSmallintField;
    qryRepCotizaNewAPLICA_TIPODESC: TSmallintField;
    qryRepCotizaNewMONEDA_FACT: TIBStringField;
    qryRepCotizaDetNew: TIBQuery;
    ibstpInsertarPorcOtrosCargosCotiza: TIBStoredProc;
    qryPorcOtrosCargosCotiza: TIBQuery;
    qryPorcOtrosCargosCotizaNUMERO_TRN: TIntegerField;
    qryPorcOtrosCargosCotizaPORCGADMIN: TFloatField;
    qryPorcOtrosCargosCotizaPORCITBISGADMIN: TFloatField;
    qryPorcOtrosCargosCotizaPORCTRANS: TFloatField;
    qryPorcOtrosCargosCotizaPORCDIRTEC: TFloatField;
    qryPorcOtrosCargosCotizaPORCITBISDIRTEC: TFloatField;
    qryPorcOtrosCargosCotizaPORCIMPREVISTO: TFloatField;
    qryPorcOtrosCargosCotizaPORCITBISIMPREVISTO: TFloatField;
    qryVentaFacturaSUBTOTALINDIRECTOS: TFloatField;
    qryVentaFacturaCOMENTARIO: TIBStringField;
    IBDataSetFacturasCIA_KEY: TIntegerField;
    qryVentaFacturaConsigna: TIBQuery;
    qryVentaFacturaConsignaNUMERO: TIntegerField;
    qryVentaFacturaConsignaFECHA: TDateTimeField;
    qryVentaFacturaConsignaCIA_KEY: TIntegerField;
    qryVentaFacturaConsignaCODIGO_CTE: TIntegerField;
    qryVentaFacturaConsignaCODIGO_VENDEDOR: TIntegerField;
    qryVentaFacturaConsignaFORMA_PAGO: TSmallintField;
    qryVentaFacturaConsignaOBSERVACION: TIBStringField;
    qryVentaFacturaConsignaMONEDA: TIBStringField;
    qryVentaFacturaConsignaVALOR_TOTAL_DET: TFloatField;
    qryVentaFacturaConsignaSTATUS: TIBStringField;
    qryVentaFacturaConsignaFECHA_IN: TDateTimeField;
    qryVentaFacturaConsignaIN_POR: TIBStringField;
    qryVentaFacturaConsignaFECHA_MOD: TDateTimeField;
    qryVentaFacturaConsignaMOD_POR: TIBStringField;
    qryVentaFacturaConsignaNUMERO_DOC_PAGO: TIBStringField;
    qryVentaFacturaConsignaSERIE_NCF_ASIGNADO: TIntegerField;
    qryVentaFacturaConsignaMONTO_BRUTO: TFloatField;
    qryVentaFacturaConsignaPORC_DESCUENTO: TIntegerField;
    qryVentaFacturaConsignaMONTO_DESCUENTO: TFloatField;
    qryVentaFacturaConsignaMONTO_INICIAL: TFloatField;
    qryVentaFacturaConsignaNOMBRE_CLIENTE_GENERAL: TIBStringField;
    qryVentaFacturaConsignaMONTO_PAGADO: TFloatField;
    qryVentaFacturaConsignaMONTO_CAMBIO: TFloatField;
    qryVentaFacturaConsignaMONTO_TOTAL_ITBIS: TFloatField;
    qryVentaFacturaConsignaTIPO_CLIENTE: TSmallintField;
    qryVentaFacturaConsignaNOMBRE_CTE: TIBStringField;
    qryVentaFacturaConsignaNOMBRE_ABREV: TIBStringField;
    qryVentaFacturaConsignaNOMBRE_FACTURAR: TIBStringField;
    qryVentaFacturaConsignaDIRECCION_CONT: TIBStringField;
    qryVentaFacturaConsignaTELEF_CONTACTO: TIBStringField;
    qryVentaFacturaConsignaFORMA_PAGO1: TSmallintField;
    qryVentaFacturaConsignaLIMITE_CREDITO: TFloatField;
    qryVentaFacturaConsignaEMAIL: TIBStringField;
    qryVentaFacturaConsignaPAIS: TIBStringField;
    qryVentaFacturaConsignaCIUDAD: TIBStringField;
    qryVentaFacturaConsignaCEDULA: TIBStringField;
    qryVentaFacturaConsignaRNC: TIBStringField;
    qryVentaFacturaConsignaCANT_DIAS_CREDITO: TSmallintField;
    qryVentaFacturaConsignaRNC_NUMERO: TIBStringField;
    qryVentaFacturaConsignaCONDICION: TIntegerField;
    qryVentaFacturaConsignaPRECIO_ID: TIntegerField;
    qryVentaFacturaConsignaTIPO_FACTURA: TIBStringField;
    qryVentaFacturaConsignaAPLICA_TIPODESC: TIBStringField;
    qryVentaFacturaConsignaMONTODESCGASTOSADMIN: TFloatField;
    qryVentaFacturaConsignaMONTODESCITBISGASTOSADMIN: TFloatField;
    qryVentaFacturaConsignaMONTODESCTRANSP: TFloatField;
    qryVentaFacturaConsignaMONTODESCDIRTECNICA: TFloatField;
    qryVentaFacturaConsignaMONTODESCITBISDIRTECNICA: TFloatField;
    qryVentaFacturaConsignaMONTODESCIMPREVISTO: TFloatField;
    qryVentaFacturaConsignaMONTODESCITBISIMPREVISTO: TFloatField;
    qryVentaFacturaConsignaSERIEFACTURA: TIBStringField;
    qryVentaFacturaConsignaMONEDAFACTURA: TIBStringField;
    qryVentaFacturaConsignaTIPOFACTURA: TIBStringField;
    qryVentaFacturaConsignaCONDICIONCREDITO: TIBStringField;
    qryVentaFacturaConsignaNUMERO_NCF: TIBStringField;
    qryVentaFacturaConsignaDESCRIPCION_NCF: TIBStringField;
    qryVentaFacturaConsignaSUBTOTALINDIRECTOS: TFloatField;
    qryVentaFacturaConsignaCOMENTARIO: TIBStringField;
    qryVentaFactura_csg0: TIBQuery;
    qryVentaFacturaDetConsigna: TIBQuery;
    qryVentaFacturaDetConsignaDESC_TIPO_NCF: TIBStringField;
    qryVentaFacturaDetConsignaSERIE: TIntegerField;
    qryVentaFacturaDetConsignaCODIGO_PROD: TIBStringField;
    qryVentaFacturaDetConsignaCANTIDAD: TFloatField;
    qryVentaFacturaDetConsignaPRECIO: TFloatField;
    qryVentaFacturaDetConsignaPORC_DESC_DET: TFloatField;
    qryVentaFacturaDetConsignaITBI_DET: TFloatField;
    qryVentaFacturaDetConsignaVALOR_SERVICIO_DET: TFloatField;
    qryVentaFacturaDetConsignaVALOR_TOTAL_DET: TFloatField;
    qryVentaFacturaDetConsignaNUMERO_FACTURA: TIntegerField;
    qryVentaFacturaDetConsignaSTATUS_DET: TIBStringField;
    qryVentaFacturaDetConsignaSERIE_NCF_ASIGNADO: TIntegerField;
    qryVentaFacturaDetConsignaNUMERO_NCF: TIBStringField;
    qryVentaFacturaDetConsignaMONTO_DESCUENTO: TFloatField;
    qryVentaFacturaDetConsignaNUMERO: TIntegerField;
    qryVentaFacturaDetConsignaCODIGO_BARRA: TIBStringField;
    qryVentaFacturaDetConsignaNUM_FACTURA: TFloatField;
    qryVentaFacturaDetConsignaFECHA_IN: TDateTimeField;
    qryVentaFacturaDetConsignaIN_POR: TIBStringField;
    qryVentaFacturaDetConsignaFECHA_MOD: TDateTimeField;
    qryVentaFacturaDetConsignaMOD_POR: TIBStringField;
    qryVentaFacturaDetConsignaCANT_REGRESO: TFloatField;
    qryVentaFacturaDetConsignaCANT_PROMO: TFloatField;
    qryVentaFacturaDetConsignaMONTO_DIETA: TFloatField;
    qryVentaFacturaDetConsignaMONTO_AJUSTE: TFloatField;
    qryVentaFacturaDetConsignaSERIE_PROD: TIBStringField;
    qryVentaFacturaDetConsignaSTATUS_CNT: TIBStringField;
    qryVentaFacturaDetConsignaTIPO_UNIDAD: TIntegerField;
    qryVentaFacturaDetConsignaITBIS_EXENTO: TSmallintField;
    qryVentaFacturaDetConsignaTIPO_VENTA: TSmallintField;
    qryVentaFacturaDetConsignaDESCRIPCION: TIBStringField;
    qryVentaFacturaDetConsignaDESCRIPCIONPRODUCTO: TMemoField;
    qryVentaFacturaConsignaNUMERO_FACTURA: TIntegerField;
    qryVentaFacturaConsignaNUMEROFACTURA: TIntegerField;
    dsqryVentaFacturaConsigna: TDataSource;
    dsqryVentaFacturaDetConsigna: TDataSource;
    ibsqlEliminarSerieVentaDet_csg: TIBSQL;
    qryRepCotizaDetNewTESTDESC: TMemoField;
    qryRepCotizaDetNewDESCRIPCIONESPECIAL: TMemoField;
    qryRepCotizaDetNewDESCRIPCION: TIBStringField;
    qryRepCotizaDetNewSERIE: TIntegerField;
    qryRepCotizaDetNewNUMERO: TIntegerField;
    qryRepCotizaDetNewCODIGO_PROD: TIBStringField;
    qryRepCotizaDetNewCODIGO_BARRA: TIBStringField;
    qryRepCotizaDetNewCANTIDAD: TFloatField;
    qryRepCotizaDetNewPRECIO: TFloatField;
    qryRepCotizaDetNewPORC_DESC_DET: TFloatField;
    qryRepCotizaDetNewITBI_DET: TFloatField;
    qryRepCotizaDetNewVALOR_SERVICIO_DET: TFloatField;
    qryRepCotizaDetNewVALOR_TOTAL_DET: TFloatField;
    qryRepCotizaDetNewSTATUS_DET: TIBStringField;
    qryRepCotizaDetNewFECHA_IN: TDateTimeField;
    qryRepCotizaDetNewIN_POR: TIBStringField;
    qryRepCotizaDetNewFECHA_MOD: TDateTimeField;
    qryRepCotizaDetNewMOD_POR: TIBStringField;
    qryRepCotizaDetNewCANT_REGRESO: TFloatField;
    qryRepCotizaDetNewCANT_PROMO: TFloatField;
    qryRepCotizaDetNewMONTO_DIETA: TFloatField;
    qryRepCotizaDetNewMONTO_AJUSTE: TFloatField;
    qryRepCotizaDetNewSERIE_PROD: TIBStringField;
    qryRepCotizaDetNewSTATUS_CNT: TIBStringField;
    qryRepCotizaDetNewTIPO_UNIDAD: TIntegerField;
    qryRepCotizaDetNewITBIS_EXENTO: TSmallintField;
    qryRepCotizaDetNewTIPO_VENTA: TSmallintField;
    qryVentaFacturaFechaVence: TDateTimeField;
    qryVentacontado_0: TIBQuery;
    qryVentaFacturaNOMBRE_FACTURAR: TIBStringField;
    qryVentaFacturaDetDESCRIPCION: TIBStringField;
    qryRepItbisNOMBRE_CTE: TIBStringField;
    qryRepCotizaNewCOMENTARIO: TMemoField;
    ibQryViewNCFDESCRIPCION: TIBStringField;
    stpProcDevolucion: TIBStoredProc;
    qryFactTieneDevolucion: TIBQuery;
    IBDataSetFacturasNUMERO_TRN_VTA: TIntegerField;
    qryFactReimpMasterMONEDA: TIBStringField;
    qryVentaServicio: TIBDataSet;
    qryVentaServicioSERIE: TIntegerField;
    qryVentaServicioFECHA: TDateTimeField;
    qryVentaServicioCODIGO_OPERARIO: TIntegerField;
    qryVentaServicioCODIGO_SERVICIO: TIntegerField;
    qryVentaServicioDESCRIPCION: TIBStringField;
    qryVentaServicioMONTO_SERVICIO: TFloatField;
    qryVentaServicioMONTO_COMISION: TFloatField;
    qryVentaServicioPORC_COMISION: TFloatField;
    qryVentaServicioMONTO_DESCUENTO: TFloatField;
    qryVentaServicioPORC_DESCUENTO: TFloatField;
    qryVentaServicioFECHA_IN: TDateTimeField;
    qryVentaServicioIN_POR: TIBStringField;
    qryVentaServicioFECHA_MOD: TDateTimeField;
    qryVentaServicioMOD_POR: TIBStringField;
    qryVentaServicioCOMENTARIO: TIBStringField;
    qryVentaServicioSTATUS: TIBStringField;
    qryVentaServicioCOD_USUARIO: TIntegerField;
    dsqryVentaServicio: TDataSource;
    qryVentaServicioCODIGO_CTE: TIntegerField;
    qryVentaServicioNUMERO_TRN: TIntegerField;
    qryRepItbisSTATUS: TIBStringField;
    qryRepItbis_EspTIPODOC: TIBStringField;
    qryRepItbis_EspNUMERODOC: TIBStringField;
    qryRepItbis_EspSTATUS: TIBStringField;
    qryVentaFacturaDetPRECIO_COMPRA: TFloatField;
    qryRepItbisVALOR_TASA: TFloatField;
    qryRepItbisFORMA_PAGO: TSmallintField;
    stpProcDevolPendiente: TIBStoredProc;
    qryFactReimpMasterDevol: TIBQuery;
    qryFactReimpDetDevol: TIBQuery;
    qryVentaFactDevolucion_base: TIBQuery;
    qryRepCotizaNewCONDICIONCREDITO: TIBStringField;
    qryUpdateVentasMast: TIBDataSet;
    qryUpdateVentasMastNUMERO: TIntegerField;
    qryUpdateVentasMastCODIGO_CTE: TIntegerField;
    qryUpdateVentasMastFECHA_MOD: TDateTimeField;
    qryUpdateVentasMastMOD_POR: TIBStringField;
    qryRepCotizaNewREFERENCIACTE: TIBStringField;
    qryVentaFacturaCOTIZACION_ORIGEN: TIntegerField;
    qryVentaFacturaREFERENCIACTE: TIBStringField;
    qryCotizacionConduce: TIBQuery;
    qryCotizacionConduceNUMERO: TIntegerField;
    qryCotizacionConduceFECHA: TDateTimeField;
    qryCotizacionConduceCIA_KEY: TIntegerField;
    qryCotizacionConduceCODIGO_CTE: TIntegerField;
    qryCotizacionConduceCODIGO_VENDEDOR: TIntegerField;
    qryCotizacionConduceOBSERVACION: TIBStringField;
    qryCotizacionConduceMONEDA: TIBStringField;
    qryCotizacionConduceVALOR_TOTAL_DET: TFloatField;
    qryCotizacionConduceSTATUS: TIBStringField;
    qryCotizacionConduceFECHA_IN: TDateTimeField;
    qryCotizacionConduceIN_POR: TIBStringField;
    qryCotizacionConduceFECHA_MOD: TDateTimeField;
    qryCotizacionConduceMOD_POR: TIBStringField;
    qryCotizacionConduceNUMERO_FACTURA: TIntegerField;
    qryCotizacionConduceNUMERO_DOC_PAGO: TIBStringField;
    qryCotizacionConduceSERIE_NCF_ASIGNADO: TIntegerField;
    qryCotizacionConduceMONTO_BRUTO: TFloatField;
    qryCotizacionConducePORC_DESCUENTO: TIntegerField;
    qryCotizacionConduceMONTO_DESCUENTO: TFloatField;
    qryCotizacionConduceMONTO_INICIAL: TFloatField;
    qryCotizacionConduceNOMBRE_CLIENTE_GENERAL: TIBStringField;
    qryCotizacionConduceMONTO_PAGADO: TFloatField;
    qryCotizacionConduceMONTO_CAMBIO: TFloatField;
    qryCotizacionConduceMONTO_TOTAL_ITBIS: TFloatField;
    qryCotizacionConduceTIPO_CLIENTE: TSmallintField;
    qryCotizacionConduceNOMBRE_CTE: TIBStringField;
    qryCotizacionConduceNOMBRE_ABREV: TIBStringField;
    qryCotizacionConduceNOMBRE_FACTURAR: TIBStringField;
    qryCotizacionConduceDIRECCION_CONT: TIBStringField;
    qryCotizacionConduceTELEF_CONTACTO: TIBStringField;
    qryCotizacionConduceFORMA_PAGO: TSmallintField;
    qryCotizacionConduceLIMITE_CREDITO: TFloatField;
    qryCotizacionConduceEMAIL: TIBStringField;
    qryCotizacionConducePAIS: TIBStringField;
    qryCotizacionConduceCIUDAD: TIBStringField;
    qryCotizacionConduceCEDULA: TIBStringField;
    qryCotizacionConduceRNC: TIBStringField;
    qryCotizacionConduceCANT_DIAS_CREDITO: TSmallintField;
    qryCotizacionConduceRNC_NUMERO: TIBStringField;
    qryCotizacionConduceCONDICION: TIntegerField;
    qryCotizacionConducePRECIO_ID: TIntegerField;
    qryCotizacionConduceMONTODESCGASTOSADMIN: TFloatField;
    qryCotizacionConduceMONTODESCITBISGASTOSADMIN: TFloatField;
    qryCotizacionConduceMONTODESCTRANSP: TFloatField;
    qryCotizacionConduceMONTODESCDIRTECNICA: TFloatField;
    qryCotizacionConduceMONTODESCITBISDIRTECNICA: TFloatField;
    qryCotizacionConduceMONTODESCIMPREVISTO: TFloatField;
    qryCotizacionConduceMONTODESCITBISIMPREVISTO: TFloatField;
    qryCotizacionConduceCONDICIONCREDITO: TIBStringField;
    qryCotizacionConduceNUMERO_NCF: TIBStringField;
    qryCotizacionConduceDESCRIPCION_NCF: TIBStringField;
    qryCotizacionConduceSUBTOTALINDIRECTOS: TFloatField;
    qryCotizacionConduceCOMENTARIO: TMemoField;
    qryCotizacionConduceCOTIZACION_ORIGEN: TIBStringField;
    qryCotizacionConduceREFERENCIACTE: TIBStringField;
    qryCotizacionConduceDet: TIBQuery;
    qryCotizacionConduceDetDESC_TIPO_NCF: TIBStringField;
    qryCotizacionConduceDetSERIE: TIntegerField;
    qryCotizacionConduceDetCODIGO_PROD: TIBStringField;
    qryCotizacionConduceDetCANTIDAD: TFloatField;
    qryCotizacionConduceDetPRECIO: TFloatField;
    qryCotizacionConduceDetPORC_DESC_DET: TFloatField;
    qryCotizacionConduceDetITBI_DET: TFloatField;
    qryCotizacionConduceDetVALOR_SERVICIO_DET: TFloatField;
    qryCotizacionConduceDetVALOR_TOTAL_DET: TFloatField;
    qryCotizacionConduceDetNUMERO_FACTURA: TIntegerField;
    qryCotizacionConduceDetSTATUS_DET: TIBStringField;
    qryCotizacionConduceDetSERIE_NCF_ASIGNADO: TIntegerField;
    qryCotizacionConduceDetNUMERO_NCF: TIBStringField;
    qryCotizacionConduceDetMONTO_DESCUENTO: TFloatField;
    qryCotizacionConduceDetNUMERO: TIntegerField;
    qryCotizacionConduceDetCODIGO_BARRA: TIBStringField;
    qryCotizacionConduceDetNUM_FACTURA: TIntegerField;
    qryCotizacionConduceDetFECHA_IN: TDateTimeField;
    qryCotizacionConduceDetIN_POR: TIBStringField;
    qryCotizacionConduceDetFECHA_MOD: TDateTimeField;
    qryCotizacionConduceDetMOD_POR: TIBStringField;
    qryCotizacionConduceDetCANT_REGRESO: TFloatField;
    qryCotizacionConduceDetCANT_PROMO: TFloatField;
    qryCotizacionConduceDetMONTO_DIETA: TFloatField;
    qryCotizacionConduceDetMONTO_AJUSTE: TFloatField;
    qryCotizacionConduceDetSERIE_PROD: TIBStringField;
    qryCotizacionConduceDetSTATUS_CNT: TIBStringField;
    qryCotizacionConduceDetTIPO_UNIDAD: TIntegerField;
    qryCotizacionConduceDetITBIS_EXENTO: TSmallintField;
    qryCotizacionConduceDetTIPO_VENTA: TSmallintField;
    qryCotizacionConduceDetDESCRIPCION: TIBStringField;
    qryCotizacionConduceDetPRECIO_COMPRA: TIntegerField;
    qryCotizacionConduceDetDESCRIPCIONPRODUCTO: TMemoField;
    qryVentaFacturaDetCANT_CONDUCE: TFloatField;
    qryCotizacionConduceDetCANT_CONDUCE: TFloatField;
    qryVerificaFact: TIBQuery;
    ibStpCancelaFactura: TIBStoredProc;
    qryFactReimpDetDESC_TIPO_NCF: TIBStringField;
    qryFactReimpDetSERIE: TIntegerField;
    qryFactReimpDetCODIGO_PROD: TIBStringField;
    qryFactReimpDetDESCRIPCION: TIBStringField;
    qryFactReimpDetREFERENCIA: TIBStringField;
    qryFactReimpDetCANTIDAD: TFloatField;
    qryFactReimpDetPRECIO: TFloatField;
    qryFactReimpDetPORC_DESC_DET: TFloatField;
    qryFactReimpDetITBI_DET: TFloatField;
    qryFactReimpDetVALOR_SERVICIO_DET: TFloatField;
    qryFactReimpDetVALOR_TOTAL_DET: TFloatField;
    qryFactReimpDetNUMERO_FACTURA: TIntegerField;
    qryFactReimpDetSTATUS_DET: TIBStringField;
    qryFactReimpDetSERIE_NCF_ASIGNADO: TIntegerField;
    qryFactReimpDetNUMERO_NCF: TIBStringField;
    qryFactReimpDetMONTO_DESCUENTO: TFloatField;
    qryFactReimpDetDESCTIPOUNIDAD: TIBStringField;
    qryFactReimpDetMONTO_DESC_ITEM: TFloatField;
    qryFactReimpDetDevolDESC_TIPO_NCF: TIBStringField;
    qryFactReimpDetDevolSERIE: TIntegerField;
    qryFactReimpDetDevolCODIGO_PROD: TIBStringField;
    qryFactReimpDetDevolDESCRIPCION: TIBStringField;
    qryFactReimpDetDevolREFERENCIA: TIBStringField;
    qryFactReimpDetDevolCANTIDAD: TFloatField;
    qryFactReimpDetDevolPRECIO: TFloatField;
    qryFactReimpDetDevolPORC_DESC_DET: TFloatField;
    qryFactReimpDetDevolITBI_DET: TFloatField;
    qryFactReimpDetDevolVALOR_SERVICIO_DET: TFloatField;
    qryFactReimpDetDevolVALOR_TOTAL_DET: TFloatField;
    qryFactReimpDetDevolNUMERO_FACTURA: TIntegerField;
    qryFactReimpDetDevolSTATUS_DET: TIBStringField;
    qryFactReimpDetDevolSERIE_NCF_ASIGNADO: TIntegerField;
    qryFactReimpDetDevolNUMERO_NCF: TIBStringField;
    qryFactReimpDetDevolMONTO_DESCUENTO: TFloatField;
    qryFactReimpDetDevolDESCTIPOUNIDAD: TIBStringField;
    qryVentaFacturaDetPORC_DESC_ITEM: TFloatField;
    qryVentaFacturaDetMONTO_DESC_ITEM: TFloatField;
    qryFactServFReimpDetDESC_TIPO_NCF: TIBStringField;
    qryFactServFReimpDetSERIE: TIntegerField;
    qryFactServFReimpDetCODIGO_PROD: TIBStringField;
    qryFactServFReimpDetDESCRIPCION: TIBStringField;
    qryFactServFReimpDetCANTIDAD: TFloatField;
    qryFactServFReimpDetPRECIO: TFloatField;
    qryFactServFReimpDetPORC_DESC_DET: TFloatField;
    qryFactServFReimpDetITBI_DET: TFloatField;
    qryFactServFReimpDetVALOR_SERVICIO_DET: TFloatField;
    qryFactServFReimpDetVALOR_TOTAL_DET: TFloatField;
    qryFactServFReimpDetNUMERO_FACTURA: TIntegerField;
    qryFactServFReimpDetPORC_DESC_ITEM: TFloatField;
    qryFactServFReimpDetMONTO_DESC_ITEM: TFloatField;
    qryFactServFReimpDetSTATUS_DET: TIBStringField;
    qryFactServFReimpDetSERIE_NCF_ASIGNADO: TIntegerField;
    qryFactServFReimpDetNUMERO_NCF: TIBStringField;
    qryFactServFReimpDetMONTO_DESCUENTO: TFloatField;
    qryRepCotizaDetNewPORC_DESC_ITEM: TFloatField;
    qryRepCotizaDetNewMONTO_DESC_ITEM: TFloatField;
    qryVentaFacturaMONTO_RECARGO: TFloatField;
    ibQryViewNCF_0: TIBQuery;
    qryVentaFacturaTIPONCFIFISCAL: TIntegerField;
    ibQryViewNCFTIPO_NCF_IFISCAL: TIntegerField;
    qryGetNcfAsignado: TIBQuery;
    qryGetNcfAsignadoNUMERO_FACT: TIntegerField;
    qryGetNcfAsignadoNUM_DOC: TIntegerField;
    qryGetNcfAsignadoSERIE_NCF_ASIGNADO: TIntegerField;
    qryGetNcfAsignadoNUMERO_TRN_ORIGEN: TIntegerField;
    qryGetNcfAsignadoNUMERO_NCF_AFECTADO: TIBStringField;
    qryGetNcfAsignadoTIPO_NCF: TIBStringField;
    qryGeNcfAsignado_1: TIBQuery;
    qryGetNcfAsignado_0: TIBQuery;
    qryDatosTrncxcSERIE: TIntegerField;
    qryDatosTrncxcNOMBRE_COMPLETO: TIBStringField;
    qryDatosTrncxcNUMERO_NCF: TIBStringField;
    qryDatosTrncxcTIPO_NCF: TIBStringField;
    qryDatosTrncxcNOMBRE_CTE: TIBStringField;
    qryDatosTrncxcCEDULA: TIBStringField;
    qryDatosTrncxcRNC_NUMERO: TIBStringField;
    qryDatosTrncxcDIRECCION_CONT: TIBStringField;
    qryDatosTrncxcNOMBRE_FACTURAR: TIBStringField;
    qryDatosTrncxcTELEF_CONTACTO: TIBStringField;
    qryDatosTrncxcNUM_DOC: TIntegerField;
    qryDatosTrncxcNUMERO_FACT: TSmallintField;
    qryDatosTrncxcSERIE_NCF_ASIGNADO: TSmallintField;
    qryDatosTrncxcVALOR_DOCUMENTO: TFloatField;
    qryDatosTrncxcCODIGO_CLIENTE: TSmallintField;
    qryDatosTrncxcNUM_NCF_AFECTADO: TIBStringField;
    qryDatosTrncxcTIPO_TRANF: TSmallintField;
    qryDatosTrncxcTIPO_DOC: TIntegerField;
    qryDatosTrncxcFECHA: TDateTimeField;
    qryDatosTrncxcCONCEPTO: TIBStringField;
    qryDatosTrncxcMONEDA: TIBStringField;
    ibQryViewNCFTIPO_NCFNCR: TIntegerField;
    qryCheckNCFSec: TIBQuery;
    qryCheckNCFSecTIPO_CF: TIBStringField;
    qryCheckNCFSecNCF_MAX: TIntegerField;
    qryCheckNCFSecNCF: TFloatField;
    qryCheckNCFSecCANT_MIN_AVISO1: TSmallintField;
    qryCheckNCFSecCANT_MIN_AVISO2: TSmallintField;
    qryCheckNCFSecDESCRIPCION: TIBStringField;
    qryCheckNCFSecAVISO: TIBStringField;
    qryCheckNCFSecSTATUS: TSmallintField;
    tblDgii_SerieNCFCANT_MIN_AVISO1: TSmallintField;
    tblDgii_SerieNCFCANT_MIN_AVISO2: TSmallintField;
    qryDatosParaCtrlNIF: TIBQuery;
    qryDatosParaCtrlNIFNUMERO_TRN: TIntegerField;
    qryDatosParaCtrlNIFNIF: TIBStringField;
    qryDatosParaCtrlNIFNUMERO_NCF: TIBStringField;
    qryDatosParaCtrlNIFFECHA: TDateTimeField;
    qryDatosParaCtrlNIFSTATUS: TIBStringField;
    qryDatosParaCtrlNIFCODIGO_CTE: TIntegerField;
    qryDatosParaCtrlNIFSERIE_NCF_ASIGNADO: TIntegerField;
    qryDatosParaCtrlNIFMONTO_BRUTO: TFloatField;
    qryDatosParaCtrlNIFOBSERVACION: TIBStringField;
    qryDatosParaCtrlNIFNIF_IMPRESO: TSmallintField;
    ibtpProcInsVtaCancelar: TIBStoredProc;
    qryFactReimpDetDevolMONTO_DESC_ITEM: TFloatField;
    qryRepItbisITBI_EXONERADO: TFloatField;
    qryRepItbisVALOR_BASE: TFloatField;
    qryRepItbisMONTO_DESCUENTO: TFloatField;
    qryRepItbisMONTO_RECARGO: TFloatField;
    qryGetNcfAsignadoTIPONCFIFISCAL: TIntegerField;
    ibQryviewNCFOld: TIBQuery;
    IBStringField9: TIBStringField;
    IBStringField10: TIBStringField;
    IBStringField11: TIBStringField;
    IBStringField12: TIBStringField;
    IBStringField13: TIBStringField;
    IBStringField14: TIBStringField;
    IBStringField15: TIBStringField;
    FloatField4: TFloatField;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    qryVentaFacturaMONTO_EXONERADO_ITBIS: TFloatField;
    qryRepItbisMONTOIBISRECARGO: TFloatField;
    qryRepItbisDESC_NCF: TIBStringField;
    qryRepItbisMONTOBASEEXENTO: TFloatField;
    qryRepItbisMONTOGRAVADO: TFloatField;
    qryRepItbisTASAITBIS: TFloatField;
    qryRepItbisITBIS_8PORCIENTO: TFloatField;
    qryRepItbisITBIS_11PORCIENTO: TFloatField;
    qryRepItbisITBIS_13PORCIENTO: TFloatField;
    qryRepItbisITBIS_16PORCIENTO: TFloatField;
    qryRepItbisITBIS_18PORCIENTO: TFloatField;
    qryRepItbisOTROPORCIENTOITBIS: TFloatField;
    ibstpInsertDevolMaster: TIBStoredProc;
    ibQryViewNCFGastos: TIBQuery;
    ibQryViewNCFGastosID: TIBStringField;
    ibQryViewNCFGastosSERIE: TIBStringField;
    ibQryViewNCFGastosDIV_NEGOCIO: TIBStringField;
    ibQryViewNCFGastosPECF: TIBStringField;
    ibQryViewNCFGastosAICF: TIBStringField;
    ibQryViewNCFGastosTIPO_CF: TIBStringField;
    ibQryViewNCFGastosNCF: TFloatField;
    ibQryViewNCFGastosDESCRIPCION: TIBStringField;
    ibQryViewNCFGastosTIPO_NCF_IFISCAL: TIntegerField;
    ibQryViewNCFGastosTIPO_NCFNCR: TIntegerField;
    dsibQryViewNCFGastos: TDataSource;
    qryVentaFacturaDetCANT_VIAJES: TFloatField;
    qryRepCotizaDetNewCANT_VIAJES: TFloatField;
    qryVentaFacturaDetDESCUNIDADMEDIDA: TIBStringField;
    qryVentaFacturaPROPINA: TFloatField;
    qryVentaFacturaPROPINALEGAL: TFloatField;
    qryVentaFacturaPORCPROPINALEGAL: TFloatField;
    qryFactReimpDetPROPINA: TFloatField;
    qryFactReimpDetPROPINALEGAL: TFloatField;
    qryFactReimpDetDevolPROPINA: TFloatField;
    qryFactReimpDetDevolPROPINALEGAL: TFloatField;
    qryFactReimpDetLTIPO_UNIDAD: TIBStringField;
    qryVentaFacturaDetLTIPO_UNIDAD: TIBStringField;
    qryVentaFacturaDetCANTXUNIDAD: TIntegerField;
    qrySumCantXTUnidad: TIBQuery;
    qrySumCantXTUnidadBULTOS: TIBStringField;
    qrySumCantXTUnidadCANT: TFloatField;
    qryDatosDevolucionNCR_0: TIBQuery;
    tblFiscalStatusTicket: TIBDataSet;
    tblFiscalStatusTicketNUMERO_TRN: TIntegerField;
    tblFiscalStatusTicketACTIVO: TSmallintField;
    tblFiscalStatusTicketFECHA: TDateTimeField;
    tblFiscalStatusTicketNIF: TIBStringField;
    tblFiscalStatusTicketIMPRIMIENDO: TSmallintField;
    ibQryViewNCFFECHA_VENCE: TDateTimeField;
    ibQryViewNCFGastosDESCRIPCION_2018: TIBStringField;
    ibQryViewNCFGastosFECHA_VENCE: TDateTimeField;
    tblDgii_SerieNCFFECHA_VENCE: TDateTimeField;
    tblTipoCFDESCRIPCION_2018: TIBStringField;
    qryVentaFacturaFECHAVENCENCF: TDateTimeField;
    qryRepCotizaDetNewEXISTENCIA: TFloatField;
    qryRepCotizaNewCODZON: TIntegerField;
    qryRepCotizaNewSTACOT: TSmallintField;
    qryRepCotizaNewIMPCOT: TSmallintField;
    qryRepCotizaNewMARCOT: TIBStringField;
    qryRepCotizaNewMODCOT: TIBStringField;
    qryRepCotizaNewCHACOT: TIBStringField;
    qryRepCotizaNewKILCOT: TIBStringField;
    qryRepCotizaNewPLACOT: TIBStringField;
    qryRepCotizaNewANOCOT: TIBStringField;
    qryRepCotizaNewCOLCOT: TIBStringField;
    qryRepCotizaNewCCMOTORCOT: TIBStringField;
    qryVentaFacturaDetREFERENCIA: TIBStringField;
    qryRepCotizaDetNewREFERENCIA: TIBStringField;
    qryRepItbisbase: TIBQuery;
    IBStringField16: TIBStringField;
    IntegerField5: TIntegerField;
    FloatField5: TFloatField;
    DateTimeField2: TDateTimeField;
    IBStringField17: TIBStringField;
    IntegerField6: TIntegerField;
    IBStringField18: TIBStringField;
    IBStringField19: TIBStringField;
    FloatField6: TFloatField;
    IBStringField20: TIBStringField;
    IBStringField21: TIBStringField;
    IBStringField22: TIBStringField;
    IBStringField23: TIBStringField;
    FloatField7: TFloatField;
    SmallintField2: TSmallintField;
    FloatField8: TFloatField;
    FloatField9: TFloatField;
    FloatField10: TFloatField;
    FloatField11: TFloatField;
    qryRepItbisSum: TIBQuery;
    qryRepItbisSumTIPODOC: TIBStringField;
    qryRepItbisSumCODIGO_CTE: TIntegerField;
    qryRepItbisSumNUMERODOC: TIBStringField;
    qryRepItbisSumNOMBRE_CTE: TIBStringField;
    qryRepItbisSumSTATUS: TIBStringField;
    qryRepItbisSumFORMA_PAGO: TSmallintField;
    qryRepItbisSumFECHA: TDateTimeField;
    qryRepItbisSumMONEDA: TIBStringField;
    qryRepItbisSumDESC_NCF: TIBStringField;
    qryRepItbisSumNUMERO_NCF: TIBStringField;
    qryRepItbisSumNUMERO: TIntegerField;
    qryRepItbisSumRNC_NUMERO: TIBStringField;
    qryRepItbisSumCEDULA: TIBStringField;
    qryRepItbisSumVALOR_TASA: TFloatField;
    qryRepItbisSumVALOR_BASE: TFloatField;
    qryRepItbisSumMONTO_DESCUENTO: TFloatField;
    qryRepItbisSumITBI_EXONERADO: TFloatField;
    qryRepItbisSumITBI_DET: TFloatField;
    qryRepItbisSumVALOR_TOTAL_DET: TFloatField;
    qryRepItbisSumMONTO_RECARGO: TFloatField;
    qryRepNCFSum: TIBQuery;
    qryVentaFacturaDetDESCRIPCIONADICIONAL: TMemoField;
    qryRepCotizaDetNewDESCRIPCIONADIC: TMemoField;
    qryVentaFacturaDet_food_0: TIBQuery;
    qryVentaFacturaDet_Base: TIBQuery;
    qryVentaFacturaDESC_SECTOR: TIBStringField;
    qryVentaFacturaDESC_CIUDAD: TIBStringField;
    qryVentaFacturaDetNUM_IDENT: TIBStringField;
    qryVentaFacturaDetFICHA_VEH: TIntegerField;
    qryClientesVendedor: TIBQuery;
    qryClientesVendedorNUMERO: TIntegerField;
    qryClientesVendedorCODVENDEDORCTE: TIntegerField;
    qryClientesVendedorCODIGO_CTE: TIntegerField;
    qryClientesVendedorCODVENDEDORDC: TIntegerField;
    qryVentaFacturaConsignaTIPO_NCF: TIBStringField;
    qryVentaFacturaTIPO_NCF: TIBStringField;
    qryVentaFacturaDetNUM_CONDUCE_CTE: TIBStringField;
    qryDatosVtaARS: TIBQuery;
    qryDatosVtaARSNOMBRE: TIBStringField;
    qryDatosVtaARSNUMERO: TIntegerField;
    qryDatosVtaARSNUMERO_TRN: TIntegerField;
    qryDatosVtaARSIDARS: TIntegerField;
    qryDatosVtaARSNOMBRE_MEDICO: TIBStringField;
    qryDatosVtaARSNUM_AUTORIZACION: TIBStringField;
    qryDatosVtaARSCONTACTO: TIBStringField;
    qryDatosVtaARSDIRECCION: TMemoField;
    qryDatosVtaARSESPECIALIDAD: TIBStringField;
    qryDatosVtaARSDIAGNOSTICO: TMemoField;
    qryDatosVtaARSMONTO_COBERTURA: TFloatField;
    qryDatosVtaARSEXEQUATUR: TIBStringField;
    qryDatosVtaARSSTATUS: TIBStringField;
    qryDatosVtaARSFECHA_IN: TDateTimeField;
    qryDatosVtaARSFECHA_UPDATE: TDateTimeField;
    qryDatosVtaARSIN_POR: TIBStringField;
    qryDatosVtaARSUPDATE_POR: TIBStringField;
    qryDatosVtaARSAFILIADO: TIBStringField;
    qryDatosVtaARSFECHA: TDateTimeField;
    qryDatosVtaARSCEDULA: TIBStringField;
    qryDatosVtaARSNOMBRE_FACTURAR: TIBStringField;
    qryDatosVtaARSTELEF_CONTACTO: TIBStringField;
    qryDatosVtaARSMONTOASEGURADO: TFloatField;
    qryDatosVtaARSNOMBRE_DEPENDIENTE: TIBStringField;
    qryVentaFacturaDetCODIGO_VENDEDOR: TIntegerField;
    qryRepItbisTIPO_INV: TSmallintField;
    qryRepItbisDESC_TIPOINVENTARIO: TIBStringField;
    qryVentaFacturaFECHAINICIAPOLIZA: TDateTimeField;
    tblServProgIgualaCODIGO_PRODUCTO: TIntegerField;
    qryServProgIgualaCODIGO_PRODUCTO: TIntegerField;
    tblFactRecurrentes: TIBDataSet;
    tblFactRecurrentesSERIE: TIntegerField;
    tblFactRecurrentesFECHA_GENERADA: TDateTimeField;
    tblFactRecurrentesCODIGO_CTE: TIntegerField;
    tblFactRecurrentesNUMERO_FACT: TIntegerField;
    tblFactRecurrentesNUMERO_TRN: TIntegerField;
    tblFactRecurrentesRUTA: TIBStringField;
    tblFactRecurrentesSTATUS: TIBStringField;
    qryFechaUltMaxFRec: TIBQuery;
    qryFechaUltMaxFRecFECHAMAX: TDateTimeField;
    qryCantProgServ: TIBQuery;
    qryCantProgServCANTSERVVIGENTES: TIntegerField;
    qryCantProgServCANTSERVINACTIVOS: TIntegerField;
    qryCantProgServCANTSERVCANCELADOS: TIntegerField;
    qryCantProgServTOTAL: TIntegerField;
    tblFactRecurrentesNUMERO_PROG: TIntegerField;
    tblQryHistoricoSecNCFSTATUS: TSmallintField;
    qryVtaConDeliveryTrn: TIBQuery;
    qryVtaConDeliveryTrnCODIGO: TIntegerField;
    qryVtaConDeliveryTrnNUMERO_TRN: TIntegerField;
    qryVtaConDeliveryTrnNOMBRE: TIBStringField;
    qryVtaConDeliveryTrnTELEFONO: TIBStringField;
    qryVtaConDeliveryTrnDIRECCION: TIBStringField;
    qryVtaConDeliveryTrnFECHA_IN: TDateTimeField;
    qryVtaConDeliveryTrnINSERT_POR: TIBStringField;
    IBDataSetFacturasPORC_ATRASOCXC: TFloatField;
    tblProgServIgualaSTATUSCONTRACTO: TIBStringField;
    qryRepCotizaNewNOMBREVENDEDOR: TIBStringField;
    qryVentaFacturaIDNUMERODVEH: TIntegerField;
    tblPrepagoCte: TIBDataSet;
    tblPrepagoCteCODIGO_CTE: TIntegerField;
    tblPrepagoCteFECHA: TDateTimeField;
    tblPrepagoCteMONTO: TFloatField;
    tblPrepagoCteNUMERO_TRN: TIntegerField;
    tblPrepagoCteCODIGO_PROD: TIntegerField;
    tblPrepagoCteNOTA: TMemoField;
    tblPrepagoCteSTATUS: TIBStringField;
    qryAbonoPrepago: TIBQuery;
    tblPrepagoCteNUMERO: TIntegerField;
    qryAbonoPrepagoNUMERO: TIntegerField;
    qryAbonoPrepagoCODIGO_CTE: TIntegerField;
    qryAbonoPrepagoFECHA: TDateTimeField;
    qryAbonoPrepagoMONTO: TFloatField;
    qryAbonoPrepagoNUMERO_TRN: TIntegerField;
    qryAbonoPrepagoCODIGO_PROD: TIntegerField;
    qryAbonoPrepagoNOTA: TMemoField;
    qryAbonoPrepagoSTATUS: TIBStringField;
    qryAbonoPrepagoNOMBRECLIENTE: TIBStringField;
    qryAbonoPrepagoRNC_NUMERO: TIBStringField;
    qryAbonoPrepagoDESCRIPCIONPROD: TIBStringField;
    qryAbonoPrepagoMOVIL1: TIBStringField;
    tblPrepagoCteCODIGO_USR_CAJA: TIntegerField;
    tblPrepagoCteFPAGO: TSmallintField;
    qryAbonoPrepagoCODIGO_USR_CAJA: TIntegerField;
    qryAbonoPrepagoFPAGO: TSmallintField;
    qryAbonoPrepagoFORMADEPAGO: TIBStringField;
    qryAbonoPrepagoNOMBREUSUARIO: TIBStringField;
    qryVentaFacturaMONTOPREPAGADO: TFloatField;
    tblPrepagoCteNUM_TRN_VTA: TIntegerField;
    tblUpdateVenta: TIBDataSet;
    tblUpdateVentaNUMERO: TIntegerField;
    tblUpdateVentaFECHA: TDateTimeField;
    tblUpdateVentaCIA_KEY: TIntegerField;
    tblUpdateVentaCODIGO_CTE: TIntegerField;
    tblUpdateVentaCODIGO_VENDEDOR: TIntegerField;
    tblUpdateVentaFORMA_PAGO: TSmallintField;
    tblUpdateVentaOBSERVACION: TIBStringField;
    tblUpdateVentaMONEDA: TIBStringField;
    tblUpdateVentaVALOR_TOTAL_DET: TFloatField;
    tblUpdateVentaSTATUS: TIBStringField;
    tblUpdateVentaFECHA_IN: TDateTimeField;
    tblUpdateVentaIN_POR: TIBStringField;
    tblUpdateVentaFECHA_MOD: TDateTimeField;
    tblUpdateVentaMOD_POR: TIBStringField;
    tblUpdateVentaNUMERO_FACTURA: TIntegerField;
    tblUpdateVentaNUMERO_DOC_PAGO: TIBStringField;
    tblUpdateVentaSERIE_NCF_ASIGNADO: TIntegerField;
    tblUpdateVentaMONTO_BRUTO: TFloatField;
    tblUpdateVentaPORC_DESCUENTO: TIntegerField;
    tblUpdateVentaMONTO_DESCUENTO: TFloatField;
    tblUpdateVentaMONTO_INICIAL: TFloatField;
    tblUpdateVentaNOMBRE_CLIENTE_GENERAL: TIBStringField;
    tblUpdateVentaMONTO_PAGADO: TFloatField;
    tblUpdateVentaMONTO_CAMBIO: TFloatField;
    tblUpdateVentaMONTO_TOTAL_ITBIS: TFloatField;
    qryDetPagos: TIBQuery;
    qryVentaFacturaDetLEVEL_PRECIO_VENTA: TSmallintField;
    ibQryViewNCFIDSEC_2018: TIBStringField;
    ibQryViewNCFDESCRIPCION_2018: TIBStringField;
    ibQryViewNCFGastosIDSEC_2018: TIBStringField;
    procedure ibQryViewNCFFilterRecord(DataSet: TDataSet;
      var Accept: Boolean);
    procedure tblDgii_SerieNCFAfterScroll(DataSet: TDataSet);
    procedure qryFactReimpMasterAfterScroll(DataSet: TDataSet);
    procedure qryFactServFReimpMasterAfterScroll(DataSet: TDataSet);
    procedure tblTemplateMasterAfterScroll(DataSet: TDataSet);
    procedure qryVentaFacturaAfterScroll(DataSet: TDataSet);
    procedure tblTemplateDetFilterRecord(DataSet: TDataSet;
      var Accept: Boolean);
    procedure qryRepCotizaNewAfterScroll(DataSet: TDataSet);
    procedure qryVentaFacturaConsignaAfterScroll(DataSet: TDataSet);
    procedure qryVentaFacturaCalcFields(DataSet: TDataSet);
    procedure stpProcDevolucionPostError(DataSet: TDataSet;
      E: EDatabaseError; var Action: TDataAction);
    procedure qryVentaFacturaFilterRecord(DataSet: TDataSet;
      var Accept: Boolean);
    procedure qryRepItbisFilterRecord(DataSet: TDataSet;
      var Accept: Boolean);
    procedure qryCotizacionConduceAfterScroll(DataSet: TDataSet);
    procedure DataModuleCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
    strFilterSeccion : String;
    formaPago : Smallint;
    rtipo : smallint;

  end;

var
  dmFactura: TdmFactura;

implementation

uses UGlobal, UDatModConectar;

{$R *.dfm}

procedure TdmFactura.ibQryViewNCFFilterRecord(DataSet: TDataSet;
  var Accept: Boolean);
begin
  Accept:=  (DataSet['tipo_cf'] = '01' ) OR
            (DataSet['tipo_cf'] = '02' ) OR
            (DataSet['tipo_cf'] = '14' );
end;

procedure TdmFactura.tblDgii_SerieNCFAfterScroll(DataSet: TDataSet);
begin
  QryHistSecNCF.close;
  QryHistSecNCF.params[0].Value:= tblDgii_SerieNCFTIPO_CF.Value;
  QryHistSecNCF.Open;
end;

procedure TdmFactura.qryFactReimpMasterAfterScroll(DataSet: TDataSet);
begin
  qryFactReimpDet.Close;
  qryFactReimpDet.Params[0].Value:=qryFactReimpMasterNUMERO.Value;
  qryFactReimpDet.Open;
end;

procedure TdmFactura.qryFactServFReimpMasterAfterScroll(DataSet: TDataSet);
begin
  qryFactServFReimpDet.Close;
  qryFactServFReimpDet.Params[0].Value:= dmFactura.qryFactServFReimpMasterNumero.Value;
  qryFactServFReimpDet.Open;
end;

procedure TdmFactura.tblTemplateMasterAfterScroll(DataSet: TDataSet);
begin
  if tblTemplateDet.state in [dsInactive, dsBrowse] then
  begin
    tblTemplateDet.Close;
    tblTemplateDet.Params[0].Value:=tblTemplateMasterNUMEROID.Value;
    tblTemplateDet.Open;
  end;
end;

procedure TdmFactura.qryVentaFacturaAfterScroll(DataSet: TDataSet);
begin
  qryClientesVendedor.Close;
  qryClientesVendedor.Open;
  qryVentaFacturaDet.Close;
  qryVentaFacturaDet.Params[0].Value :=qryVentaFacturaNUMERO.Value;
  qryVentaFacturaDet.Open;//qryVentaFacturaDet.sql.text
  //qryVentaFacturaDetLEVEL_PRECIO_VENTA.value
  //Chequear aqui error
  qryPorcApplicadoenFactServ.Close;
  qryPorcApplicadoenFactServ.Params[0].Value:= qryVentaFacturaNUMERO.Value;
  qryPorcApplicadoenFactServ.Open;
  dmFactura.qryFactTieneDevolucion.Close;
  dmFactura.qryFactTieneDevolucion.Params[0].Value:= qryVentaFacturaNUMERO.Value;
  dmFactura.qryFactTieneDevolucion.Params[1].Value:= qryVentaFacturaSERIE_NCF_ASIGNADO.Value;
  dmFactura.qryFactTieneDevolucion.Open;

  qryGetNcfAsignado.Close;
  if qryVentaFacturaForma_pago.Value  = 1 then //contado
  qryGetNcfAsignado.SQL.Text:=qryGeNcfAsignado_1.SQL.Text
  else
  qryGetNcfAsignado.SQL.Text:=qryGetNcfAsignado_0.SQL.Text;
    
  qryGetNcfAsignado.Params[0].Value:= qryVentaFacturaNUMERO.Value;
  qryGetNcfAsignado.Open;

  qrySumCantXTUnidad.Close;
  qrySumCantXTUnidad.Params[0].Value :=qryVentaFacturaNUMERO.Value;
  qrySumCantXTUnidad.Open;

  qryDetPagos.close;
  qryDetPagos.params[0].Value:=qryVentaFacturaNUMERO.Value;
  qryDetPagos.Open;
  //Buscar
  {dmfactura.stpPorcOtrosCargosFactServ.Params[0].Value := TotalesPorcGAdmin.Value;
  dmfactura.stpPorcOtrosCargosFactServ.Params[1].Value := TotalesPorcItbisGAdmin.Value;
  dmfactura.stpPorcOtrosCargosFactServ.Params[2].Value := TotalesPorcTrans.Value;
  dmfactura.stpPorcOtrosCargosFactServ.Params[3].Value := TotalesPorcDirTec.Value;
  dmfactura.stpPorcOtrosCargosFactServ.Params[4].Value := TotalesPorcItbisDirTec.Value;
  dmfactura.stpPorcOtrosCargosFactServ.Params[5].Value := TotalesPorcImprevisto.Value;
  dmfactura.stpPorcOtrosCargosFactServ.Params[6].Value := TotalesPorcItbisImprevisto.Value;

  dmfactura.stpPorcOtrosCargosFactServ.Close;
  dmfactura.stpPorcOtrosCargosFactServ.Params[7].Value := qryVentaFacturaNUMERO.Value;
  dmfactura.stpPorcOtrosCargosFactServ.ExecProc;}
end;

procedure TdmFactura.tblTemplateDetFilterRecord(DataSet: TDataSet;
  var Accept: Boolean);
begin
  if (strFilterSeccion <> '') then
  Accept:=DataSet['SECCION'] = strFilterSeccion
  else Dataset.Filtered:=False;
end;

procedure TdmFactura.qryRepCotizaNewAfterScroll(DataSet: TDataSet);
begin
  qryRepCotizaDetNew.Close;
  qryRepCotizaDetNew.Params[0].Value:=qryRepCotizaNewNUMERO.Value;
  qryRepCotizaDetNew.Open;
end;

procedure TdmFactura.qryVentaFacturaConsignaAfterScroll(DataSet: TDataSet);
begin
  qryVentaFacturaDetConsigna.Close;
  qryVentaFacturaDetConsigna.Params[0].Value :=qryVentaFacturaConsignaNUMERO.Value;
  qryVentaFacturaDetConsigna.Open;

  qryPorcApplicadoenFactServ.Close;
  qryPorcApplicadoenFactServ.Params[0].Value:= qryVentaFacturaConsignaNUMERO.Value;
  qryPorcApplicadoenFactServ.Open;

end;

procedure TdmFactura.qryVentaFacturaCalcFields(DataSet: TDataSet);
begin
  qryVentaFacturaFechaVence.Value:= qryVentaFacturaFECHA.Value +
  qryVentaFacturaCANT_DIAS_CREDITO.Value;
end;

procedure TdmFactura.stpProcDevolucionPostError(DataSet: TDataSet;
  E: EDatabaseError; var Action: TDataAction);
begin
  MessageDlg('Error en procedure',mtInformation, [mbOK], 0);
end;

procedure TdmFactura.qryVentaFacturaFilterRecord(DataSet: TDataSet;
  var Accept: Boolean);
begin
  Accept:= DataSet['FORMA_PAGO'] = dmFactura.formaPago;
end;

procedure TdmFactura.qryRepItbisFilterRecord(DataSet: TDataSet;
  var Accept: Boolean);
begin
  if (rtipo = 1) or (rtipo = 3)  or (rtipo = 4) then
  Accept := (Dataset['tipodoc'] = 'FACTURA') OR (Dataset['tipodoc'] = 'CONTADO')
  else
  Accept := (Dataset['tipodoc'] = 'DEVOLUCION');
  //CONTADO DEVOLUCION FACTURA
end;

procedure TdmFactura.qryCotizacionConduceAfterScroll(DataSet: TDataSet);
begin
  qryCotizacionConduceDet.Close;
  qryCotizacionConduceDet.Params[0].Value := qryCotizacionConduceNUMERO.Value;
  qryCotizacionConduceDet.Open;

  //qryPorcApplicadoenFactServ.Close;
  //qryPorcApplicadoenFactServ.Params[0].Value:= qryCotizacionConduceNUMERO.Value;
  //qryPorcApplicadoenFactServ.Open;
  //dmFactura.qryFactTieneDevolucion.Close;
  //dmFactura.qryFactTieneDevolucion.Params[0].Value:= qryCotizacionConduceNUMERO.Value;
  //dmFactura.qryFactTieneDevolucion.Open;
end;

procedure TdmFactura.DataModuleCreate(Sender: TObject);
begin
  if (GlBLimao = 1) then
  begin
    dmFactura.qryVentaFacturaDet.SQL.Text:= dmFactura.qryVentaFacturaDet_food_0.SQL.Text;
  end else
  begin
    dmFactura.qryVentaFacturaDet.SQL.Text:= dmFactura.qryVentaFacturaDet_Base.SQL.Text;
  end;
end;

end.
