SET AUTODDL ON;

--DROP VIEW VIEW_VENTAS_MAST;

/**************** DROPPING COMPLETE ***************/

CREATE or alter VIEW VIEW_VENTAS_MAST (NUMERO, FECHA, CODIGO_CTE, CODIGO_VENDEDOR, FORMA_PAGO, OBSERVACION, MONEDA, VALOR_TOTAL_DET, STATUS, NUMERO_FACTURA, NUMERO_DOC_PAGO, SERIE_NCF_ASIGNADO, MONTO_BRUTO, PORC_DESCUENTO, MONTO_DESCUENTO, MONTO_PAGADO, MONTO_CAMBIO, MONTO_INICIAL, NOMBRE_CLIENTE_GENERAL, NOMBRE_COMPLETO, NUMERO_NCF, TIPO_NCF, NOMBRE_CTE, CEDULA, RNC, DIRECCION_CONT, NOMBRE_FACTURAR, TELEF_CONTACTO, DESC_TIPOPAGO, ORIGEN, DESC_TIPONCF, NOMBRE_ABREV, COMENTARIO)
AS     
SELECT 
  VENTAS_MAST.NUMERO,
  VENTAS_MAST.FECHA,
  VENTAS_MAST.CODIGO_CTE,
  VENTAS_MAST.CODIGO_VENDEDOR,
  VENTAS_MAST.FORMA_PAGO,
  VENTAS_MAST.OBSERVACION,
  VENTAS_MAST.MONEDA,
  VENTAS_MAST.VALOR_TOTAL_DET,
  VENTAS_MAST.STATUS,
  VENTAS_MAST.NUMERO_FACTURA,
  VENTAS_MAST.NUMERO_DOC_PAGO,
  VENTAS_MAST.SERIE_NCF_ASIGNADO,
  VENTAS_MAST.MONTO_BRUTO,
  VENTAS_MAST.PORC_DESCUENTO,
  VENTAS_MAST.MONTO_DESCUENTO,
  VENTAS_MAST.MONTO_PAGADO,
  VENTAS_MAST.MONTO_CAMBIO,
  VENTAS_MAST.MONTO_INICIAL,
  VENTAS_MAST.NOMBRE_CLIENTE_GENERAL,
  NCF_ASIGNADOS.NOMBRE_COMPLETO,
  NCF_ASIGNADOS.NUMERO_NCF,
  NCF_ASIGNADOS.TIPO_NCF,
  CLIENTES.NOMBRE_CTE,
  CLIENTES.CEDULA,
  CLIENTES.RNC_NUMERO,
  CLIENTES.DIRECCION_CONT,
  CLIENTES.NOMBRE_FACTURAR,
  CLIENTES.TELEF_CONTACTO,
  TIPO_PAGO.DESCRIPCION AS DESC_TIPOPAGO,
  TIPO_PAGO.ORIGEN,
  TIPO_CF.DESCRIPCION as Desc_tiponcf,
  Clientes.NOMBRE_ABREV,
  VENTAS_MAST.COMENTARIO
FROM
  VENTAS_MAST
  LEFT OUTER JOIN NCF_ASIGNADOS ON (VENTAS_MAST.SERIE_NCF_ASIGNADO = NCF_ASIGNADOS.SERIE)
  LEFT OUTER JOIN CLIENTES ON (VENTAS_MAST.CODIGO_CTE = CLIENTES.CODIGO_CTE)
  INNER JOIN TIPO_PAGO ON (VENTAS_MAST.FORMA_PAGO = TIPO_PAGO.CODIGO)
  LEFT OUTER JOIN TIPO_CF ON (NCF_ASIGNADOS.TIPO_NCF = TIPO_CF.TIPO_CF)
;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEW_VENTAS_MAST TO  DIVISON WITH GRANT OPTION;
