SET TERM ^ ;
ALTER PROCEDURE PROC_INSFACTURAS_PEND (
    CODIGO_PROV integer,
    TIPO integer,
    MONEDA char(1),
    NUMERO_FACT integer,
    MONTO_PENDIENTE numeric(15,2),
    FECHA timestamp  )
AS
BEGIN
  INSERT INTO 
  FACTURAS_cxp_PENDIENTES(CODIGO_PROV, TIPO,MONEDA,NUMERO_FACT,MONTO_PENDIENTE,STATUS,fecha)
  Values(:CODIGO_PROV, :TIPO,:MONEDA,:NUMERO_FACT,:MONTO_PENDIENTE,"A",:fecha); 
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE PROC_INSFACTURAS_PEND TO  DIVISON;

