SET AUTODDL ON;

--DROP VIEW VIEW_COTIZACION_MASTER;

/**************** DROPPING COMPLETE ***************/

CREATE OR ALTER VIEW VIEW_COTIZACION_MASTER (NUMERO, FECHA, CIA_KEY, FECHA_VENCE, CODIGO_CTE, CODIGO_VENDEDOR, OBSERVACION, MONEDA, VALOR_TOTAL, STATUS, FECHA_IN, IN_POR, FECHA_MOD, MOD_POR, NUMERO_FACTURA, NUMERO_DOC_PAGO, SERIE_NCF_ASIGNADO, MONTO_BRUTO, PORC_DESCUENTO, MONTO_DESCUENTO, MONTO_INICIAL, NOMBRE_CLIENTE_GENERAL, MONTO_PAGADO, MONTO_CAMBIO, MONTO_TOTAL_ITBIS, MONTODESCGASTOSADMIN, MONTODESCITBISGASTOSADMIN, MONTODESCTRANSP, MONTODESCDIRTECNICA, MONTODESCITBISDIRTECNICA, MONTODESCIMPREVISTO, MONTODESCITBISIMPREVISTO, TIPO_FACTURA, APLICA_TIPODESC, COMENTARIO)
AS  
SELECT 
  COTIZACION_MAST.NUMERO,
  COTIZACION_MAST.FECHA,
  COTIZACION_MAST.CIA_KEY,
  COTIZACION_MAST.FECHA_VENCE,
  COTIZACION_MAST.CODIGO_CTE,
  COTIZACION_MAST.CODIGO_VENDEDOR,
  COTIZACION_MAST.OBSERVACION,
  COTIZACION_MAST.MONEDA,
  COTIZACION_MAST.VALOR_TOTAL,
  COTIZACION_MAST.STATUS,
  COTIZACION_MAST.FECHA_IN,
  COTIZACION_MAST.IN_POR,
  COTIZACION_MAST.FECHA_MOD,
  COTIZACION_MAST.MOD_POR,
  COTIZACION_MAST.NUMERO_FACTURA,
  COTIZACION_MAST.NUMERO_DOC_PAGO,
  COTIZACION_MAST.SERIE_NCF_ASIGNADO,
  COTIZACION_MAST.MONTO_BRUTO,
  COTIZACION_MAST.PORC_DESCUENTO,
  COTIZACION_MAST.MONTO_DESCUENTO,
  COTIZACION_MAST.MONTO_INICIAL,
  COTIZACION_MAST.NOMBRE_CLIENTE_GENERAL,
  COTIZACION_MAST.MONTO_PAGADO,
  COTIZACION_MAST.MONTO_CAMBIO,
  COTIZACION_MAST.MONTO_TOTAL_ITBIS,
  COTIZACION_MAST.MONTODESCGASTOSADMIN,
  COTIZACION_MAST.MONTODESCITBISGASTOSADMIN,
  COTIZACION_MAST.MONTODESCTRANSP,
  COTIZACION_MAST.MONTODESCDIRTECNICA,
  COTIZACION_MAST.MONTODESCITBISDIRTECNICA,
  COTIZACION_MAST.MONTODESCIMPREVISTO,
  COTIZACION_MAST.MONTODESCITBISIMPREVISTO,
  COTIZACION_MAST.TIPO_FACTURA,
  COTIZACION_MAST.APLICA_TIPODESC,
  COTIZACION_MAST.COMENTARIO
FROM
  COTIZACION_MAST
;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEW_COTIZACION_MASTER TO  DIVISON WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEW_COTIZACION_MASTER TO  SYSDBA;
