SET TERM ^ ;
create PROCEDURE PROC_update_COTIZACION_MAST (
    FECHA timestamp,
    FECHA_VENCE timestamp,
    CODIGO_CTE integer,
    CODIGO_VENDEDOR integer,
    OBSERVACION varchar(60),
    MONEDA char(1),
    VALOR_TOTAL numeric(15,2),
    STATUS char(1),
    FECHA_IN timestamp,
    IN_POR varchar(12),
    FECHA_MOD timestamp,
    MOD_POR varchar(12),
    NUMERO_FACTURA smallint,
    NUMERO_DOC_PAGO varchar(20),
    SERIE_NCF_ASIGNADO smallint,
    MONTO_BRUTO numeric(15,2),
    PORC_DESCUENTO smallint,
    MONTO_DESCUENTO numeric(15,2),
    MONTO_INICIAL numeric(15,2),
    NOMBRE_CLIENTE_GENERAL varchar(60),
    MONTO_PAGADO numeric(15,2),
    MONTO_CAMBIO numeric(15,2),
    MONTO_TOTAL_ITBIS numeric(15,2),
    MONTODESCGASTOSADMIN numeric(15,2),
    MONTODESCITBISGASTOSADMIN numeric(15,2),
    MONTODESCTRANSP numeric(15,2),
    MONTODESCDIRTECNICA numeric(15,2),
    MONTODESCITBISDIRTECNICA numeric(15,2),
    MONTODESCIMPREVISTO numeric(15,2),
    MONTODESCITBISIMPREVISTO numeric(15,2),
    TIPO_FACTURA smallint,
    APLICA_TIPODESC smallint,
    numero_cotiza integer,
    Comentario blob sub_type 1  )
RETURNS (
    NUMERO_TRNS integer )
AS
declare variable xnumero integer;
BEGIN   
  NUMERO_TRNS = :numero_cotiza;
  update COTIZACION_MAST 
  set     
        FECHA =    :FECHA,
    FECHA_VENCE=    :FECHA_VENCE,
    CODIGO_CTE=    :CODIGO_CTE,
    CODIGO_VENDEDOR=    :CODIGO_VENDEDOR,
    OBSERVACION=    :OBSERVACION,
    MONEDA=    :MONEDA,
    VALOR_TOTAL=    :VALOR_TOTAL,
    STATUS=    :STATUS,
    FECHA_IN=    :FECHA_IN,
    IN_POR=    :IN_POR,
    FECHA_MOD=    :FECHA_MOD,
    MOD_POR=    :MOD_POR,
  NUMERO_FACTURA=    :NUMERO_FACTURA,
  NUMERO_DOC_PAGO=  :NUMERO_DOC_PAGO,
  SERIE_NCF_ASIGNADO=  :SERIE_NCF_ASIGNADO,
  MONTO_BRUTO=  :MONTO_BRUTO,
  PORC_DESCUENTO=  :PORC_DESCUENTO,
  MONTO_DESCUENTO =  :MONTO_DESCUENTO ,
  MONTO_INICIAL=  :MONTO_INICIAL,
  NOMBRE_CLIENTE_GENERAL=  :NOMBRE_CLIENTE_GENERAL,
  MONTO_PAGADO=  :MONTO_PAGADO,
  MONTO_CAMBIO=  :MONTO_CAMBIO,
  MONTO_TOTAL_ITBIS=  :MONTO_TOTAL_ITBIS,
  MONTODESCGASTOSADMIN=  :MONTODESCGASTOSADMIN,
  MONTODESCITBISGASTOSADMIN=  :MONTODESCITBISGASTOSADMIN,
  MONTODESCTRANSP =  :MONTODESCTRANSP ,
  MONTODESCDIRTECNICA=  :MONTODESCDIRTECNICA,
  MONTODESCITBISDIRTECNICA=  :MONTODESCITBISDIRTECNICA,
  MONTODESCIMPREVISTO =  :MONTODESCIMPREVISTO ,
  MONTODESCITBISIMPREVISTO=  :MONTODESCITBISIMPREVISTO, 
  TIPO_FACTURA=  :TIPO_FACTURA,
  COTIZACION_MAST.APLICA_TIPODESC =:APLICA_TIPODESC,
  COTIZACION_MAST.Comentario=:comentario
 Where COTIZACION_MAST.numero = :numero_cotiza;
  SUSPEND;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE PROC_update_COTIZACION_MAST TO  DIVISON;
