Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(1,1,'ACROMAX DOMINICANA ,S.A. ','809-531-0164','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(2,1,'DISFARCAMP, C. POR A ','809-560-0900','809-560-3100','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(3,1,'DISTRIBUIDORA CALDERON C. POR A. ','''','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(4,1,'DISTRIBUIDORA COMERCIAL SOSA,C X A.','809-557-1670','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(5,1,'DISTRIBUIDORA EDESSA, COLGATE ','809-527-7807','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(6,1,'DR. MANELIC GASSO-PEREYRA,C. POR A.','809-473-8300','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(7,1,'Dr. elizardo perez espinosa, c. por a.','809-530-5423','809-530-5424','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(8,1,'ELIJO FARMACEUTICA','809-528-0799','809-528-2725','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(9,1,'ETHICAL PHARMACEUTICAL ','809-544-3360','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(10,1,'F. REYES & Co., C. POR A. ','809-689-7895','809-200-7895','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(11,1,'FARCARIBE ','809-532-2178','809-2005832','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(12,1,'ALFAU & SANCHEZ,C.POR A. ','809-381-2620','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(13,1,'FARGESA, S. A. ','809-682-4344','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(14,1,'FARMACONAL ','809-539-5545','809-200-1419','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(15,1,'FARQUI INDUSTRIA  FARMOQUIMICA, C.XA ','809-530-6531','809-200-1541','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(16,1,'FONT, GAMUNDI & Co.,C. POR A. ','809-200-198','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(17,1,'FRANK RODRIGUEZ JIMENEZ ','809-530-6531','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(18,1,'GenCaSa','809-594-5713','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(19,1,'KETTE SANCHEZ & CO., C. POR A. ','809-689-7101','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(20,1,'L & F COMERCIAL ','809-537-3800','809-428-3000','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(21,1,'LABORATORIO CYMACLA, S.A. ','809-567-9789','809-200-3050','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(22,1,'LABORATORIO DR. COLLADO, C. POR A. ','809-532-7361','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(23,1,'ALTER, S. A. ','809-565-8802','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(24,1,'LABORATORIO SAN LUIS, C. POR A ','809-379-0876','809-200-3336','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(25,1,'LABORATORIOS EXELS, S. A. ','809-221-7055','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(26,1,'LABORATORIOS FELTREX, S. A. ','809-567-1510','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(27,1,'LABORATORIOS LAANED','809-567-3223','809-200-1638','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(28,1,'LABORATORIOS LACOFARMA, C.POR A. ','809-569-2400','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(29,1,'LABORATORIOS LAM ','809-338-1616','809-200-8526','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(30,1,'LABORATORIOS LAPROFAR ','809-568-7401','68026710','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(31,1,'LABORATORIOS ORBIS, S. A. ','809-537-7474','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(32,1,'LABORATORIOS QUIMICOS DOM,C.PxA.','809-535-1787','809-200-3783','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(33,1,'LAROXXE,S.A. ','809-683-2858','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(34,1,'ARTOFARMA,C. X A.','809-566-1232','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(35,1,'LETERAGO C. POR A.','809-687-5155','809-685-1044','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(36,1,'LINEA, S. A. ','809-687-5155','809-685-1044','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(37,1,'MALLEN GUERRA, C. POR A. ','809-683-7000','809-200-2586','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(38,1,'MAXIMO GOMEZ P., C. POR A.','809-566-3111','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(39,1,'MEDEK PHARMA, S. A.','809-334-0092','809-200-8182','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(40,1,'MERCANTIL FARMACEUTICA, S. A. ','''','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(41,1,'MERYS PHARMACEUTICALS, S. A','809-689-1934','809-304-2401','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(42,1,'NOVARTIS  ','809-686-7676','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(43,1,'NIFARMED, S. A.','809-2001514','809-531-4366','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(44,1,'NUTRIFARMA, S. A. ','809-200-252','809-567-328','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(45,1,'BAYER,S. A. ','809-530-8086','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(46,1,'O H M MOBILE SERVICES (ORANGE)','809-521-3487','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(47,1,'OLDMAC, C. POR A. ','809-560-4077','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(48,1,'OSCAR RENTA NEGRON,C. POR A. ','809-689-8542','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(49,1,'P & M ASOCIADOS,C.X A. ','809-528-3633','809-200-0010','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(50,1,'PHARMATECH (PROVEEDDOR)','80-682-8000','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(51,1,'PROMEDCA ','809-473-4949','562-2323','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(52,1,'REDIFAR,S. A. ','809-531-3167','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(53,1,'SAINT-HITAIRE COMERCIAL,S.A.','809-598-4449','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(54,1,'SANISA PHARMACEUTICALS,C. POR A.','809-568-2260','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(55,1,'SANOFI AVENTIS ','809-200-3332','809-537-3333','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(56,1,'BRUGAL & Co.,CPOR A. ','809-561-5651','809-200-4010','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(57,1,'SHERING DOMINICANA, S. A.','809-200-137','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(58,1,'SUED FARMACEUTICA, C. POR A. ','809-682-4344','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(59,1,'VICTORIA YEB, S.A. ','809-701-6565','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(60,1,'VARIOS','''','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(61,1,'DR. ARISTY RODRIGUEZ,C. POR A.','809-686-0849','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(62,1,'RUIZ & Co., POR A.','809-241-7413','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(63,1,'PHARMA CORP,C.POR A.','809-487-1010','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(64,1,'DISFAPENN','''','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(65,1,'DISTRIBUIDARA FARMACEUTICA JIMENEZ','809-380-0310','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(66,1,'A M COMERCIAL,C. X A.','''','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(67,1,'C.FEDERICO GOMEZG., C.POR A. ','809-227-1116','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(68,1,'SUIPHAR, S. A.','''','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(69,1,'TECNOMED DEL CARIBE','1-809-200-14','8','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(70,1,'SUNCAR,DOMINICANA','809-616-1135','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(71,1,'E Y S FARMACEUTICA','''','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(72,1,'DINAFA','809-200-010',',','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(73,1,'FERRETERIA SANFEL','809-521-9323','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(74,1,'FARACH,S.A','809-544-0222','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(75,1,'LABORATORIOS RANGEL C X A','809-573-3885','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(76,1,'Advanced CompuTech','809-522-411','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(77,1,'METROMED','809-518-0000','','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(78,1,'CARICORP ','809-687-6262','809687-6363','A','DIVISON');
Insert into Proveedores(codigo_cte, tipo_cliente, descripcion, telefono, fax, status, in_por) Values(79,1,'DANIEL ESPINAL, C. POR A. ','809-620-6000','','A','DIVISON');
