SET TERM ^ ;

CREATE OR ALTER PROCEDURE PROC_ECF_POST_CXC (
    P_FECHA             TIMESTAMP,
    P_FECHA_VENCE       TIMESTAMP,
    P_DESCRIPCION       VARCHAR(120),
    P_CODIGO_USUARIO    INTEGER,
    P_CODIGO_CTE        INTEGER,
    P_MONTO             NUMERIC(15,2),
    P_NUMERO_FACT       INTEGER,
    P_NUMERO_TRN_VTA    INTEGER,
    P_MONEDA            VARCHAR(2),
    P_CODIGO_VENDEDOR   INTEGER,
    P_TIPO_FACT         SMALLINT,
    P_TIPO_DOC          SMALLINT,
    P_TIPO_TRANF        SMALLINT,
    P_TIPO_SERV         SMALLINT
)
RETURNS (
    O_SERIE_FACTURA     INTEGER,
    O_NUMERO_FACT       INTEGER,
    O_SERIE_TRANS_CXC   INTEGER
)
AS
DECLARE VARIABLE V_CIA_KEY              INTEGER;
DECLARE VARIABLE V_USUARIO              VARCHAR(12);
DECLARE VARIABLE V_CANT_CLIENTES         INTEGER;
DECLARE VARIABLE V_CANT_FACTURAS         INTEGER;
DECLARE VARIABLE V_CANT_FACT_PEND        INTEGER;
DECLARE VARIABLE V_CANT_TRANS_CXC        INTEGER;
DECLARE VARIABLE V_CANT_BALANCE          INTEGER;
DECLARE VARIABLE V_NUEVA_TRANS_CXC       SMALLINT;
DECLARE VARIABLE V_FACT_CODIGO_CTE       INTEGER;
DECLARE VARIABLE V_FACT_NUMERO_TRN_VTA   INTEGER;
DECLARE VARIABLE V_FACT_MONEDA           VARCHAR(2);
DECLARE VARIABLE V_FACT_TIPO             SMALLINT;
DECLARE VARIABLE V_FACT_MONTO            NUMERIC(15,2);
DECLARE VARIABLE V_FACT_STATUS           CHAR(1);
DECLARE VARIABLE V_FACT_PEND_MONTO       NUMERIC(15,2);
DECLARE VARIABLE V_FACT_PEND_STATUS      CHAR(1);
DECLARE VARIABLE V_TRANS_MONTO           NUMERIC(15,2);
DECLARE VARIABLE V_TRANS_TIPO_TRANF      SMALLINT;
DECLARE VARIABLE V_TRANS_TIPO_SERV       SMALLINT;
BEGIN
  O_SERIE_FACTURA = NULL;
  O_NUMERO_FACT = P_NUMERO_FACT;
  O_SERIE_TRANS_CXC = NULL;
  V_NUEVA_TRANS_CXC = 0;

  IF (P_FECHA IS NULL) THEN
    EXCEPTION EX_INVALID_PARAM 'La fecha de la factura es obligatoria.';

  IF (P_FECHA_VENCE IS NULL) THEN
    P_FECHA_VENCE = P_FECHA;

  IF (P_CODIGO_CTE IS NULL OR P_CODIGO_CTE <= 0) THEN
    EXCEPTION EX_INVALID_PARAM 'El codigo del cliente es obligatorio.';

  IF (P_NUMERO_FACT IS NULL OR P_NUMERO_FACT <= 0) THEN
    EXCEPTION EX_INVALID_PARAM 'El numero de factura es obligatorio.';

  IF (P_NUMERO_TRN_VTA IS NULL OR P_NUMERO_TRN_VTA <= 0) THEN
    EXCEPTION EX_INVALID_PARAM 'El numero de VENTAS_MAST es obligatorio.';

  IF (P_MONTO IS NULL OR P_MONTO <= 0) THEN
    EXCEPTION EX_INVALID_PARAM 'El monto debe ser mayor que cero.';

  IF (P_MONEDA IS NULL OR TRIM(P_MONEDA) = '') THEN P_MONEDA = '1';
  IF (P_DESCRIPCION IS NULL OR TRIM(P_DESCRIPCION) = '') THEN P_DESCRIPCION = 'Venta';
  IF (P_CODIGO_USUARIO IS NULL OR P_CODIGO_USUARIO <= 0) THEN P_CODIGO_USUARIO = 40;
  IF (P_CODIGO_VENDEDOR IS NULL) THEN P_CODIGO_VENDEDOR = 0;
  IF (P_TIPO_FACT IS NULL) THEN P_TIPO_FACT = 2;
  IF (P_TIPO_DOC IS NULL) THEN P_TIPO_DOC = 1;
  IF (P_TIPO_TRANF IS NULL) THEN P_TIPO_TRANF = 1;
  IF (P_TIPO_SERV IS NULL) THEN P_TIPO_SERV = 2;

  P_MONEDA = TRIM(P_MONEDA);
  V_USUARIO = CAST(P_CODIGO_USUARIO AS VARCHAR(12));

  SELECT COUNT(*), MAX(CIA_KEY)
    FROM CLIENTES
   WHERE CODIGO_CTE = :P_CODIGO_CTE
    INTO :V_CANT_CLIENTES, :V_CIA_KEY;

  IF (V_CANT_CLIENTES <> 1) THEN
    EXCEPTION EX_INVALID_PARAM 'El cliente no existe o esta duplicado.';

  IF (V_CIA_KEY IS NULL OR V_CIA_KEY <= 0) THEN
    EXCEPTION EX_INVALID_PARAM 'El cliente no tiene una compania valida.';

  SELECT COUNT(*) FROM FACTURAS
   WHERE NUMERO = :P_NUMERO_FACT
    INTO :V_CANT_FACTURAS;

  IF (V_CANT_FACTURAS > 1) THEN
    EXCEPTION EX_INVALID_PARAM 'Existe mas de una factura con ese numero.';

  IF (V_CANT_FACTURAS = 0) THEN
  BEGIN
    SELECT GEN_ID(GEN_SERIE_FACTURA, 1)
      FROM RDB$DATABASE
      INTO :O_SERIE_FACTURA;

    INSERT INTO FACTURAS
    (
      SERIE, NUMERO, NUMERO_TRN_VTA, MONEDA, TIPO, CODIGO_CTE,
      FECHA, FECHA_VENCE, DESCRIPCION, MONTO_FACT, RCXC, STATUS,
      TIPO_FACTURA, FECHA_IN, IN_POR, CIA_KEY
    )
    VALUES
    (
      :O_SERIE_FACTURA, :P_NUMERO_FACT, :P_NUMERO_TRN_VTA,
      :P_MONEDA, :P_TIPO_FACT, :P_CODIGO_CTE,
      CAST(:P_FECHA AS DATE), CAST(:P_FECHA_VENCE AS DATE),
      :P_DESCRIPCION, :P_MONTO, 'R', 'F', 1,
      CURRENT_TIMESTAMP, :V_USUARIO, :V_CIA_KEY
    );
  END
  ELSE
  BEGIN
    SELECT FIRST 1
        SERIE, CODIGO_CTE, NUMERO_TRN_VTA, MONEDA,
        TIPO, MONTO_FACT, STATUS
      FROM FACTURAS
     WHERE NUMERO = :P_NUMERO_FACT
      INTO
        :O_SERIE_FACTURA, :V_FACT_CODIGO_CTE,
        :V_FACT_NUMERO_TRN_VTA, :V_FACT_MONEDA,
        :V_FACT_TIPO, :V_FACT_MONTO, :V_FACT_STATUS;

    IF (COALESCE(V_FACT_CODIGO_CTE, 0) <> P_CODIGO_CTE) THEN
      EXCEPTION EX_INVALID_PARAM 'La factura pertenece a otro cliente.';

    IF (TRIM(COALESCE(V_FACT_MONEDA, '')) <> P_MONEDA) THEN
      EXCEPTION EX_INVALID_PARAM 'La moneda de la factura no coincide.';

    IF (COALESCE(V_FACT_TIPO, 0) <> P_TIPO_FACT) THEN
      EXCEPTION EX_INVALID_PARAM 'El tipo de factura no coincide.';

    IF (ABS(COALESCE(V_FACT_MONTO, 0) - P_MONTO) > 0.01) THEN
      EXCEPTION EX_INVALID_PARAM 'El monto de la factura no coincide.';

    IF (COALESCE(V_FACT_NUMERO_TRN_VTA, 0) > 0 AND
        V_FACT_NUMERO_TRN_VTA <> P_NUMERO_TRN_VTA) THEN
      EXCEPTION EX_INVALID_PARAM 'La factura esta vinculada a otra venta.';

    IF (COALESCE(V_FACT_STATUS, '') NOT IN ('F', 'P')) THEN
      EXCEPTION EX_INVALID_PARAM 'Estado de factura incompatible.';

    UPDATE FACTURAS
       SET NUMERO_TRN_VTA = :P_NUMERO_TRN_VTA,
           FECHA_VENCE = CAST(:P_FECHA_VENCE AS DATE),
           RCXC = 'R', STATUS = 'F', TIPO_FACTURA = 1,
           CIA_KEY = :V_CIA_KEY
     WHERE SERIE = :O_SERIE_FACTURA;
  END

  SELECT COUNT(*)
    FROM FACTURAS_PENDIENTES
   WHERE NUMERO_FACT = :P_NUMERO_FACT
     AND MONEDA = :P_MONEDA
     AND TIPO = :P_TIPO_FACT
    INTO :V_CANT_FACT_PEND;

  IF (V_CANT_FACT_PEND > 1) THEN
    EXCEPTION EX_INVALID_PARAM 'Factura pendiente duplicada.';

  IF (V_CANT_FACT_PEND = 0) THEN
  BEGIN
    INSERT INTO FACTURAS_PENDIENTES
      (TIPO, MONEDA, NUMERO_FACT, MONTO_PENDIENTE, STATUS)
    VALUES
      (:P_TIPO_FACT, :P_MONEDA, :P_NUMERO_FACT, :P_MONTO, 'A');
  END
  ELSE
  BEGIN
    SELECT FIRST 1 MONTO_PENDIENTE, STATUS
      FROM FACTURAS_PENDIENTES
     WHERE NUMERO_FACT = :P_NUMERO_FACT
       AND MONEDA = :P_MONEDA
       AND TIPO = :P_TIPO_FACT
      INTO :V_FACT_PEND_MONTO, :V_FACT_PEND_STATUS;

    IF (ABS(COALESCE(V_FACT_PEND_MONTO, 0) - P_MONTO) > 0.01) THEN
      EXCEPTION EX_INVALID_PARAM 'El monto pendiente no coincide.';

    IF (COALESCE(V_FACT_PEND_STATUS, '') <> 'A') THEN
      EXCEPTION EX_INVALID_PARAM 'Estado de factura pendiente incompatible.';
  END

  SELECT COUNT(*)
    FROM TRANS_CXC
   WHERE NUMERO_DOC = :P_NUMERO_FACT
     AND TIPO_DOC = :P_TIPO_DOC
     AND CODIGO_CLIENTE = :P_CODIGO_CTE
     AND MONEDA = :P_MONEDA
    INTO :V_CANT_TRANS_CXC;

  IF (V_CANT_TRANS_CXC > 1) THEN
    EXCEPTION EX_INVALID_PARAM 'Transaccion CxC duplicada.';

  IF (V_CANT_TRANS_CXC = 0) THEN
  BEGIN
    SELECT GEN_ID(GEN_SERIE_TRN_CXC, 1)
      FROM RDB$DATABASE
      INTO :O_SERIE_TRANS_CXC;

    INSERT INTO TRANS_CXC
    (
      SERIE, TIPO_DOC, MONEDA, FECHA, NUMERO_DOC,
      CODIGO_CLIENTE, CODIGO_SERV, CONCEPTO, VALOR_DOCUMENTO,
      TIPO_TRANF, STATUS, TIPO_SERV, FECHA_IN, IN_POR,
      CODIGO_VENDEDOR, CIA_KEY
    )
    VALUES
    (
      :O_SERIE_TRANS_CXC, :P_TIPO_DOC, :P_MONEDA,
      CAST(:P_FECHA AS DATE), :P_NUMERO_FACT, :P_CODIGO_CTE,
      0, :P_DESCRIPCION, :P_MONTO, :P_TIPO_TRANF,
      'R', :P_TIPO_SERV, CURRENT_TIMESTAMP, :V_USUARIO,
      :P_CODIGO_VENDEDOR, :V_CIA_KEY
    );

    V_NUEVA_TRANS_CXC = 1;
  END
  ELSE
  BEGIN
    SELECT FIRST 1 SERIE, VALOR_DOCUMENTO, TIPO_TRANF, TIPO_SERV
      FROM TRANS_CXC
     WHERE NUMERO_DOC = :P_NUMERO_FACT
       AND TIPO_DOC = :P_TIPO_DOC
       AND CODIGO_CLIENTE = :P_CODIGO_CTE
       AND MONEDA = :P_MONEDA
      INTO :O_SERIE_TRANS_CXC, :V_TRANS_MONTO,
           :V_TRANS_TIPO_TRANF, :V_TRANS_TIPO_SERV;

    IF (ABS(COALESCE(V_TRANS_MONTO, 0) - P_MONTO) > 0.01) THEN
      EXCEPTION EX_INVALID_PARAM 'El monto de TRANS_CXC no coincide.';

    IF (COALESCE(V_TRANS_TIPO_TRANF, 0) <> P_TIPO_TRANF) THEN
      EXCEPTION EX_INVALID_PARAM 'TIPO_TRANF no coincide.';

    IF (COALESCE(V_TRANS_TIPO_SERV, 0) <> P_TIPO_SERV) THEN
      EXCEPTION EX_INVALID_PARAM 'TIPO_SERV no coincide.';

    UPDATE TRANS_CXC
       SET STATUS = 'R',
           CODIGO_VENDEDOR = :P_CODIGO_VENDEDOR,
           CIA_KEY = :V_CIA_KEY
     WHERE SERIE = :O_SERIE_TRANS_CXC;
  END

  IF (V_NUEVA_TRANS_CXC = 1) THEN
  BEGIN
    SELECT COUNT(*)
      FROM BALANCE_CTE
     WHERE CODIGO = :P_CODIGO_CTE
       AND SERVICIO = 1
       AND MONEDA = :P_MONEDA
      INTO :V_CANT_BALANCE;

    IF (V_CANT_BALANCE > 1) THEN
      EXCEPTION EX_INVALID_PARAM 'Balance del cliente duplicado.';

    IF (V_CANT_BALANCE = 1) THEN
    BEGIN
      UPDATE BALANCE_CTE
         SET BALANCE_ANT = COALESCE(BALANCE_ACT, 0),
             BALANCE_ACT = COALESCE(BALANCE_ACT, 0) + :P_MONTO,
             DEBITO_MES = COALESCE(DEBITO_MES, 0) + :P_MONTO,
             DEBITO_ACM = COALESCE(DEBITO_ACM, 0) + :P_MONTO,
             FECHA_BCE = CAST(:P_FECHA AS DATE),
             FECHA_MOD = CURRENT_TIMESTAMP
       WHERE CODIGO = :P_CODIGO_CTE
         AND SERVICIO = 1
         AND MONEDA = :P_MONEDA;
    END
    ELSE
    BEGIN
      INSERT INTO BALANCE_CTE
      (
        CODIGO, SERVICIO, MONEDA, BALANCE_ACT, BALANCE_ANT,
        DEBITO_MES, CREDITO_MES, DEBITO_ACM, CREDITO_ACM,
        FECHA_BCE, FECHA_IN, IN_POR
      )
      VALUES
      (
        :P_CODIGO_CTE, 1, :P_MONEDA, :P_MONTO, 0,
        :P_MONTO, 0, :P_MONTO, 0,
        CAST(:P_FECHA AS DATE), CURRENT_TIMESTAMP, :V_USUARIO
      );
    END
  END

  SUSPEND;
END^

SET TERM ; ^
