/* Sustituya los límites si cambia el lote. */

SELECT
    N.NUMERO_NCF,
    N.MONTO,
    N.DGII_STATUS,
    V.NUMERO AS NUMERO_VENTA,
    V.NUMERO_FACTURA,
    V.NUMERO_DOC_PAGO,
    V.FORMA_PAGO,
    V.CODIGO_CTE,
    V.COD_USR_CAJA,
    V.CODIGO_VENDEDOR,
    V.OBSERVACION,
    V.COMENTARIO,
    V.TIPONCFIFISCAL,
    V.VALOR_TOTAL_DET,
    V.MONTO_TOTAL_ITBIS,
    V.STATUS
FROM NCF_ASIGNADOS N
JOIN VENTAS_MAST V ON V.SERIE_NCF_ASIGNADO = N.SERIE
WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
      BETWEEN 50907 AND 50921
ORDER BY N.NUMERO_NCF;

SELECT
    V.NUMERO,
    COUNT(D.SERIE) AS LINEAS,
    SUM(D.VALOR_TOTAL_DET) AS TOTAL_DETALLE,
    SUM(D.ITBIS_FISCAL_DET) AS ITBIS_FISCAL_DETALLE,
    SUM(D.ITBI_DET) AS ITBI_DETALLE,
    V.VALOR_TOTAL_DET AS TOTAL_MASTER,
    V.MONTO_TOTAL_ITBIS AS ITBIS_MASTER
FROM VENTAS_MAST V
JOIN NCF_ASIGNADOS N ON N.SERIE = V.SERIE_NCF_ASIGNADO
JOIN VENTAS_DET D ON D.NUMERO = V.NUMERO
WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
      BETWEEN 50907 AND 50921
GROUP BY V.NUMERO, V.VALOR_TOTAL_DET, V.MONTO_TOTAL_ITBIS
ORDER BY V.NUMERO;

SELECT
    F.NUMERO,
    F.NUMERO_TRN_VTA,
    F.CODIGO_CTE,
    F.MONTO_FACT,
    FP.MONTO_PENDIENTE,
    T.VALOR_DOCUMENTO,
    T.STATUS
FROM FACTURAS F
JOIN FACTURAS_PENDIENTES FP
  ON FP.NUMERO_FACT = F.NUMERO
 AND FP.MONEDA = F.MONEDA
 AND FP.TIPO = F.TIPO
JOIN TRANS_CXC T
  ON T.NUMERO_DOC = F.NUMERO
 AND T.CODIGO_CLIENTE = F.CODIGO_CTE
WHERE F.CODIGO_CTE = 838
  AND F.NUMERO_TRN_VTA IN
      (
        SELECT V.NUMERO
        FROM VENTAS_MAST V
        JOIN NCF_ASIGNADOS N ON N.SERIE = V.SERIE_NCF_ASIGNADO
        WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
              BETWEEN 50907 AND 50921
      )
ORDER BY F.NUMERO;


/* Estado final de la secuencia de documento de pago para ventas al contado. */
SELECT TIPO, SECUENCIA, FECHA_UPDATE, COD_USUARIO
FROM SECUENCIA
WHERE TIPO = 1;

/* Cada contado del lote debe tener NUMERO_DOC_PAGO único y no nulo. */
SELECT
    V.NUMERO_DOC_PAGO,
    COUNT(*) AS CANTIDAD
FROM VENTAS_MAST V
JOIN NCF_ASIGNADOS N ON N.SERIE = V.SERIE_NCF_ASIGNADO
WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
      BETWEEN 50907 AND 50921
  AND V.FORMA_PAGO = 1
GROUP BY V.NUMERO_DOC_PAGO
HAVING V.NUMERO_DOC_PAGO IS NULL OR COUNT(*) <> 1;

/* Debe retornar cero filas. */
SELECT
    N.NUMERO_NCF,
    V.NUMERO,
    V.FORMA_PAGO,
    V.CODIGO_CTE,
    V.COD_USR_CAJA,
    V.CODIGO_VENDEDOR,
    V.OBSERVACION,
    V.NUMERO_FACTURA,
    V.NUMERO_DOC_PAGO,
    V.TIPONCFIFISCAL
FROM VENTAS_MAST V
JOIN NCF_ASIGNADOS N ON N.SERIE = V.SERIE_NCF_ASIGNADO
WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
      BETWEEN 50907 AND 50921
  AND
  (
       V.COD_USR_CAJA <> 40
    OR V.CODIGO_VENDEDOR IS NOT NULL
    OR V.TIPONCFIFISCAL <> 2
    OR (V.FORMA_PAGO = 1 AND
        (V.CODIGO_CTE <> 0 OR V.OBSERVACION <> 'CONTADO' OR
         V.NUMERO_FACTURA IS NOT NULL OR V.NUMERO_DOC_PAGO IS NULL))
    OR (V.FORMA_PAGO = 7 AND
        (V.CODIGO_CTE <> 838 OR V.OBSERVACION <> 'Venta a Credito' OR
         V.NUMERO_FACTURA IS NULL OR V.NUMERO_DOC_PAGO IS NOT NULL))
  )
ORDER BY N.NUMERO_NCF;


/* Debe retornar cero filas: ambos campos de ITBIS deben ser iguales por linea. */
SELECT
    N.NUMERO_NCF,
    V.NUMERO AS NUMERO_VENTA,
    D.SERIE AS SERIE_DETALLE,
    D.CODIGO_PROD,
    D.ITBI_DET,
    D.ITBIS_FISCAL_DET
FROM VENTAS_MAST V
JOIN NCF_ASIGNADOS N ON N.SERIE = V.SERIE_NCF_ASIGNADO
JOIN VENTAS_DET D ON D.NUMERO = V.NUMERO
WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
      BETWEEN 50907 AND 50921
  AND ABS(COALESCE(D.ITBI_DET, 0) - COALESCE(D.ITBIS_FISCAL_DET, 0)) > 0.01
ORDER BY N.NUMERO_NCF, D.SERIE;


/* Debe retornar cero filas: el bruto persistido de cada línea debe coincidir
   con VALOR_TOTAL_DET para este lote sin descuentos por ítem. */
SELECT
    N.NUMERO_NCF,
    V.NUMERO AS NUMERO_VENTA,
    D.SERIE AS SERIE_DETALLE,
    D.CODIGO_PROD,
    D.CANTIDAD,
    D.PRECIO,
    D.VALOR_SERVICIO_DET,
    D.VALOR_TOTAL_DET
FROM VENTAS_MAST V
JOIN NCF_ASIGNADOS N ON N.SERIE = V.SERIE_NCF_ASIGNADO
JOIN VENTAS_DET D ON D.NUMERO = V.NUMERO
WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
      BETWEEN 50907 AND 50921
  AND ABS(COALESCE(D.VALOR_SERVICIO_DET, 0) -
          COALESCE(D.VALOR_TOTAL_DET, 0)) > 0.01
ORDER BY N.NUMERO_NCF, D.SERIE;


/* Debe retornar cero filas: MONTO_BRUTO del encabezado debe coincidir con
   la suma del bruto persistido en el detalle. */
SELECT
    N.NUMERO_NCF,
    V.NUMERO AS NUMERO_VENTA,
    V.MONTO_BRUTO,
    SUM(COALESCE(D.VALOR_SERVICIO_DET, 0)) AS BRUTO_DETALLE
FROM VENTAS_MAST V
JOIN NCF_ASIGNADOS N ON N.SERIE = V.SERIE_NCF_ASIGNADO
JOIN VENTAS_DET D ON D.NUMERO = V.NUMERO
WHERE CAST(SUBSTRING(N.NUMERO_NCF FROM 4 FOR 10) AS INTEGER)
      BETWEEN 50907 AND 50921
GROUP BY N.NUMERO_NCF, V.NUMERO, V.MONTO_BRUTO
HAVING ABS(COALESCE(V.MONTO_BRUTO, 0) -
           SUM(COALESCE(D.VALOR_SERVICIO_DET, 0))) > 0.01
ORDER BY N.NUMERO_NCF;
