/*
   Verifica si DETALLE_PAGOS.SERIE se asigna mediante trigger y muestra
   los generadores referenciados por triggers de la tabla.
*/

SELECT
    TRIM(T.RDB$TRIGGER_NAME) AS TRIGGER_NAME,
    T.RDB$TRIGGER_TYPE,
    T.RDB$TRIGGER_INACTIVE,
    T.RDB$TRIGGER_SOURCE
FROM RDB$TRIGGERS T
WHERE TRIM(T.RDB$RELATION_NAME) = 'DETALLE_PAGOS'
ORDER BY T.RDB$TRIGGER_NAME;

SELECT
    TRIM(D.RDB$DEPENDENT_NAME) AS TRIGGER_NAME,
    TRIM(D.RDB$DEPENDED_ON_NAME) AS GENERATOR_NAME
FROM RDB$DEPENDENCIES D
WHERE D.RDB$DEPENDENT_TYPE = 2
  AND D.RDB$DEPENDED_ON_TYPE = 14
  AND D.RDB$DEPENDENT_NAME IN
      (
        SELECT T.RDB$TRIGGER_NAME
        FROM RDB$TRIGGERS T
        WHERE TRIM(T.RDB$RELATION_NAME) = 'DETALLE_PAGOS'
      )
ORDER BY D.RDB$DEPENDENT_NAME;
