
-- ============================================
-- SCRIPT DE CREACIÓN DE ESTRUCTURA LAVANDERÍA
-- Firebird 2.5
-- ============================================

-- 1. TABLA LAV_ORDEN
CREATE TABLE LAV_ORDEN (
  ID INTEGER NOT NULL PRIMARY KEY,
  ID_CLIENTE INTEGER NOT NULL,
  FECHA_ENTRADA TIMESTAMP NOT NULL,
  FECHA_ENTREGA TIMESTAMP,
  ESTADO VARCHAR(20),
  APLICA_ITBIS SMALLINT DEFAULT 0,
  ID_OPERADOR SMALLINT,
  NOTAS VARCHAR(255),
  TOTAL NUMERIC(15,2)
);

-- 2. TABLA LAV_PRENDA
CREATE TABLE LAV_PRENDA (
  ID INTEGER NOT NULL PRIMARY KEY,
  ID_ORDEN INTEGER NOT NULL,
  CODIGO_PRODUCTO INTEGER NOT NULL,
  CANTIDAD INTEGER DEFAULT 1,
  PRECIO_UNITARIO NUMERIC(15,2),
  MONTO_BASE NUMERIC(15,2),
  MONTO_ITBIS NUMERIC(15,2),
  TOTAL_LINEA NUMERIC(15,2),
  ETAPA_ACTUAL VARCHAR(20),
  CODIGO_BARRA VARCHAR(40),
  FOREIGN KEY (ID_ORDEN) REFERENCES LAV_ORDEN(ID),
  FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES INVENTARIO_PRODUCTO(CODIGO)
);

-- 3. TABLA LAV_HISTORIAL
CREATE TABLE LAV_HISTORIAL (
  ID INTEGER NOT NULL PRIMARY KEY,
  ID_PRENDA INTEGER NOT NULL,
  ETAPA VARCHAR(20),
  FECHA_HORA TIMESTAMP,
  USUARIO_ID SMALLINT,
  FOREIGN KEY (ID_PRENDA) REFERENCES LAV_PRENDA(ID),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(NUMERO)
);

-- 4. GENERADORES
CREATE GENERATOR GEN_LAV_ORDEN_ID;
CREATE GENERATOR GEN_LAV_PRENDA_ID;
CREATE GENERATOR GEN_LAV_HISTORIAL_ID;

-- 5. TRIGGERS
SET TERM !! ;

CREATE TRIGGER BI_LAV_ORDEN_ID FOR LAV_ORDEN
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_LAV_ORDEN_ID, 1);
END!!

CREATE TRIGGER BI_LAV_PRENDA_ID FOR LAV_PRENDA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_LAV_PRENDA_ID, 1);
END!!

CREATE TRIGGER BI_LAV_HISTORIAL_ID FOR LAV_HISTORIAL
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_LAV_HISTORIAL_ID, 1);
END!!

SET TERM ; !!
