
-- ============================================
-- VISTAS E ÍNDICES PARA MÓDULO DE LAVANDERÍA
-- Firebird 2.5
-- ============================================

-- VISTA 1: Ordenes con resumen de cliente, total y operador
CREATE VIEW VW_LAV_ORDENES AS
SELECT
  lo.ID,
  lo.ID_CLIENTE,
  lo.FECHA_ENTRADA,
  lo.FECHA_ENTREGA,
  lo.ESTADO,
  lo.APLICA_ITBIS,
  lo.TOTAL,
  u.NOMBRECOMPLETO AS OPERADOR
FROM
  LAV_ORDEN lo
LEFT JOIN
  USUARIO u ON lo.ID_OPERADOR = u.NUMERO;

-- VISTA 2: Detalle de prendas con información del producto
CREATE VIEW VW_LAV_PRENDAS_DETALLE AS
SELECT
  lp.ID,
  lp.ID_ORDEN,
  p.CODIGO_TEXTO,
  p.DESCRIPCION AS PRODUCTO,
  lp.CANTIDAD,
  lp.PRECIO_UNITARIO,
  lp.MONTO_BASE,
  lp.MONTO_ITBIS,
  lp.TOTAL_LINEA,
  lp.ETAPA_ACTUAL
FROM
  LAV_PRENDA lp
JOIN
  INVENTARIO_PRODUCTO p ON lp.CODIGO_PRODUCTO = p.CODIGO;

-- VISTA 3: Seguimiento completo de etapas
CREATE VIEW VW_LAV_SEGUIMIENTO AS
SELECT
  h.ID,
  h.ID_PRENDA,
  p.CODIGO_BARRA,
  h.ETAPA,
  h.FECHA_HORA,
  u.NOMBRECOMPLETO AS USUARIO
FROM
  LAV_HISTORIAL h
LEFT JOIN
  LAV_PRENDA p ON h.ID_PRENDA = p.ID
LEFT JOIN
  USUARIO u ON h.USUARIO_ID = u.NUMERO;

-- ÍNDICES SUGERIDOS
CREATE INDEX IDX_LAV_ORDEN_ESTADO ON LAV_ORDEN (ESTADO);
CREATE INDEX IDX_LAV_PRENDA_ORDEN ON LAV_PRENDA (ID_ORDEN);
CREATE INDEX IDX_LAV_PRENDA_PRODUCTO ON LAV_PRENDA (CODIGO_PRODUCTO);
CREATE INDEX IDX_LAV_HISTORIAL_PRENDA ON LAV_HISTORIAL (ID_PRENDA);


CREATE TABLE LAV_PRENDA_SERVICIO (
  ID INTEGER NOT NULL,
  ID_PRENDA INTEGER NOT NULL,  -- FK a LAV_PRENDA
  ID_SERVICIO INTEGER NOT NULL,  -- FK a LAV_SERVICIO
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_PRENDA) REFERENCES LAV_PRENDA(ID),
  FOREIGN KEY (ID_SERVICIO) REFERENCES LAV_SERVICIO(ID)
);
