SET TERM ^ ;
CREATE PROCEDURE ProcGetTemplateXLS
RETURNS(
  NOMBRE_TEMPLATE VARCHAR(110) CHARACTER SET NONE,
  NOMBRE_ARCHIVO VARCHAR(110) CHARACTER SET NONE,
  SERIEID INTEGER,
  NUMEROID INTEGER,
  SECCION VARCHAR(30) CHARACTER SET NONE,
  NOMBRE_CAMPO VARCHAR(70) CHARACTER SET NONE,
  DESCRIPCION_LABEL VARCHAR(100) CHARACTER SET NONE,
  COLUMNA_NOMBRE VARCHAR(8) CHARACTER SET NONE,
  FILE_NUMERO VARCHAR(8) CHARACTER SET NONE,
  ISDETAIL SMALLINT,
  STATUS CHAR(1) CHARACTER SET NONE)
AS
BEGIN
  FOR
    SELECT 
      TEMPLATE_XLS_DOC.NOMBRE_TEMPLATE,
      TEMPLATE_XLS_MASTER.NOMBRE_ARCHIVO,
      TEMPLATE_XLS.SERIEID,
      TEMPLATE_XLS.NUMEROID,
      TEMPLATE_XLS.SECCION,
      TEMPLATE_XLS.NOMBRE_CAMPO,
      TEMPLATE_XLS.DESCRIPCION_LABEL,
      TEMPLATE_XLS.COLUMNA_NOMBRE,
      TEMPLATE_XLS.FILE_NUMERO,
      TEMPLATE_XLS.ISDETAIL,
      TEMPLATE_XLS.STATUS
    FROM
      TEMPLATE_XLS_MASTER
      INNER JOIN TEMPLATE_XLS ON (TEMPLATE_XLS_MASTER.NUMEROID = TEMPLATE_XLS.NUMEROID)
      INNER JOIN TEMPLATE_XLS_DOC ON (TEMPLATE_XLS_MASTER.IDDOC = TEMPLATE_XLS_DOC.IDDOC)
    where TEMPLATE_XLS.NOMBRE_CAMPO is not null
    and TEMPLATE_XLS.NOMBRE_CAMPO <> ''
    INTO
      :NOMBRE_TEMPLATE,
      :NOMBRE_ARCHIVO,
      :SERIEID,
      :NUMEROID,
      :SECCION,
      :NOMBRE_CAMPO,
      :DESCRIPCION_LABEL,
      :COLUMNA_NOMBRE,
      :FILE_NUMERO,
      :ISDETAIL,
      :STATUS
  DO
  BEGIN
    SUSPEND;
  END
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE ProcGetTemplateXLS TO  DIVISON;
GRANT EXECUTE
 ON PROCEDURE ProcGetTemplateXLS TO  sysdba;
