unit UDatosVentas;

interface

uses
  SysUtils, Classes, DB, IBCustomDataSet, IBUpdateSQL, IBQuery, IBTable,
  Variants, dialogs, IBStoredProc, IBSQL;

type
  TdmVentas = class(TDataModule)
    tblVentasMast: TIBDataSet;
    tblVentasDetalle: TIBDataSet;
    tblVentasMastNUMERO: TIntegerField;
    tblVentasMastFECHA: TDateTimeField;
    tblVentasMastCODIGO_CTE: TIntegerField;
    tblVentasMastOBSERVACION: TIBStringField;
    tblVentasMastMONEDA: TIBStringField;
    tblVentasMastVALOR_TOTAL_DET: TFloatField;
    tblVentasMastSTATUS: TIBStringField;
    tblVentasMastFECHA_IN: TDateTimeField;
    tblVentasMastIN_POR: TIBStringField;
    tblVentasMastFECHA_MOD: TDateTimeField;
    tblVentasMastMOD_POR: TIBStringField;
    tblVentasDetalleSERIE: TIntegerField;
    tblVentasDetalleNUMERO: TIntegerField;
    tblVentasDetalleCODIGO_BARRA: TIBStringField;
    tblVentasDetalleDESCRIPCION: TIBStringField;
    tblVentasDetallePRECIO: TFloatField;
    tblVentasDetallePORC_DESC_DET: TFloatField;
    tblVentasDetalleITBI_DET: TFloatField;
    tblVentasDetalleVALOR_SERVICIO_DET: TFloatField;
    tblVentasDetalleVALOR_TOTAL_DET: TFloatField;
    tblVentasDetalleNUM_FACTURA: TFloatField;
    tblVentasDetalleSTATUS_DET: TIBStringField;
    tblVentasDetalleFECHA_IN: TDateTimeField;
    tblVentasDetalleIN_POR: TIBStringField;
    tblVentasDetalleFECHA_MOD: TDateTimeField;
    tblVentasDetalleMOD_POR: TIBStringField;
    dsVentasDetalle: TDataSource;
    dsVentasMast: TDataSource;
    IBUpdateSQL2: TIBUpdateSQL;
    qryClientes: TIBQuery;
    dsqryClientes: TDataSource;
    qryClientesCODIGO_CTE: TIntegerField;
    qryClientesNOMBRE_CTE: TIBStringField;
    qryitbi: TIBQuery;
    dsqryitbi: TDataSource;
    tblDoc_tran_cxc: TIBTable;
    dstblDoc_tran_cxc: TDataSource;
    tblDoc_tran_cxcCODIGO: TSmallintField;
    tblDoc_tran_cxcCODIGO_ABR: TIBStringField;
    tblDoc_tran_cxcDESCRIPCION: TIBStringField;
    TblFormaPago: TIBTable;
    dsTblFormaPago: TDataSource;
    TblFormaPagoCODIGO: TSmallintField;
    TblFormaPagoDESCRIPCION: TIBStringField;
    IBUpdateSQL1: TIBUpdateSQL;
    tblVentasMastFORMA_PAGO: TSmallintField;
    qryClientesCIUDAD: TIBStringField;
    qryClientesDIRECCION_CONT: TIBStringField;
    qryClientesNOMBRE_FACTURAR: TIBStringField;
    qryClientesPAIS: TIBStringField;
    qryClientesTELEF_CONTACTO: TIBStringField;
    qryClientesFOTO: TBlobField;
    GenNumFactura: TIBSQL;
    tblVentasMastNUMERO_FACTURA: TIntegerField;
    tblVentasDetalleCANTIDAD: TFloatField;
    IBStoredProc1: TIBStoredProc;
    tblVentasMastCODIGO_VENDEDOR: TIntegerField;
    TblFormaPagoORIGEN: TSmallintField;
    tblVentasMastNUMERO_DOC_PAGO: TIBStringField;
    tblVentasDetalleCANT_REGRESO: TFloatField;
    tblVentasDetalleCANT_PROMO: TFloatField;
    tblVentasDetalleMONTO_DIETA: TFloatField;
    tblVentasDetalleMONTO_AJUSTE: TFloatField;
    qryClientesRNC_NUMERO: TIBStringField;
    tblVentasDetalleCODIGO_PROD: TIBStringField;
    qryProveedor: TIBQuery;
    IntegerField1: TIntegerField;
    IBStringField1: TIBStringField;
    IBStringField2: TIBStringField;
    IBStringField3: TIBStringField;
    IBStringField4: TIBStringField;
    IBStringField5: TIBStringField;
    IBStringField6: TIBStringField;
    IBStringField7: TIBStringField;
    tblRegServicioDet: TIBDataSet;
    tblRegServicioMaster: TIBDataSet;
    dstblRegServicioMaster: TDataSource;
    dstblRegServicioDet: TDataSource;
    tblRegServicioDetNUMERO: TIntegerField;
    tblRegServicioDetSERIE: TIntegerField;
    tblRegServicioDetFECHA: TDateTimeField;
    tblRegServicioDetCOD_SERVICIO: TIntegerField;
    tblRegServicioDetCANT: TFloatField;
    tblRegServicioDetVALOR_SERVICIO: TFloatField;
    tblRegServicioDetPORC_ITBIS: TFloatField;
    tblRegServicioDetPORC_DESC: TFloatField;
    tblRegServicioDetVALOR_ITBIS: TFloatField;
    tblRegServicioDetVALOR_DESCUENTO: TFloatField;
    tblRegServicioDetDESCRIPCION: TIBStringField;
    tblRegServicioDetSTATUS: TIBStringField;
    tblRegServicioDetIN_POR: TIBStringField;
    tblRegServicioDetFECHA_IN: TDateTimeField;
    tblRegServicioDetUPDATE_POR: TIBStringField;
    tblRegServicioDetFECHA_UPDATE: TDateTimeField;
    tblRegServicioDetCOD_USUARIO: TIntegerField;
    tblRegServicioMasterNUMERO: TIntegerField;
    tblRegServicioMasterFECHA_ENTRADA: TDateTimeField;
    tblRegServicioMasterFECHA_SALIDA: TDateTimeField;
    tblRegServicioMasterLAVADO: TSmallintField;
    tblRegServicioMasterPLANCHADO: TSmallintField;
    tblRegServicioMasterNOMBRE_CLIENTE: TIBStringField;
    tblRegServicioMasterMONTO_TOTAL: TFloatField;
    tblRegServicioMasterCOD_USUARIO: TIntegerField;
    tblRegServicioMasterSTATUS: TIBStringField;
    qryRegServMasterRep: TIBQuery;
    qryRegServMasterRepDet: TIBQuery;
    qryRegServMasterRepNUMERO: TIntegerField;
    qryRegServMasterRepFECHA_ENTRADA: TDateTimeField;
    qryRegServMasterRepFECHA_SALIDA: TDateTimeField;
    qryRegServMasterRepLAVADO: TSmallintField;
    qryRegServMasterRepPLANCHADO: TSmallintField;
    qryRegServMasterRepNOMBRE_CLIENTE: TIBStringField;
    qryRegServMasterRepMONTO_TOTAL: TFloatField;
    qryRegServMasterRepCOD_USUARIO: TIntegerField;
    qryRegServMasterRepSTATUS: TIBStringField;
    qryRegServMasterRepDetSERIE: TIntegerField;
    qryRegServMasterRepDetNUMERO: TIntegerField;
    qryRegServMasterRepDetFECHA: TDateTimeField;
    qryRegServMasterRepDetCOD_SERVICIO: TIntegerField;
    qryRegServMasterRepDetCANT: TFloatField;
    qryRegServMasterRepDetVALOR_SERVICIO: TFloatField;
    qryRegServMasterRepDetPORC_ITBIS: TFloatField;
    qryRegServMasterRepDetPORC_DESC: TFloatField;
    qryRegServMasterRepDetVALOR_ITBIS: TFloatField;
    qryRegServMasterRepDetVALOR_DESCUENTO: TFloatField;
    qryRegServMasterRepDetDESCRIPCION: TIBStringField;
    qryRegServMasterRepDetSTATUS: TIBStringField;
    qryRegServMasterRepDetIN_POR: TIBStringField;
    qryRegServMasterRepDetFECHA_IN: TDateTimeField;
    qryRegServMasterRepDetUPDATE_POR: TIBStringField;
    qryRegServMasterRepDetFECHA_UPDATE: TDateTimeField;
    qryRegServMasterRepDetCOD_USUARIO: TIntegerField;
    qryInventarioLavanderia: TIBQuery;
    qryInventarioLavanderiaCODIGO: TIntegerField;
    qryInventarioLavanderiaCODIGO_TEXTO: TIBStringField;
    qryInventarioLavanderiaFECHA: TDateTimeField;
    qryInventarioLavanderiaCODIGO_BARRA: TIBStringField;
    qryInventarioLavanderiaTIPO: TIntegerField;
    qryInventarioLavanderiaDESCRIPCION: TIBStringField;
    qryInventarioLavanderiaCANTIDAD: TFloatField;
    qryInventarioLavanderiaPRECIO: TFloatField;
    qryInventarioLavanderiaPRECIO_COMPRA: TFloatField;
    qryInventarioLavanderiaPRECIO_MINIMO: TFloatField;
    dsqryInventarioLavanderia: TDataSource;
    qryRegServMasterRepDetDESC_SERVICIO: TIBStringField;
    tblRegServicioDetPRECIO: TFloatField;
    tblRegServicioMasterMONTO_RECIBIDO: TFloatField;
    tblRegServicioMasterMONTO_DEVUELTO: TFloatField;
    qryRegServMasterRepMONTO_RECIBIDO: TFloatField;
    qryRegServMasterRepMONTO_DEVUELTO: TFloatField;
    qryRegServMasterRepDetPRECIO: TFloatField;
    ibstpProcInsVentaMast: TIBStoredProc;
    ibstpProcInsVentaDetalle: TIBStoredProc;
    qryInventarioCafeteria: TIBQuery;
    qryInventarioCafeteriaCODIGO: TIntegerField;
    qryInventarioCafeteriaCODIGO_TEXTO: TIBStringField;
    qryInventarioCafeteriaFECHA: TDateTimeField;
    qryInventarioCafeteriaCODIGO_BARRA: TIBStringField;
    qryInventarioCafeteriaTIPO: TIntegerField;
    qryInventarioCafeteriaDESCRIPCION: TIBStringField;
    qryInventarioCafeteriaCANTIDAD_REORDEN: TIntegerField;
    qryInventarioCafeteriaPRECIO_ANT: TFloatField;
    qryInventarioCafeteriaCANTIDAD: TFloatField;
    qryInventarioCafeteriaPRECIO: TFloatField;
    qryInventarioCafeteriaBLCE_CANT_ENTRADA: TFloatField;
    qryInventarioCafeteriaBLCE_CANT_SALIDA: TFloatField;
    qryInventarioCafeteriaFECHA_ULTIMA_TRN: TDateTimeField;
    qryInventarioCafeteriaSTATUS: TIBStringField;
    qryInventarioCafeteriaPORC_DESCUENTO: TFloatField;
    qryInventarioCafeteriaFOTO: TBlobField;
    qryInventarioCafeteriaPAGA_ITBI: TSmallintField;
    qryInventarioCafeteriaCODIGO_PRECIO: TIBStringField;
    qryInventarioCafeteriaUNIDAD: TFloatField;
    qryInventarioCafeteriaPRECIO_COMPRA: TFloatField;
    qryInventarioCafeteriaPRECIO_MINIMO: TFloatField;
    qryInventarioCafeteriaREFERENCIA: TIBStringField;
    qryInventarioCafeteriaFECHA_VENCIMIENTO: TDateTimeField;
    qryInventarioCafeteriaINVENTARIAR: TSmallintField;
    qryInventarioCafeteriaPRECIO_TIPO_UNIDAD: TFloatField;
    qryInventarioCafeteriaTIPO_UNIDAD: TIntegerField;
    qryInventarioCafeteriaORIGEN: TIntegerField;
    qryInventarioCafeteriaUBICACION: TIBStringField;
    qryInventarioCafeteriaMARCA: TIBStringField;
    qryInventarioCafeteriaMODELO: TIBStringField;
    qryInventarioCafeteriaIng: TIBQuery;
    qryInventarioCafeteriaIngCODIGO: TIntegerField;
    qryInventarioCafeteriaIngCODIGO_TEXTO: TIBStringField;
    qryInventarioCafeteriaIngFECHA: TDateTimeField;
    qryInventarioCafeteriaIngCODIGO_BARRA: TIBStringField;
    qryInventarioCafeteriaIngTIPO: TIntegerField;
    qryInventarioCafeteriaIngDESCRIPCION: TIBStringField;
    qryInventarioCafeteriaIngCANTIDAD_REORDEN: TIntegerField;
    qryInventarioCafeteriaIngPRECIO_ANT: TFloatField;
    qryInventarioCafeteriaIngCANTIDAD: TFloatField;
    qryInventarioCafeteriaIngPRECIO: TFloatField;
    qryInventarioCafeteriaIngBLCE_CANT_ENTRADA: TFloatField;
    qryInventarioCafeteriaIngBLCE_CANT_SALIDA: TFloatField;
    qryInventarioCafeteriaIngFECHA_ULTIMA_TRN: TDateTimeField;
    qryInventarioCafeteriaIngSTATUS: TIBStringField;
    qryInventarioCafeteriaIngPORC_DESCUENTO: TFloatField;
    qryInventarioCafeteriaIngFOTO: TBlobField;
    qryInventarioCafeteriaIngPAGA_ITBI: TSmallintField;
    qryInventarioCafeteriaIngCODIGO_PRECIO: TIBStringField;
    qryInventarioCafeteriaIngUNIDAD: TFloatField;
    qryInventarioCafeteriaIngPRECIO_COMPRA: TFloatField;
    qryInventarioCafeteriaIngPRECIO_MINIMO: TFloatField;
    qryInventarioCafeteriaIngREFERENCIA: TIBStringField;
    qryInventarioCafeteriaIngFECHA_VENCIMIENTO: TDateTimeField;
    qryInventarioCafeteriaIngINVENTARIAR: TSmallintField;
    qryInventarioCafeteriaIngPRECIO_TIPO_UNIDAD: TFloatField;
    qryInventarioCafeteriaIngTIPO_UNIDAD: TIntegerField;
    qryInventarioCafeteriaIngORIGEN: TIntegerField;
    qryInventarioCafeteriaIngUBICACION: TIBStringField;
    qryInventarioCafeteriaIngREFERENCIA_ALTERNA: TIBStringField;
    qryInventarioCafeteriaIngMARCA: TIBStringField;
    qryInventarioCafeteriaIngMODELO: TIBStringField;
    tblTransCafeteria: TIBDataSet;
    dstblTransCafeteria: TDataSource;
    tblTransCafeteriaNUMERO: TIntegerField;
    tblTransCafeteriaCODIGO_PROD: TIntegerField;
    tblTransCafeteriaCANT: TFloatField;
    tblTransCafeteriaCOD_USUARIO: TIntegerField;
    tblTransCafeteriaFECHA_IN: TDateTimeField;
    tblTransCafeteriaIN_POR: TIBStringField;
    tblTransCafeteriaSTATUS: TIBStringField;
    tblTransCafeteriaSERIE: TIntegerField;
    qryIngredienteCaf: TIBQuery;
    qryIngredienteCafSERIE: TIntegerField;
    qryIngredienteCafNUMERO: TIntegerField;
    qryIngredienteCafCODIGO_PROD: TIntegerField;
    qryIngredienteCafCANT: TIntegerField;
    qryIngredienteCafSTATUS: TIBStringField;
    qryIngredienteCafDESCRIPCION: TIBStringField;
    qryInventarioServTaller: TIBQuery;
    tblRegServicioMasterCODIGO_EMP: TIntegerField;
    qryEmpleado: TIBQuery;
    qryEmpleadoCODIGO: TIntegerField;
    qryEmpleadoCODIGO_CIA: TIntegerField;
    qryEmpleadoNOMBRE: TIBStringField;
    qryEmpleadoAPELLIDO: TIBStringField;
    qryEmpleadoCEDULA: TIBStringField;
    qryEmpleadoFOTO: TBlobField;
    qryEmpleadoPASSPORT: TIBStringField;
    qryEmpleadoCALLE: TIBStringField;
    qryEmpleadoNUM_CASA: TSmallintField;
    qryEmpleadoCIUDAD: TIBStringField;
    qryEmpleadoPAIS: TIBStringField;
    qryEmpleadoTELEF_CASA: TIBStringField;
    qryEmpleadoTELEF_OFICINA: TIBStringField;
    qryEmpleadoCELULAR: TIBStringField;
    qryEmpleadoEMAIL: TIBStringField;
    qryEmpleadoSEXO: TIBStringField;
    qryEmpleadoESTADO_CIVIL: TIBStringField;
    qryEmpleadoTELEF_REFERENCIA: TIBStringField;
    qryEmpleadoNOMBRE_REFERENCIA: TIBStringField;
    qryEmpleadoFECHA_NAC: TDateTimeField;
    qryEmpleadoNACIONALIDAD: TIBStringField;
    qryEmpleadoFECHA_ENTRADA: TDateTimeField;
    qryEmpleadoFECHA_SALIDA: TDateTimeField;
    qryEmpleadoSALARIO: TFloatField;
    qryEmpleadoTIPO_NOMINA: TSmallintField;
    qryEmpleadoTIPO_EMPLEADO: TSmallintField;
    qryEmpleadoDEPTO_EMP: TSmallintField;
    qryEmpleadoSECCION: TSmallintField;
    qryEmpleadoCARGO: TSmallintField;
    qryEmpleadoPAGA_AFP: TSmallintField;
    qryEmpleadoPAGA_TSS: TSmallintField;
    qryEmpleadoSTATUS: TIBStringField;
    qryEmpleadoFECHA_IN: TDateTimeField;
    qryEmpleadoIN_POR: TIBStringField;
    qryEmpleadoFECHA_MOD: TDateTimeField;
    qryEmpleadoMOD_POR: TIBStringField;
    qryEmpleadoLICENCIA: TIBStringField;
    qryEmpleadoFECHA_VENCE_LICENCIA: TDateTimeField;
    dsqryEmpleado: TDataSource;
    qryEmpleadoNOMBRECOMPLETO: TIBStringField;
    qryInventarioServTallerCODIGO: TIntegerField;
    qryInventarioServTallerCODIGO_TEXTO: TIBStringField;
    qryInventarioServTallerDESCRIPCION: TIBStringField;
    qryInventarioServTallerDESCRIPCIONADICIONAL: TMemoField;
    qryInventarioServTallerCANTIDAD: TFloatField;
    qryInventarioServTallerPRECIO: TFloatField;
    qryInventarioServTallerPRECIO_COMPRA: TFloatField;
    qryInventarioServTallerPRECIO_MINIMO: TFloatField;
    qryInventarioServTallerINVENTARIAR: TSmallintField;
    qryInventarioServTallerCOD_MONEDA: TIBStringField;
    dsqryInventarioServTaller: TDataSource;
    tblDespachoMaster: TIBDataSet;
    tblDespachoMasterNUMERO: TIntegerField;
    tblDespachoMasterFECHA: TDateTimeField;
    tblDespachoMasterTIPO_TRN: TSmallintField;
    tblDespachoMasterCODIGO_DESPACHADOR: TIntegerField;
    tblDespachoMasterCODIGO_EMP: TIntegerField;
    tblDespachoMasterMONTO_TOTAL: TFloatField;
    tblDespachoMasterNUM_ORDEN: TFloatField;
    tblDespachoMasterSTATUS: TIBStringField;
    tblDespachoMasterFECHA_IN: TDateTimeField;
    tblDespachoMasterIN_POR: TIBStringField;
    tblDespachoMasterFECHA_MOD: TDateTimeField;
    tblDespachoMasterMOD_POR: TIBStringField;
    tblDespachoMasterCODIGO_RUTA: TIntegerField;
    tblDespachoMasterNUM_CONDUCE: TIntegerField;
    tblDespachoMasterCODIGO_PROV: TIntegerField;
    tblDespachoMasterNCF: TIBStringField;
    tblDespachoMasterRNC_PROVEEDOR: TIBStringField;
    tblDespachoMasterINVENTARIO_ID: TIntegerField;
    tblDespachoMasterSERIE_INV_ID: TIntegerField;
    tblDespachoMasterINV_ID_ORIGEN: TIntegerField;
    tblDespachoMasterINV_ID_DESTINO: TIntegerField;
    tblDespachoMasterFORMA_PAGO: TSmallintField;
    tblDespachoMasterNUMERO_FACTURA: TIntegerField;
    tblDespachoMasterSTATUS_CNT: TIBStringField;
    tblDespachoDet: TIBDataSet;
    tblDespachoDetSERIE: TIntegerField;
    tblDespachoDetNUMERO: TIntegerField;
    tblDespachoDetTIPO_TRN: TSmallintField;
    tblDespachoDetCODIGO_PROD: TIntegerField;
    tblDespachoDetCANTIDAD: TFloatField;
    tblDespachoDetPRECIO: TFloatField;
    tblDespachoDetPORC_DESC_DET: TFloatField;
    tblDespachoDetITBI_DET: TFloatField;
    tblDespachoDetVALOR_BRUTO: TFloatField;
    tblDespachoDetVALOR_TOTAL_DET: TFloatField;
    tblDespachoDetNUM_ORDEN: TFloatField;
    tblDespachoDetSTATUS_DET: TIBStringField;
    tblDespachoDetFECHA_IN: TDateTimeField;
    tblDespachoDetIN_POR: TIBStringField;
    tblDespachoDetFECHA_MOD: TDateTimeField;
    tblDespachoDetMOD_POR: TIBStringField;
    tblDespachoDetDESCRIPCION: TIBStringField;
    tblDespachoDetRECARGA: TFloatField;
    tblDespachoDetCANT_UNIDADES: TFloatField;
    tblDespachoDetUNIDADID: TIntegerField;
    tblDespachoDetSTATUS_CNT: TIBStringField;
    tblDespachoDetMontoDescuento: TCurrencyField;
    tblDespachoDetCANTOFERTA: TIntegerField;
    QryBuscarITBIGlobal: TIBQuery;
    QryBuscarITBIGlobalGRUPO: TSmallintField;
    QryBuscarITBIGlobalFECHA_INI: TDateTimeField;
    QryBuscarITBIGlobalFECHA_FIN: TDateTimeField;
    QryBuscarITBIGlobalPORCIENTO: TFloatField;
    QryBuscarITBIGlobalOBSERVACIONES: TIBStringField;
    QryBuscarITBIGlobalSTATUS: TIBStringField;
    qryitbiFECHA_FIN: TDateTimeField;
    qryitbiFECHA_INI: TDateTimeField;
    qryitbiIDTASAITBIS: TSmallintField;
    qryitbiPORCIENTO: TFloatField;
    qryitbiOBSERVACIONES: TIBStringField;
    qryitbiSTATUS: TIBStringField;
    qryitbiSIMBOLO_TASA: TIBStringField;
    qryBuscarTasaItbis: TIBQuery;
    qryBuscarTasaItbisIDTASAITBIS: TSmallintField;
    qryBuscarTasaItbisFECHAINI: TDateTimeField;
    qryBuscarTasaItbisFECHAFIN: TDateTimeField;
    qryBuscarTasaItbisDESCRIPCION: TIBStringField;
    qryBuscarTasaItbisPORCIENTO: TFloatField;
    qryBuscarTasaItbisUSER_IN: TIntegerField;
    qryBuscarTasaItbisUSER_MOD: TIntegerField;
    qryBuscarTasaItbisIN_POR: TIBStringField;
    qryBuscarTasaItbisFECHA_IN: TDateTimeField;
    qryBuscarTasaItbisMOD_POR: TIBStringField;
    qryBuscarTasaItbisSTATUS: TIBStringField;
    qryBuscarTasaItbisFECHA_UPDATE: TDateTimeField;
    qryBuscarTasaItbisSIMBOLO_TASA: TIBStringField;
    qryTasaItbis: TIBQuery;
    qryTasaItbisIDTASAITBIS: TSmallintField;
    qryTasaItbisFECHAINI: TDateTimeField;
    qryTasaItbisFECHAFIN: TDateTimeField;
    qryTasaItbisDESCRIPCION: TIBStringField;
    qryTasaItbisPORCIENTO: TFloatField;
    qryTasaItbisUSER_IN: TIntegerField;
    qryTasaItbisUSER_MOD: TIntegerField;
    qryTasaItbisIN_POR: TIBStringField;
    qryTasaItbisFECHA_IN: TDateTimeField;
    qryTasaItbisMOD_POR: TIBStringField;
    qryTasaItbisSTATUS: TIBStringField;
    qryTasaItbisFECHA_UPDATE: TDateTimeField;
    qryTasaItbisSIMBOLO_TASA: TIBStringField;
    qryBuscarMonedaProd: TIBQuery;
    qryBuscarMonedaProdCOD_MONEDA: TIBStringField;
    tblRegServicioDetDESCRIPCIONESPECIAL: TMemoField;
    qryRegServMasterRepDetDESCRIPCIONESPECIAL: TMemoField;
    tblRegServicioMasterCODIGO_CTE: TIntegerField;
    tblRegServicioMasterNUM_TRNVENTA: TIntegerField;
    tblRegServicioMasterFECHA_ESTIMADA_ENTREGA: TDateTimeField;
    tblOrdenTrabajo: TIBDataSet;
    tblOrdenTrabajoIDORDEN: TIntegerField;
    tblOrdenTrabajoFECHA: TDateTimeField;
    tblOrdenTrabajoCOD_MONEDA: TIBStringField;
    tblOrdenTrabajoCODIGO_CTE: TIntegerField;
    tblOrdenTrabajoFECHA_ENTREGA: TDateTimeField;
    tblOrdenTrabajoNUM_ORDEN: TIntegerField;
    tblOrdenTrabajoDESC_VEHICULO: TIBStringField;
    tblOrdenTrabajoDESC_ORDEN: TMemoField;
    tblOrdenTrabajoMONTO_TOTAL: TFloatField;
    tblOrdenTrabajoMONTO_ABONO: TFloatField;
    tblOrdenTrabajoASIGNADO_A: TIntegerField;
    tblOrdenTrabajoCODIGO_USER: TIntegerField;
    tblOrdenTrabajoSTATUS: TIBStringField;
    tblOrdenTrabajoIN_POR: TIBStringField;
    tblOrdenTrabajoFECHA_IN: TDateTimeField;
    tblOrdenTrabajoMOD_POR: TIBStringField;
    tblOrdenTrabajoFECHA_MOD: TDateTimeField;
    dstblOrdenTrabajo: TDataSource;
    tblOrdenTrabajoMontoRestanteCld: TCurrencyField;
    tblOrdenTrabajoNUM_COTIZACION: TIntegerField;
    qryPrecioUnidadSurt: TIBQuery;
    qryUnidadPLSurt: TIBQuery;
    qryUnidadPLSurtIDUNIDAD: TIntegerField;
    qryUnidadPLSurtDESCRIPCION: TIBStringField;
    qryPrecioUnidadSurtIDUNIDAD: TIntegerField;
    qryPrecioUnidadSurtCOD_PRODUCTO: TIntegerField;
    qryPrecioUnidadSurtDESCRIPCION: TIBStringField;
    qryPrecioUnidadSurtPORCUTILIDAD1: TFloatField;
    qryPrecioUnidadSurtPORCUTILIDAD2: TFloatField;
    qryPrecioUnidadSurtPORCUTILIDAD3: TFloatField;
    qryPrecioUnidadSurtPORCUTILIDAD4: TFloatField;
    qryPrecioUnidadSurtPRECIOVENTA1: TFloatField;
    qryPrecioUnidadSurtPRECIOVENTA2: TFloatField;
    qryPrecioUnidadSurtPRECIOVENTA3: TFloatField;
    qryPrecioUnidadSurtPRECIOVENTA4: TFloatField;
    qryPrecioUnidadSurtCANTIDAD: TIntegerField;
    tblLineaComentario: TIBDataSet;
    tblLineaComentarioID: TSmallintField;
    tblLineaComentarioNUMERO_TRN: TIntegerField;
    tblLineaComentarioNUMLIN: TSmallintField;
    tblLineaComentarioLINEA: TIBStringField;
    tblLineaComentarioTIPO_OPE: TSmallintField;
    ibsqlInsertConduce: TIBSQL;
    qryVerProdEnConduce: TIBQuery;
    qryVerProdEnConduceCANT_EN_INV: TFloatField;
    qryVerProdEnConduceCANT_TOTAL_CONDUCE: TFloatField;
    qryVentaConduce: TIBQuery;
    qryVentaConduceMaster: TIBQuery;
    ibsqlUpdateStVtaConduce: TIBSQL;
    qryVentaConduceMasterNUMERO: TIntegerField;
    qryVentaConduceMasterFECHA: TDateTimeField;
    qryVentaConduceMasterNOMBRE_FACTURAR: TIBStringField;
    qryVentaConduceMasterVALOR_TOTAL_DET: TFloatField;
    qryVentaConduceSERIE: TIntegerField;
    qryVentaConduceNUMERO: TIntegerField;
    qryVentaConduceCODIGO_PROD: TIBStringField;
    qryVentaConduceCODIGO_BARRA: TIBStringField;
    qryVentaConduceDESCRIPCION: TIBStringField;
    qryVentaConduceCANTIDAD: TFloatField;
    qryVentaConducePRECIO: TFloatField;
    qryVentaConducePORC_DESC_DET: TFloatField;
    qryVentaConduceITBI_DET: TFloatField;
    qryVentaConduceVALOR_SERVICIO_DET: TFloatField;
    qryVentaConduceVALOR_TOTAL_DET: TFloatField;
    qryVentaConduceNUM_FACTURA: TFloatField;
    qryVentaConduceSTATUS_DET: TIBStringField;
    qryVentaConduceFECHA_IN: TDateTimeField;
    qryVentaConduceIN_POR: TIBStringField;
    qryVentaConduceFECHA_MOD: TDateTimeField;
    qryVentaConduceMOD_POR: TIBStringField;
    qryVentaConduceCANT_REGRESO: TFloatField;
    qryVentaConduceCANT_PROMO: TFloatField;
    qryVentaConduceMONTO_DIETA: TFloatField;
    qryVentaConduceMONTO_AJUSTE: TFloatField;
    qryVentaConduceSERIE_PROD: TIBStringField;
    qryVentaConduceSTATUS_CNT: TIBStringField;
    qryVentaConduceTIPO_UNIDAD: TIntegerField;
    qryVentaConduceITBIS_EXENTO: TSmallintField;
    qryVentaConduceTIPO_VENTA: TSmallintField;
    qryVentaConduceDESCRIPCIONPRODUCTO: TMemoField;
    qryVentaConduceCOD_EMPLEADO_CONDUCTOR: TFloatField;
    qryVentaConducePLACA_VEHICULO: TIBStringField;
    qryVentaConduceMONEDA: TIBStringField;
    qryVentaConduceMONTO_TASA: TFloatField;
    qryVentaConduceCAPACIDAD: TFloatField;
    qryVentaConduceCANT_VIAJES: TFloatField;
    qryVentaConduceCANT_METROS_CUBICO: TFloatField;
    qryVentaConduceFICHA_VEH: TIntegerField;
    qryVentaConduceIDZONA_ORIGEN: TIntegerField;
    qryVentaConduceIDZONA_DETALLE: TIntegerField;
    qryVentaConducePRECIO_COMPRA: TFloatField;
    qryVentaConduceCANT_CONDUCE: TFloatField;
    qryVentaConducePORC_DESC_ITEM: TFloatField;
    qryVentaConduceMONTO_DESC_ITEM: TFloatField;
    qryVentaConduceITBIS_FISCAL_DET: TFloatField;
    qryVentaConduceIDTASAITBIS: TFloatField;
    qryVentaConduceMONTOIBISRECARGO: TFloatField;
    qryVentaConduceDC_ITBIS_CLD: TFloatField;
    qryVentaConduceTC_MONTOITBISRECARGO_GLB: TFloatField;
    qryVentaConduceTC_MONTOITBISRECARGO_ITM: TFloatField;
    ibsqlCancelaStVtaConduce: TIBSQL;
    qryRepOrdenConduce: TIBQuery;
    tblDatosConduce: TIBDataSet;
    tblDatosConduceNUM_TRN: TIntegerField;
    tblDatosConduceDESPACHADO_POR: TIntegerField;
    tblDatosConduceCOD_CLIENTE: TIntegerField;
    tblDatosConduceCOD_VENDEDOR: TIntegerField;
    tblDatosConduceCOD_CHOFER: TIntegerField;
    tblDatosConduceNUM_CONDUCE: TIntegerField;
    tblDatosConduceFECHA_IN: TDateTimeField;
    tblDatosConduceIN_POR: TIBStringField;
    tblDatosConduceSTATUS: TIBStringField;
    qryVentaFacturaDet: TIBQuery;
    qryVentaFacturaDetDESC_TIPO_NCF: TIBStringField;
    qryVentaFacturaDetSERIE: TIntegerField;
    qryVentaFacturaDetCODIGO_PROD: TIBStringField;
    qryVentaFacturaDetDESCRIPCION: TIBStringField;
    qryVentaFacturaDetCANTIDAD: TFloatField;
    qryVentaFacturaDetPRECIO: TFloatField;
    qryVentaFacturaDetPORC_DESC_DET: TFloatField;
    qryVentaFacturaDetITBI_DET: TFloatField;
    qryVentaFacturaDetVALOR_SERVICIO_DET: TFloatField;
    qryVentaFacturaDetVALOR_TOTAL_DET: TFloatField;
    qryVentaFacturaDetNUMERO_FACTURA: TIntegerField;
    qryVentaFacturaDetSTATUS_DET: TIBStringField;
    qryVentaFacturaDetSERIE_NCF_ASIGNADO: TIntegerField;
    qryVentaFacturaDetNUMERO_NCF: TIBStringField;
    qryVentaFacturaDetMONTO_DESCUENTO: TFloatField;
    qryVentaFacturaDetNUMERO: TIntegerField;
    qryVentaFacturaDetCODIGO_BARRA: TIBStringField;
    qryVentaFacturaDetNUM_FACTURA: TFloatField;
    qryVentaFacturaDetFECHA_IN: TDateTimeField;
    qryVentaFacturaDetIN_POR: TIBStringField;
    qryVentaFacturaDetFECHA_MOD: TDateTimeField;
    qryVentaFacturaDetMOD_POR: TIBStringField;
    qryVentaFacturaDetCANT_REGRESO: TFloatField;
    qryVentaFacturaDetCANT_PROMO: TFloatField;
    qryVentaFacturaDetMONTO_DIETA: TFloatField;
    qryVentaFacturaDetMONTO_AJUSTE: TFloatField;
    qryVentaFacturaDetSERIE_PROD: TIBStringField;
    qryVentaFacturaDetSTATUS_CNT: TIBStringField;
    qryVentaFacturaDetTIPO_UNIDAD: TIntegerField;
    qryVentaFacturaDetITBIS_EXENTO: TSmallintField;
    qryVentaFacturaDetTIPO_VENTA: TSmallintField;
    qryVentaFacturaDetDESCRIPCIONPRODUCTO: TMemoField;
    qryVentaFacturaDetPRECIO_COMPRA: TFloatField;
    qryVentaFacturaDetCANT_CONDUCE: TFloatField;
    qryVentaFacturaDetPORC_DESC_ITEM: TFloatField;
    qryVentaFacturaDetMONTO_DESC_ITEM: TFloatField;
    qryVentaFacturaDetCANT_VIAJES: TFloatField;
    qryVentaFacturaDetDESCUNIDADMEDIDA: TIBStringField;
    qryVentaFacturaDetLTIPO_UNIDAD: TIBStringField;
    qryVentaFacturaDetCANTXUNIDAD: TIntegerField;
    qryVentaFacturaDetREFERENCIA: TIBStringField;
    ibsqlUpdate: TIBSQL;
    tblVentasMastCIA_KEY: TIntegerField;
    tblVentasMastCOD_USR_CAJA: TIntegerField;
    tblVentaVocados: TIBDataSet;
    dstblVentaVocados: TDataSource;
    tblVentaVocadosNUMERO_TRN: TIntegerField;
    tblVentaVocadosCOD_PRODUCTO: TIntegerField;
    tblVentaVocadosDESCRIPCION: TIBStringField;
    tblVentaVocadosPRECIO: TFloatField;
    tblVentaVocadosCOD_SUBCLIENTE: TIntegerField;
    qryInv: TIBQuery;
    qryVentaVocados: TIBQuery;
    qryVentaVocadosNUMERO_TRN: TIntegerField;
    qryVentaVocadosCOD_PRODUCTO: TIntegerField;
    qryVentaVocadosDESCRIPCION: TIBStringField;
    qryVentaVocadosPRECIO: TFloatField;
    qryVentaVocadosCOD_SUBCLIENTE: TIntegerField;
    qryVentaVocadosNOMBRE_FACTURAR: TIBStringField;
    qryVentaVocadosDIRECCION_CONT: TIBStringField;
    tblVentaVocadosPAGA_PORC_ITBIS: TFloatField;
    qryVentaVocadosPAGA_PORC_ITBIS: TFloatField;
    tblVentaVocadosNOMBRESUBCLIENTE: TIBStringField;
    tblVentaVocadosDIRECCIONSUBCTE: TIBStringField;
    qryVentaVocadosNOMBRESUBCLIENTE: TIBStringField;
    qryVentaVocadosDIRECCIONSUBCTE: TIBStringField;
    qryitbiPAGA_ITBI: TSmallintField;
    tblVtaMast: TIBDataSet;
    tblVtaMastNUMERO: TIntegerField;
    tblVtaMastFECHA: TDateTimeField;
    tblVtaMastCIA_KEY: TIntegerField;
    tblVtaMastCODIGO_CTE: TIntegerField;
    tblVtaMastCODIGO_VENDEDOR: TIntegerField;
    tblVtaMastFORMA_PAGO: TSmallintField;
    tblVtaMastOBSERVACION: TIBStringField;
    tblVtaMastMONEDA: TIBStringField;
    tblVtaMastVALOR_TOTAL_DET: TFloatField;
    tblVtaMastSTATUS: TIBStringField;
    tblVtaMastFECHA_IN: TDateTimeField;
    tblVtaMastIN_POR: TIBStringField;
    tblVtaMastFECHA_MOD: TDateTimeField;
    tblVtaMastMOD_POR: TIBStringField;
    tblVtaMastNUMERO_FACTURA: TIntegerField;
    tblVtaMastNUMERO_DOC_PAGO: TIBStringField;
    tblVtaMastSERIE_NCF_ASIGNADO: TIntegerField;
    tblVtaMastMONTO_BRUTO: TFloatField;
    tblVtaMastPORC_DESCUENTO: TIntegerField;
    tblVtaMastMONTO_DESCUENTO: TFloatField;
    tblVtaMastMONTO_INICIAL: TFloatField;
    tblVtaMastNOMBRE_CLIENTE_GENERAL: TIBStringField;
    tblVtaMastMONTO_PAGADO: TFloatField;
    tblVtaMastMONTO_CAMBIO: TFloatField;
    tblVtaMastMONTO_TOTAL_ITBIS: TFloatField;
    tblVtaMastMONTODESCGASTOSADMIN: TFloatField;
    tblVtaMastMONTODESCITBISGASTOSADMIN: TFloatField;
    tblVtaMastMONTODESCTRANSP: TFloatField;
    tblVtaMastMONTODESCDIRTECNICA: TFloatField;
    tblVtaMastMONTODESCITBISDIRTECNICA: TFloatField;
    tblVtaMastMONTODESCIMPREVISTO: TFloatField;
    tblVtaMastMONTODESCITBISIMPREVISTO: TFloatField;
    tblVtaMastDESC_MONTO_COMBUSTIBLE: TFloatField;
    tblVtaMastDESC_MONTO_PRESTAMO: TFloatField;
    tblVtaMastDESC_MONTO_SINDICATO: TFloatField;
    tblVtaMastDESC_IMP_SOBRE_RENTA: TFloatField;
    tblVtaMastDESC_OTROS: TFloatField;
    tblVtaMastPORC_DESC_SINDICATO: TIBBCDField;
    tblVtaMastPORC_DESC_IMP_SOBRE_RENTA: TIBBCDField;
    tblVtaMastDESC_RUTA: TFloatField;
    tblVtaMastOTROS_DESCUENTOS_2: TFloatField;
    tblVtaMastOTROS_DESCUENTOS_3: TFloatField;
    tblVtaMastMONTO_DESC_CHOFER: TFloatField;
    tblVtaMastTIPO_VENTA: TSmallintField;
    tblVtaMastCOMENTARIO: TIBStringField;
    tblVtaMastCOTIZACION_ORIGEN: TIntegerField;
    tblVtaMastREFERENCIACTE: TIBStringField;
    tblVtaMastMONTO_RECARGO: TFloatField;
    tblVtaMastTIPONCFIFISCAL: TIntegerField;
    tblVtaMastMONTO_EXONERADO_ITBIS: TFloatField;
    tblVtaMastNIF_IMPRESO: TSmallintField;
    tblVtaMastIDRETENCION: TIntegerField;
    tblVtaMastPORCPROPINALEGAL: TFloatField;
    tblVtaMastPROPINA: TFloatField;
    tblVtaMastPROPINALEGAL: TFloatField;
    tblVtaMastTICKET_ID: TIntegerField;
    tblVtaMastSUB_TOTALITBIS: TFloatField;
    tblVtaMastCOD_USR_CAJA: TIntegerField;
    tblVtaMastCOD_SUBCLIENTE: TIntegerField;
    qryVentaConduceMasterSTATUSMASTER: TIBStringField;
    qryVentaConduceMasterSTATUS_DET: TIBStringField;
    qryRepOrdenConduceNUMERO: TIntegerField;
    qryRepOrdenConduceNOMBRE_FACTURAR: TIBStringField;
    qryRepOrdenConduceNOMBREVENDEDOR: TIBStringField;
    qryRepOrdenConduceFECHA: TDateTimeField;
    qryRepOrdenConduceCOMENTARIO: TIBStringField;
    qryRepOrdenConduceNUM_FACT_CLD: TIBStringField;
    qryRepOrdenConduceDESPACHADOPOR: TIBStringField;
    qryRepOrdenConduceCHOFER: TIBStringField;
    qryRepOrdenConduceNUM_TRN: TIntegerField;
    qryRepOrdenConduceDESPACHADO_POR: TIntegerField;
    qryRepOrdenConduceCOD_CLIENTE: TIntegerField;
    qryRepOrdenConduceCOD_VENDEDOR: TIntegerField;
    qryRepOrdenConduceCOD_CHOFER: TIntegerField;
    qryRepOrdenConduceNUM_CONDUCE: TIntegerField;
    qryRepOrdenConduceFECHA_IN: TDateTimeField;
    qryRepOrdenConduceIN_POR: TIBStringField;
    qryRepOrdenConduceSTATUS: TIBStringField;
    qryRepOrdenConduceDESC_CIUDAD: TIBStringField;
    qryRepOrdenConduceDESC_SECTOR: TIBStringField;
    qryRepOrdenConduceDIRECCION_CONT: TIBStringField;
    tblConduceDet: TIBDataSet;
    tblConduceDetSERIE: TIntegerField;
    tblConduceDetNUMERO: TIntegerField;
    tblConduceDetCODIGO_PROD: TIBStringField;
    tblConduceDetCODIGO_BARRA: TIBStringField;
    tblConduceDetDESCRIPCION: TIBStringField;
    tblConduceDetCANTIDAD: TFloatField;
    tblConduceDetPRECIO: TFloatField;
    tblConduceDetPORC_DESC_DET: TFloatField;
    tblConduceDetITBI_DET: TFloatField;
    tblConduceDetVALOR_SERVICIO_DET: TFloatField;
    tblConduceDetVALOR_TOTAL_DET: TFloatField;
    tblConduceDetNUM_FACTURA: TFloatField;
    tblConduceDetSTATUS_DET: TIBStringField;
    tblConduceDetFECHA_IN: TDateTimeField;
    tblConduceDetIN_POR: TIBStringField;
    tblConduceDetFECHA_MOD: TDateTimeField;
    tblConduceDetMOD_POR: TIBStringField;
    tblConduceDetCANT_REGRESO: TFloatField;
    tblConduceDetCANT_PROMO: TFloatField;
    tblConduceDetMONTO_DIETA: TFloatField;
    tblConduceDetMONTO_AJUSTE: TFloatField;
    tblConduceDetSERIE_PROD: TIBStringField;
    tblConduceDetSTATUS_CNT: TIBStringField;
    tblConduceDetTIPO_UNIDAD: TIntegerField;
    tblConduceDetITBIS_EXENTO: TSmallintField;
    tblConduceDetTIPO_VENTA: TSmallintField;
    tblConduceDetDESCRIPCIONPRODUCTO: TMemoField;
    tblConduceDetCOD_EMPLEADO_CONDUCTOR: TFloatField;
    tblConduceDetPLACA_VEHICULO: TIBStringField;
    tblConduceDetMONEDA: TIBStringField;
    tblConduceDetMONTO_TASA: TFloatField;
    tblConduceDetCAPACIDAD: TFloatField;
    tblConduceDetCANT_VIAJES: TFloatField;
    tblConduceDetCANT_METROS_CUBICO: TFloatField;
    tblConduceDetFICHA_VEH: TIntegerField;
    tblConduceDetIDZONA_ORIGEN: TIntegerField;
    tblConduceDetIDZONA_DETALLE: TIntegerField;
    tblConduceDetPRECIO_COMPRA: TFloatField;
    tblConduceDetCANT_CONDUCE: TFloatField;
    tblConduceDetPORC_DESC_ITEM: TFloatField;
    tblConduceDetMONTO_DESC_ITEM: TFloatField;
    tblConduceDetITBIS_FISCAL_DET: TFloatField;
    tblConduceDetIDTASAITBIS: TFloatField;
    tblConduceDetMONTOIBISRECARGO: TFloatField;
    tblConduceDetDC_ITBIS_CLD: TFloatField;
    tblConduceDetTC_MONTOITBISRECARGO_GLB: TFloatField;
    tblConduceDetTC_MONTOITBISRECARGO_ITM: TFloatField;
    tblVentasDet: TIBDataSet;
    tblVentasDetSERIE: TIntegerField;
    tblVentasDetNUMERO: TIntegerField;
    tblVentasDetCODIGO_PROD: TIBStringField;
    tblVentasDetCODIGO_BARRA: TIBStringField;
    tblVentasDetDESCRIPCION: TIBStringField;
    tblVentasDetCANTIDAD: TFloatField;
    tblVentasDetPRECIO: TFloatField;
    tblVentasDetPORC_DESC_DET: TFloatField;
    tblVentasDetITBI_DET: TFloatField;
    tblVentasDetVALOR_SERVICIO_DET: TFloatField;
    tblVentasDetVALOR_TOTAL_DET: TFloatField;
    tblVentasDetNUM_FACTURA: TFloatField;
    tblVentasDetSTATUS_DET: TIBStringField;
    tblVentasDetFECHA_IN: TDateTimeField;
    tblVentasDetIN_POR: TIBStringField;
    tblVentasDetFECHA_MOD: TDateTimeField;
    tblVentasDetMOD_POR: TIBStringField;
    tblVentasDetCANT_REGRESO: TFloatField;
    tblVentasDetCANT_PROMO: TFloatField;
    tblVentasDetMONTO_DIETA: TFloatField;
    tblVentasDetMONTO_AJUSTE: TFloatField;
    tblVentasDetSERIE_PROD: TIBStringField;
    tblVentasDetSTATUS_CNT: TIBStringField;
    tblVentasDetTIPO_UNIDAD: TIntegerField;
    tblVentasDetITBIS_EXENTO: TSmallintField;
    tblVentasDetTIPO_VENTA: TSmallintField;
    tblVentasDetDESCRIPCIONPRODUCTO: TMemoField;
    tblVentasDetCOD_EMPLEADO_CONDUCTOR: TFloatField;
    tblVentasDetPLACA_VEHICULO: TIBStringField;
    tblVentasDetMONEDA: TIBStringField;
    tblVentasDetMONTO_TASA: TFloatField;
    tblVentasDetCAPACIDAD: TFloatField;
    tblVentasDetCANT_VIAJES: TFloatField;
    tblVentasDetCANT_METROS_CUBICO: TFloatField;
    tblVentasDetFICHA_VEH: TIntegerField;
    tblVentasDetIDZONA_ORIGEN: TIntegerField;
    tblVentasDetIDZONA_DETALLE: TIntegerField;
    tblVentasDetPRECIO_COMPRA: TFloatField;
    tblVentasDetCANT_CONDUCE: TFloatField;
    tblVentasDetPORC_DESC_ITEM: TFloatField;
    tblVentasDetMONTO_DESC_ITEM: TFloatField;
    tblVentasDetITBIS_FISCAL_DET: TFloatField;
    tblVentasDetIDTASAITBIS: TFloatField;
    tblVentasDetMONTOIBISRECARGO: TFloatField;
    tblVentasDetDC_ITBIS_CLD: TFloatField;
    tblVentasDetTC_MONTOITBISRECARGO_GLB: TFloatField;
    tblVentasDetTC_MONTOITBISRECARGO_ITM: TFloatField;
    tblDatosConduceNUM_CONDUCE_CTE: TIntegerField;
    tblDatosConduceFICHA_VEH: TIntegerField;
    qryEmpleadoDESC_CARGO: TIBStringField;
    qryDetVtaXUsr: TIBQuery;
    qryDetVtaXUsrNUMERO: TIntegerField;
    qryDetVtaXUsrSERIE: TIntegerField;
    qryDetVtaXUsrFECHA: TDateTimeField;
    qryDetVtaXUsrCOD_USR_CAJA: TIntegerField;
    qryDetVtaXUsrNOMBRECOMPLETO: TIBStringField;
    qryDetVtaXUsrCODIGO_PROD: TIBStringField;
    qryDetVtaXUsrDESCRIPCION: TIBStringField;
    qryDetVtaXUsrDESC_UNIDAD: TIBStringField;
    qryDetVtaXUsrCOSTO: TFloatField;
    qryDetVtaXUsrP1_INV: TFloatField;
    qryDetVtaXUsrP2_INV: TFloatField;
    qryDetVtaXUsrP3_INV: TFloatField;
    qryDetVtaXUsrP4_INV: TFloatField;
    qryDetVtaXUsrCANTIDAD: TFloatField;
    qryDetVtaXUsrPRECIOVTA: TFloatField;
    qryDetVtaXUsrVALOR_SERVICIO_DET: TFloatField;
    qryDetVtaXUsrITBI_DET: TFloatField;
    qryDetVtaXUsrMONTO_TOTAL: TFloatField;
    qryDetVtaXUsrIN_POR: TIBStringField;
    qryDetVtaXUsrFECHA_IN: TDateTimeField;
    qryDetVtaXUsrMOD_POR: TIBStringField;
    qryDetVtaXUsrFECHA_MOD: TDateTimeField;
    tblVentasARS: TIBDataSet;
    tblVentasARSNUMERO: TIntegerField;
    tblVentasARSNUMERO_TRN: TIntegerField;
    tblVentasARSIDARS: TIntegerField;
    tblVentasARSNOMBRE_MEDICO: TIBStringField;
    tblVentasARSNUM_AUTORIZACION: TIBStringField;
    tblVentasARSCONTACTO: TIBStringField;
    tblVentasARSDIRECCION: TMemoField;
    tblVentasARSESPECIALIDAD: TIBStringField;
    tblVentasARSDIAGNOSTICO: TMemoField;
    tblVentasARSMONTO_COBERTURA: TFloatField;
    tblVentasARSEXEQUATUR: TIBStringField;
    tblVentasARSSTATUS: TIBStringField;
    tblVentasARSFECHA_IN: TDateTimeField;
    tblVentasARSFECHA_UPDATE: TDateTimeField;
    tblVentasARSIN_POR: TIBStringField;
    tblVentasARSUPDATE_POR: TIBStringField;
    tblVentasARSAFILIADO: TIBStringField;
    tblVentasARSFECHA: TDateTimeField;
    tblVentasARSPAGO_AFILIADO: TFloatField;
    tblVentasARSMONTO_RECLAMADO: TFloatField;
    tblVentasARSPORC_COBERTURA: TFloatField;
    tblVentasDetCODIGO_VENDEDOR: TIntegerField;
    qryNIFCtrlConT: TIBQuery;
    qryInvCategoria: TIBQuery;
    qryInvCategoriaCODCATEGORIA: TIntegerField;
    qryInvCategoriaDESCRIPCION: TIBStringField;
    qryDatosVehPolizas: TIBQuery;
    qryDatosVehPolizasNUMERO: TIntegerField;
    qryDatosVehPolizasCODIGO_CTE: TIntegerField;
    qryDatosVehPolizasTIPO_AFILIADO: TSmallintField;
    qryDatosVehPolizasPLACA: TIBStringField;
    qryDatosVehPolizasIDMARCA: TIntegerField;
    qryDatosVehPolizasMODELO: TIBStringField;
    qryDatosVehPolizasANO_VEH: TIntegerField;
    qryDatosVehPolizasFECHA_VENCE_SEGURO: TDateTimeField;
    qryDatosVehPolizasTIPO_SEGURO: TSmallintField;
    qryDatosVehPolizasCIA_SEGURO: TIBStringField;
    qryDatosVehPolizasEMPRESA_LABORA: TIBStringField;
    qryDatosVehPolizasFECHA_IN: TDateTimeField;
    qryDatosVehPolizasIN_POR: TIBStringField;
    qryDatosVehPolizasCODIGO_DEALER: TIntegerField;
    qryDatosVehPolizasCODIGO_AGENCIA: TIntegerField;
    qryDatosVehPolizasCOLOR: TIBStringField;
    qryDatosVehPolizasNUM_CERTIFICADO: TIntegerField;
    qryDatosVehPolizasCHASSIS: TIBStringField;
    qryDatosVehPolizasNUMPOL: TIntegerField;
    qryDatosVehPolizasSTATUSCXC: TIBStringField;
    ibstpProc_InserKardexDet: TIBStoredProc;
    qryInventarioProduccion_base: TIBQuery;
    qryInventarioCafeteria_base: TIBQuery;
    qryRevisionVentas: TIBQuery;
    qryRevisionVentasSERIE: TIntegerField;
    qryRevisionVentasNUMERO: TIntegerField;
    qryRevisionVentasFECHA: TDateTimeField;
    qryRevisionVentasCODIGO_CTE: TIntegerField;
    qryRevisionVentasNOMBRECLIENTE: TIBStringField;
    qryRevisionVentasCODIGO_PROD: TIBStringField;
    qryRevisionVentasDESCRIPCION: TIBStringField;
    qryRevisionVentasCANTIDAD: TFloatField;
    qryRevisionVentasPRECIO: TFloatField;
    qryRevisionVentasVALOR_SERVICIO_DET: TFloatField;
    qryRevisionVentasPORC_DESC_DET: TFloatField;
    qryRevisionVentasITBI_DET: TFloatField;
    qryRevisionVentasDC_ITBIS_CLD: TFloatField;
    qryRevisionVentasITBIVERIFICADO: TFloatField;
    qryRevisionVentasPORCTBIS: TFloatField;
    qryRegServMasterRepCODIGO_EMP: TIntegerField;
    qryRegServMasterRepCODIGO_CTE: TIntegerField;
    qryRegServMasterRepNUM_TRNVENTA: TIntegerField;
    qryRegServMasterRepFECHA_ESTIMADA_ENTREGA: TDateTimeField;
    qryRegServMasterRepNUM_ORDEN_TRABAJO: TFloatField;
    qryPrecioMaxInv: TIBQuery;
    qryPrecioMaxInvPRECIOMAX: TFloatField;
    tblVtaMastIDDGII_MOTIVO_NCR: TSmallintField;
    tblncfasignado: TIBDataSet;
    tblncfasignadoSERIE: TIntegerField;
    tblncfasignadoTIPO_NCF: TIBStringField;
    tblncfasignadoNUMERO_NCF: TIBStringField;
    tblncfasignadoFECHA: TDateTimeField;
    tblncfasignadoCODIGO_CTE: TIntegerField;
    tblncfasignadoNOMBRE_COMPLETO: TIBStringField;
    tblncfasignadoCEDULA: TIBStringField;
    tblncfasignadoDIRECCION: TIBStringField;
    tblncfasignadoCIUDAD: TIBStringField;
    tblncfasignadoMONTO: TFloatField;
    tblncfasignadoSTATUS: TIBStringField;
    tblncfasignadoCODIGO_USUARIO: TIntegerField;
    tblncfasignadoFECHA_INSERT: TDateTimeField;
    tblncfasignadoFECHA_UPDATE: TDateTimeField;
    tblncfasignadoCODIGO_USUARIO_UPD: TIntegerField;
    tblncfasignadoECF: TIBStringField;
    tblncfasignadoNUMERO_NCF_REFERENCIA: TIBStringField;
    procedure tblVentasDetalleBeforePost(DataSet: TDataSet);
    procedure tblVentasMastAfterScroll(DataSet: TDataSet);
    procedure tblVentasMastAfterInsert(DataSet: TDataSet);
    procedure tblRegServicioMasterAfterScroll(DataSet: TDataSet);
    procedure qryRegServMasterRepAfterScroll(DataSet: TDataSet);
    procedure tblDespachoMasterAfterScroll(DataSet: TDataSet);
    procedure tblDespachoDetCalcFields(DataSet: TDataSet);
    procedure tblDespachoDetAfterScroll(DataSet: TDataSet);
    procedure tblOrdenTrabajoCalcFields(DataSet: TDataSet);
    procedure tblOrdenTrabajoFilterRecord(DataSet: TDataSet;
      var Accept: Boolean);
    procedure qryVentaConduceMasterBeforeScroll(DataSet: TDataSet);
    procedure qryVentaConduceMasterAfterScroll(DataSet: TDataSet);
    procedure qryRepOrdenConduceAfterScroll(DataSet: TDataSet);
    procedure tblDespachoDetFilterRecord(DataSet: TDataSet;
      var Accept: Boolean);
  private
    { Private declarations }
    function GeneraNumFactura:integer;
  public
    { Public declarations }
    strFilterIsInt:boolean;
    strFilerFName:string ;
    strFilterValue:string ;
    xcodProd : integer;
    Procedure Proc_InsertarKardexDet(
    CIA_KEY : integer;
    TIPO : integer;
    TIPO_OPE :integer;
    FECHA_TRN :TDateTime;
    CODIGO_PRODUCTO :integer;
    cant : Currency;
    COSTO_PRODUCTO :real;
    PRECIO_VENTA :real;
    CODIGO_USUARIO :integer;
    NUMERO_TRN_VTA: integer;
    STATUS :string; area:string);
  end;

var
  dmVentas: TdmVentas;

implementation

uses UDatModConectar, UDatModInventario, UDatModFactura, UGlobal;

{$R *.dfm}

procedure TdmVentas.tblVentasDetalleBeforePost(DataSet: TDataSet);
begin
  if tblVentasMast.State in [dsInsert] then
  tblVentasMast.Post;
end;

procedure TdmVentas.tblVentasMastAfterScroll(DataSet: TDataSet);
begin
  if tblVentasDetalle.State In [dsInactive, dsBrowse] then
  begin
    tblVentasDetalle.Close;
    tblVentasDetalle.Params[0].Value:= tblVentasMastNUMERO.Value;
    tblVentasDetalle.Open;
  end;
end;

function TdmVentas.GeneraNumFactura: integer;
begin
  dmVentas.GenNumFactura.ExecQuery;
  if dmVentas.GenNumFactura.Open then
  try
    Result:=dmVentas.GenNumFactura.Fields[0].AsInteger;
  finally
  dmventas.GenNumFactura.Close;
  end;
end;

procedure TdmVentas.tblVentasMastAfterInsert(DataSet: TDataSet);
begin
  dmVentas.tblVentasMastnumero_factura.Value :=GeneraNumFactura;//funcion
end;

procedure TdmVentas.tblRegServicioMasterAfterScroll(DataSet: TDataSet);
begin
  if tblRegServicioDet.State In [dsInsert, dsEdit] Then Exit;
  tblRegServicioDet.Close;
  tblRegServicioDet.Params[0].Value := tblRegServicioMasterNUMERO.Value;
  tblRegServicioDet.Open;
end;

procedure TdmVentas.qryRegServMasterRepAfterScroll(DataSet: TDataSet);
begin
  qryRegServMasterRepDet.Close;
  qryRegServMasterRepDet.Params[0].Value:= qryRegServMasterRepNUMERO.Value;
  qryRegServMasterRepDet.Open;
end;

procedure TdmVentas.tblDespachoMasterAfterScroll(DataSet: TDataSet);
begin
  tblDespachoDet.Close;
  tblDespachoDet.Params[0].Value:= tblDespachoMasterNUMERO.Value;
  tblDespachoDet.Open;
end;

procedure TdmVentas.tblDespachoDetCalcFields(DataSet: TDataSet);
begin
  tblDespachoDetMontoDescuento.Value:=
  tblDespachoDetVALOR_BRUTO.Value * (tblDespachoDetPORC_DESC_DET.Value/100);
end;

procedure TdmVentas.tblDespachoDetAfterScroll(DataSet: TDataSet);
begin
  if dmInventario.tblInventarioProd.State = dsBrowse then
  dmInventario.tblInventarioProd.Locate('CODIGO', tblDespachoDetCODIGO_PROD.Value,[]);
end;

procedure TdmVentas.tblOrdenTrabajoCalcFields(DataSet: TDataSet);
begin
  if (not tblOrdenTrabajoMONTO_ABONO.IsNull) then
  tblOrdenTrabajoMontoRestanteCld.Value:=
  tblOrdenTrabajoMONTO_TOTAL.Value -
  tblOrdenTrabajoMONTO_ABONO.Value
  else
  tblOrdenTrabajoMontoRestanteCld.Value:=
  tblOrdenTrabajoMONTO_TOTAL.Value;
end;

procedure TdmVentas.tblOrdenTrabajoFilterRecord(DataSet: TDataSet;
  var Accept: Boolean);
begin
  if not strFilterIsInt then
  Accept:=Dataset[strFilerFName] = strFilterValue
  else
  Accept:=Dataset[strFilerFName] = StrToInt(strFilterValue);
end;

procedure TdmVentas.qryVentaConduceMasterBeforeScroll(DataSet: TDataSet);
begin
    //qryVentaConduceMaster
end;

procedure TdmVentas.qryVentaConduceMasterAfterScroll(DataSet: TDataSet);
begin
  qryVentaConduce.Close;
  qryVentaConduce.Params[0].Value:= qryVentaConduceMasterNUMERO.Value;
  qryVentaConduce.Open;
end;

procedure TdmVentas.qryRepOrdenConduceAfterScroll(DataSet: TDataSet);
begin
  qryVentaFacturaDet.Close;
  qryVentaFacturaDet.Params[0].Value := dmVentas.qryRepOrdenConduceNUM_TRN.Value; //qryVentaFacturaNUMERO.Value;
  qryVentaFacturaDet.Open;

  dmFactura.qryVentaFacturaDet.Close;
  dmFactura.qryVentaFacturaDet.Params[0].Value:= dmVentas.qryRepOrdenConduceNUM_TRN.Value;
  dmFactura.qryVentaFacturaDet.Open;
end;

procedure TdmVentas.Proc_InsertarKardexDet(
    CIA_KEY : integer;
    TIPO : integer;
    TIPO_OPE :integer;
    FECHA_TRN :TDateTime;
    CODIGO_PRODUCTO :integer;
    cant : Currency;
    COSTO_PRODUCTO :real;
    PRECIO_VENTA :real;
    CODIGO_USUARIO :integer;
    NUMERO_TRN_VTA: integer;
    STATUS :string; area:string);
begin
  ibstpProc_InserKardexDet.Params[0].Value := cia_key;
  ibstpProc_InserKardexDet.Params[1].Value := tipo;
  ibstpProc_InserKardexDet.Params[2].Value := tipo_ope;
  ibstpProc_InserKardexDet.Params[3].Value := ExtraerFecha(fecha_trn);
  ibstpProc_InserKardexDet.Params[4].Value := Codigo_Producto;
  ibstpProc_InserKardexDet.Params[5].Value := Cant;
  ibstpProc_InserKardexDet.Params[6].Value := costo_producto;
  ibstpProc_InserKardexDet.Params[7].Value := precio_venta;
  ibstpProc_InserKardexDet.Params[8].Value := codigo_usuario;
  ibstpProc_InserKardexDet.Params[9].Value := numero_trn_vta;
  ibstpProc_InserKardexDet.Params[10].Value:= status;
  ibstpProc_InserKardexDet.Params[11].Value:= now;
  ibstpProc_InserKardexDet.Params[12].Value:= strusername;
  ibstpProc_InserKardexDet.Params[13].Value:= null;
  ibstpProc_InserKardexDet.Params[14].Value:= null;
  ibstpProc_InserKardexDet.Params[15].Value:= area;
  ibstpProc_InserKardexDet.ExecProc;

  if not ibstpProc_InserKardexDet.Transaction.InTransaction then
  ibstpProc_InserKardexDet.Transaction.StartTransaction;
  try
    ibstpProc_InserKardexDet.Transaction.CommitRetaining;
  except
  ibstpProc_InserKardexDet.Transaction.RollbackRetaining;
  end;
end;

procedure TdmVentas.tblDespachoDetFilterRecord(DataSet: TDataSet;
  var Accept: Boolean);
begin
  Accept:= DataSet['CODIGO_PROD'] = xcodProd;
end;

end.
