CREATE GENERATOR GEN_LCOMENTARIO_ID;

SET TERM !! ;
CREATE TRIGGER LCOMENTARIO_BI FOR LCOMENTARIO
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_LCOMENTARIO_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_LCOMENTARIO_ID, 0);
    if (tmp < new.ID) then
      tmp = GEN_ID(GEN_LCOMENTARIO_ID, new.ID-tmp);
  END
END!!
SET TERM ; !!
