SET AUTODDL ON;

DROP VIEW VIEW_VENTAS_DET;

/**************** DROPPING COMPLETE ***************/

CREATE VIEW VIEW_VENTAS_DET (SERIE, NUMERO, CODIGO_PROD, CODIGO_BARRA, 
DESCRIPCION, CANTIDAD, PRECIO, PORC_DESC_DET, ITBI_DET, VALOR_SERVICIO_DET, 
VALOR_TOTAL_DET, NUM_FACTURA, STATUS_DET, CANT_REGRESO, CANT_PROMO, 
MONTO_DIETA, MONTO_AJUSTE, SERIE_PROD, STATUS_CNT, TIPO_VENTA, 
DESC_TIPOUNIDAD, CX_TIPOUNIDAD, IDUNIDAD, descripcionproducto)
AS   
SELECT DISTINCT
  VENTAS_DET.SERIE,
  VENTAS_DET.NUMERO,
  VENTAS_DET.CODIGO_PROD,
  VENTAS_DET.CODIGO_BARRA,
  VENTAS_DET.DESCRIPCION,
  VENTAS_DET.CANTIDAD,
  VENTAS_DET.PRECIO,
  VENTAS_DET.PORC_DESC_DET,
  VENTAS_DET.ITBI_DET,
  VENTAS_DET.VALOR_SERVICIO_DET,
  VENTAS_DET.VALOR_TOTAL_DET,
  VENTAS_DET.NUM_FACTURA,
  VENTAS_DET.STATUS_DET,
  VENTAS_DET.CANT_REGRESO,
  VENTAS_DET.CANT_PROMO,
  VENTAS_DET.MONTO_DIETA,
  VENTAS_DET.MONTO_AJUSTE,
  VENTAS_DET.SERIE_PROD,
  VENTAS_DET.STATUS_CNT,
  VENTAS_DET.TIPO_VENTA,
  UNIDADES.DESCRIPCION as DESC_tipounidad,
  UNIDADES.CANTIDAD as cx_tipounidad,
  UNIDADES.IDUNIDAD,
  ventas_Det.DESCRIPCIONPRODUCTO
FROM
  VENTAS_MAST
  INNER JOIN VENTAS_DET ON (VENTAS_MAST.NUMERO = VENTAS_DET.NUMERO)
  LEFT OUTER JOIN UNIDADES ON (VENTAS_DET.TIPO_UNIDAD = UNIDADES.IDUNIDAD)
ORDER BY
  VENTAS_MAST.NUMERO

;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEW_VENTAS_DET TO  DIVISON WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIEW_VENTAS_DET TO  SYSDBA WITH GRANT OPTION;
