CREATE TABLE COBROS_EN_CHEQUE
(
  SERIE integer NOT NULL,
  NUMERO_RECIBO integer NOT NULL,
  NUMERO_CHEQUE integer,
  CODIGO_BANCO integer,
  MONTO_CHEQUE numeric(15,2),
  COD_USUARIO integer,
  FECHA_IN timestamp,
  IN_POR varchar(12),
  MOD_POR varchar(12),
  FECHA_MOD timestamp,
  STATUS char(1)
);

CREATE UNIQUE INDEX IDX_COBROS_EN_CHEQUE1 ON COBROS_EN_CHEQUE (SERIE,NUMERO_RECIBO,NUMERO_CHEQUE,CODIGO_BANCO);
CREATE INDEX IDX_COBROS_EN_CHEQUE2 ON COBROS_EN_CHEQUE (NUMERO_RECIBO);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON COBROS_EN_CHEQUE TO  DIVISON WITH GRANT OPTION;