CREATE TABLE VENTAS_MAST_CONSIGNA
(
  NUMERO CAMPO_ENTERO NOT NULL,
  FECHA CAMPO_FECHA_HORA,
  CIA_KEY integer,
  CODIGO_CTE CAMPO_ENTERO,
  CODIGO_VENDEDOR CAMPO_ENTERO,
  FORMA_PAGO NUM_SMALLINT,
  OBSERVACION CAMPO_VARCHAR60,
  MONEDA CAMPO_CHAR1,
  VALOR_TOTAL_DET NUMERICO_15_2,
  STATUS CAMPO_CHAR1,
  FECHA_IN CAMPO_FECHA_HORA,
  IN_POR CAMPO_VARCHAR12,
  FECHA_MOD CAMPO_FECHA_HORA,
  MOD_POR CAMPO_VARCHAR12,
  NUMERO_FACTURA CAMPO_ENTERO,
  NUMERO_DOC_PAGO CAMPO_VARCHAR20,
  SERIE_NCF_ASIGNADO integer,
  MONTO_BRUTO numeric(15,2),
  PORC_DESCUENTO integer,
  MONTO_DESCUENTO numeric(15,2),
  MONTO_INICIAL numeric(15,2),
  NOMBRE_CLIENTE_GENERAL varchar(60),
  MONTO_PAGADO numeric(15,2),
  MONTO_CAMBIO numeric(15,2),
  MONTO_TOTAL_ITBIS numeric(15,2),
  MONTODESCGASTOSADMIN numeric(15,2),
  MONTODESCITBISGASTOSADMIN numeric(15,2),
  MONTODESCTRANSP numeric(15,2),
  MONTODESCDIRTECNICA numeric(15,2),
  MONTODESCITBISDIRTECNICA numeric(15,2),
  MONTODESCIMPREVISTO numeric(15,2),
  MONTODESCITBISIMPREVISTO numeric(15,2),
  DESC_MONTO_COMBUSTIBLE numeric(15,2),
  DESC_MONTO_PRESTAMO numeric(15,2),
  DESC_MONTO_SINDICATO numeric(15,2),
  DESC_IMP_SOBRE_RENTA numeric(15,2),
  DESC_OTROS numeric(15,2),
  PORC_DESC_SINDICATO numeric(8,2),
  PORC_DESC_IMP_SOBRE_RENTA numeric(8,2),
  DESC_RUTA numeric(15,2),
  OTROS_DESCUENTOS_2 numeric(15,2),
  OTROS_DESCUENTOS_3 numeric(15,2),
  MONTO_DESC_CHOFER numeric(15,2),
  TIPO_VENTA smallint,
  COMENTARIO varchar(80),
  CONSTRAINT VENTAS_MASTPRIMARYKEY1C PRIMARY KEY (NUMERO)
);

CREATE INDEX IDX_VENTAS_MAST1C ON VENTAS_MAST_CONSIGNA (CODIGO_CTE);
CREATE UNIQUE INDEX VENTAS_MASTINDEX1C ON VENTAS_MAST_CONSIGNA (NUMERO);
CREATE INDEX VENTAS_MASTINDEX2C ON VENTAS_MAST_CONSIGNA (FECHA);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VENTAS_MAST_CONSIGNA TO  DIVISON WITH GRANT OPTION;



-- TODO:
-- * add triggers and their ddl
-- * for each trigger, look for dependent generators via dependecies

CREATE TABLE VENTAS_DET_CONSIGNA
(
  SERIE CAMPO_ENTERO NOT NULL,
  NUMERO CAMPO_ENTERO NOT NULL,
  CODIGO_PROD CAMPO_VARCHAR40,
  CODIGO_BARRA CAMPO_VARCHAR20,
  DESCRIPCION CAMPO_VARCHAR80,
  CANTIDAD NUMERICO_15_2,
  PRECIO NUM_FLOTANTE,
  PORC_DESC_DET NUM_FLOTANTE,
  ITBI_DET NUM_FLOTANTE,
  VALOR_SERVICIO_DET NUMERICO_15_2,
  VALOR_TOTAL_DET NUMERICO_15_2,
  NUM_FACTURA CAMPO_DOBLE_PREC,
  STATUS_DET CAMPO_CHAR1,
  FECHA_IN CAMPO_FECHA_HORA,
  IN_POR CAMPO_VARCHAR12,
  FECHA_MOD CAMPO_FECHA_HORA,
  MOD_POR CAMPO_VARCHAR12,
  CANT_REGRESO NUMERICO_15_2,
  CANT_PROMO NUMERICO_15_2,
  MONTO_DIETA NUMERICO_15_2,
  MONTO_AJUSTE NUMERICO_15_2,
  SERIE_PROD varchar(50),
  STATUS_CNT char(1),
  TIPO_UNIDAD CAMPO_ENTERO,
  ITBIS_EXENTO smallint,
  TIPO_VENTA smallint,
  DESCRIPCIONPRODUCTO CAMPO_MEMO,
  COD_EMPLEADO_CONDUCTOR numeric(15,2),
  PLACA_VEHICULO varchar(20),
  MONEDA char(1),
  MONTO_TASA numeric(15,2),
  CAPACIDAD numeric(15,2),
  CANT_VIAJES numeric(15,2),
  CANT_METROS_CUBICO numeric(15,2),
  FICHA_VEH integer,
  IDZONA_ORIGEN integer,
  IDZONA_DETALLE integer,
  CONSTRAINT VENTAS_DETPRIMARYKEY1c PRIMARY KEY (SERIE)
);

CREATE INDEX IDX_VENTAS_DET1c ON VENTAS_DET_CONSIGNA (CODIGO_PROD);
CREATE INDEX IDX_VENTAS_DET2c ON VENTAS_DET_CONSIGNA (STATUS_CNT);
CREATE UNIQUE INDEX VENTAS_DETINDEX1c ON VENTAS_DET_CONSIGNA (SERIE);
CREATE INDEX VENTAS_DETINDEX2c ON VENTAS_DET_CONSIGNA (NUMERO);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VENTAS_DET_CONSIGNA TO  DIVISON WITH GRANT OPTION;



-- TODO:
-- * add triggers and their ddl
-- * for each trigger, look for dependent generators via dependecies

CREATE GENERATOR GEN_NUM_VENTA_MASTc;

CREATE GENERATOR GEN_NUM_VENTA_DETc;


SET TERM ^ ;
CREATE PROCEDURE PROC_INS_VENTAS_MAST_csg (
    FECHA timestamp,
    CIA_KEY integer,
    CODIGO_CTE integer,
    CODIGO_VENDEDOR integer,
    FORMA_PAGO smallint,
    OBSERVACION varchar(60),
    MONEDA char(1),
    VALOR_TOTAL_DET numeric(15,2),
    STATUS char(1),
    FECHA_IN timestamp,
    IN_POR varchar(12),
    FECHA_MOD timestamp,
    MOD_POR varchar(12),
    NUMERO_FACTURA integer,
    NUMERO_DOC_PAGO varchar(20),
    SERIE_NCF_ASIGNADO integer,
    MONTO_BRUTO numeric(15,2),
    PORC_DESCUENTO integer,
    MONTO_DESCUENTO numeric(15,2),
    MONTO_PAGADO numeric(15,2),
    MONTO_CAMBIO numeric(15,2),
    MONTO_TOTAL_ITBIS numeric(15,2),
    MONTO_INICIAL numeric(15,2),
    NOMBRE_CLIENTE_GENERAL varchar(60),
    E_MONTODESCGASTOSADMIN numeric(15,2),
    E_MONTODESCITBISGASTOSADMIN numeric(15,2),
    E_MONTODESCTRANSP numeric(15,2),
    E_MONTODESCDIRTECNICA numeric(15,2),
    E_MONTODESCITBISDIRTECNICA numeric(15,2),
    E_MONTODESCIMPREVISTO numeric(15,2),
    E_MONTODESCITBISIMPREVISTO numeric(15,2),
    COMENTARIO varchar(80) )
RETURNS (
    NUMERO_TRNS integer )
AS
declare variable xnumero integer;
DECLARE VARIABLE NUM_CONSIGNA INTEGER;
BEGIN
  
  Select Gen_id(GEN_NUM_VENTA_MASTc,1) From rdb$database
  into NUMERO_TRNS;
  
  SELECT Gen_id(GEN_NUM_CONSIGNA,1) From rdb$database
  into NUM_CONSIGNA;
  
  xNumero =NUMERO_TRNS;
 
  INSERT INTO VENTAS_MAST_CONSIGNA (
    NUMERO,
    cia_key,
    FECHA,
    CODIGO_CTE,
    CODIGO_VENDEDOR,
    FORMA_PAGO,
    OBSERVACION,
    MONEDA,
    VALOR_TOTAL_DET,
    STATUS,
    FECHA_IN,
    IN_POR,
    FECHA_MOD,
    MOD_POR,
    NUMERO_FACTURA,
    NUMERO_DOC_PAGO, serie_ncf_asignado,
    monto_bruto,
    porc_descuento,
    monto_descuento, 
	MONTO_PAGADO,
    MONTO_CAMBIO,
    MONTO_TOTAL_ITBIS,
	MONTO_INICIAL, 
	NOMBRE_CLIENTE_GENERAL,
    MONTODESCGASTOSADMIN,
    MONTODESCITBISGASTOSADMIN,
    MONTODESCTRANSP,
    MONTODESCDIRTECNICA,
    MONTODESCITBISDIRTECNICA,
    MONTODESCIMPREVISTO,
    MONTODESCITBISIMPREVISTO, comentario 	
 )
  VALUES (
    :xNumero,
    :cia_key,
    :FECHA,
    :CODIGO_CTE,
    :CODIGO_VENDEDOR,
    :FORMA_PAGO,
    :OBSERVACION,
    :MONEDA,
    :VALOR_TOTAL_DET,
    :STATUS,
    :FECHA_IN,
    :IN_POR,
    :FECHA_MOD,
    :MOD_POR,
    :NUM_CONSIGNA,
    :NUMERO_DOC_PAGO, :serie_ncf_asignado,
    :monto_bruto,
    :porc_descuento,
    :monto_descuento,
    :monto_pagado,
    :monto_cambio,
    :monto_total_itbis,
    :MONTO_INICIAL, 
    :NOMBRE_CLIENTE_GENERAL,
    :e_MONTODESCGASTOSADMIN,
    :e_MONTODESCITBISGASTOSADMIN,
    :e_MONTODESCTRANSP,
    :e_MONTODESCDIRTECNICA,
    :e_MONTODESCITBISDIRTECNICA,
    :e_MONTODESCIMPREVISTO,
    :e_MONTODESCITBISIMPREVISTO,:comentario);   
   SUSPEND;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE PROC_INS_VENTAS_MAST_csg TO  DIVISON;



-- TODO:
-- * add triggers and their ddl
-- * for each trigger, look for dependent generators via dependecies


SET TERM ^ ;
CREATE PROCEDURE PROC_INS_VENTAS_DET_csg (
    NUMERO integer,
    CODIGO_PROD varchar(40),
    CODIGO_BARRA varchar(20),
    DESCRIPCION varchar(60),
    CANTIDAD numeric(15,2),
    PRECIO float,
    PORC_DESC_DET float,
    ITBI_DET float,
    VALOR_SERVICIO_DET numeric(15,2),
    VALOR_TOTAL_DET numeric(15,2),
    NUM_FACTURA double precision,
    STATUS_DET char(1),
    FECHA_IN timestamp,
    IN_POR varchar(12),
    FECHA_MOD timestamp,
    MOD_POR varchar(12),
    CANT_REGRESO numeric(15,2),
    CANT_PROMO numeric(15,2),
    MONTO_DIETA numeric(15,2),
    MONTO_AJUSTE numeric(15,2),
    SERIE_PROD varchar(50),
    TIPO_UNIDAD integer,
    ITBIS_EXENTO smallint,
    TIPO_VENTA smallint,
    DESCRIPCIONPRODUCTO blob sub_type 1 )
AS
declare variable xSerie integer;
BEGIN
  Select Gen_id(GEN_NUM_VENTA_DETC,1) From rdb$Database
  Into :xSerie;
  INSERT INTO VENTAS_DET_CONSIGNA (
    Serie,
    NUMERO,
    CODIGO_PROD,
    CODIGO_BARRA,
    DESCRIPCION,
    CANTIDAD,
    PRECIO,
    PORC_DESC_DET,
    ITBI_DET,
    VALOR_SERVICIO_DET,
    VALOR_TOTAL_DET,
    NUM_FACTURA,
    STATUS_DET,
    FECHA_IN,
    IN_POR,
    FECHA_MOD,
    MOD_POR,
    CANT_REGRESO,
    CANT_PROMO,
    MONTO_DIETA,
    MONTO_AJUSTE, Serie_Prod, TIPO_UNIDAD, ITBIS_EXENTO, TIPO_VENTA, DESCRIPCIONPRODUCTO
 
    )
  VALUES (
    :XSERIE,
    :NUMERO,
    :CODIGO_PROD,
    :CODIGO_BARRA,
    :DESCRIPCION,
    :CANTIDAD,
    :PRECIO,
    :PORC_DESC_DET,
    :ITBI_DET,
    :VALOR_SERVICIO_DET,
    :VALOR_TOTAL_DET,
    :NUM_FACTURA,
    :STATUS_DET,
    :FECHA_IN,
    :IN_POR,
    :FECHA_MOD,
    :MOD_POR,
    :CANT_REGRESO,
    :CANT_PROMO,
    :MONTO_DIETA,
    :MONTO_AJUSTE, :Serie_Prod, :TIPO_UNIDAD, :ITBIS_EXENTO, :TIPO_VENTA,:DESCRIPCIONPRODUCTO);
  SUSPEND;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE PROC_INS_VENTAS_DET_csg TO  DIVISON;



-- TODO:
-- * add triggers and their ddl
-- * for each trigger, look for dependent generators via dependecies

INSERT INTO TIPO_PAGO (CODIGO, DESCRIPCION, ORIGEN) VALUES ('17', 'Consignación', '1');


CREATE GENERATOR GEN_NUM_CONSIGNA;
SET GENERATOR GEN_NUM_CONSIGNA TO 0;


SET TERM ^ ;
create PROCEDURE PROC_BUSCARULTNUMSEC_csg (
    CIAKEY integer )
RETURNS (
    SERIE_VTA integer
     )
AS
BEGIN
  --Select max(numero) from facturas where CIA_KEY =:ciakey
  --Into :num_factura;

  Select Max(VENTAS_MAST_CONSIGNA.NUMERO_FACTURA)
  From VENTAS_MAST_CONSIGNA  
  Where forma_pago in (17)
  And CIA_KEY =:ciakey
  Into :serie_vta;
SUSPEND;
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE PROC_BUSCARULTNUMSEC_csg TO  DIVISON;


 SET TERM ^ ;
Create PROCEDURE PROC_UPDATEVENTAS_MAST_U1_csg (
    NUMERO integer,
    FECHA timestamp,
    CIA_KEY integer,
    CODIGO_CTE integer,
    CODIGO_VENDEDOR integer,
    FORMA_PAGO smallint,
    OBSERVACION varchar(60),
    MONEDA char(1),
    VALOR_TOTAL_DET numeric(15,2),
    STATUS char(1),
    FECHA_MOD timestamp,
    MOD_POR varchar(12),
    NUMERO_FACTURA integer,
    NUMERO_DOC_PAGO varchar(20),
    SERIE_NCF_ASIGNADO integer,
    MONTO_BRUTO numeric(15,2),
    PORC_DESCUENTO integer,
    MONTO_DESCUENTO numeric(15,2),
    MONTO_INICIAL numeric(15,2),
    NOMBRE_CLIENTE_GENERAL varchar(60),
    MONTO_PAGADO numeric(15,2),
    MONTO_CAMBIO numeric(15,2),
    MONTO_TOTAL_ITBIS numeric(15,2),
    MONTODESCGASTOSADMIN numeric(15,2),
    MONTODESCITBISGASTOSADMIN numeric(15,2),
    MONTODESCTRANSP numeric(15,2),
    MONTODESCDIRTECNICA numeric(15,2),
    MONTODESCITBISDIRTECNICA numeric(15,2),
    MONTODESCIMPREVISTO numeric(15,2),
    MONTODESCITBISIMPREVISTO numeric(15,2),
    COMENTARIO varchar(80) )
AS
BEGIN
  UPDATE VENTAS_MAST_CONSIGNA
  SET
    FECHA = :FECHA,
    CIA_KEY = :CIA_KEY,
    CODIGO_CTE = :CODIGO_CTE,
    --CODIGO_VENDEDOR = :CODIGO_VENDEDOR,
    FORMA_PAGO = :FORMA_PAGO,
    OBSERVACION = :OBSERVACION,
    MONEDA = :MONEDA,
    VALOR_TOTAL_DET = :VALOR_TOTAL_DET,
    STATUS = :STATUS,

    FECHA_MOD = :FECHA_MOD,
    MOD_POR = :MOD_POR,
    NUMERO_FACTURA = :NUMERO_FACTURA,
    --NUMERO_DOC_PAGO = :NUMERO_DOC_PAGO,
    --SERIE_NCF_ASIGNADO = :SERIE_NCF_ASIGNADO,
    MONTO_BRUTO = :MONTO_BRUTO,
    PORC_DESCUENTO = :PORC_DESCUENTO,
    MONTO_DESCUENTO = :MONTO_DESCUENTO,
    MONTO_INICIAL = :MONTO_INICIAL,
    NOMBRE_CLIENTE_GENERAL = :NOMBRE_CLIENTE_GENERAL,
    MONTO_PAGADO = :MONTO_PAGADO,
    MONTO_CAMBIO = :MONTO_CAMBIO,
    MONTO_TOTAL_ITBIS = :MONTO_TOTAL_ITBIS,
    MONTODESCGASTOSADMIN = :MONTODESCGASTOSADMIN,
    MONTODESCITBISGASTOSADMIN = :MONTODESCITBISGASTOSADMIN,
    MONTODESCTRANSP = :MONTODESCTRANSP,
    MONTODESCDIRTECNICA = :MONTODESCDIRTECNICA,
    MONTODESCITBISDIRTECNICA = :MONTODESCITBISDIRTECNICA,
    MONTODESCIMPREVISTO = :MONTODESCIMPREVISTO,
    MONTODESCITBISIMPREVISTO = :MONTODESCITBISIMPREVISTO,
    Comentario =:Comentario
  WHERE
  (NUMERO = :NUMERO);
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE PROC_UPDATEVENTAS_MAST_U1_csg TO  DIVISON;


 SET TERM ^ ;
create PROCEDURE PROC_UPDATEVENTAS_DET_U1_csg (
    SERIE integer,
    NUMERO integer,
    CODIGO_PROD varchar(40),
    CODIGO_BARRA varchar(20),
    DESCRIPCION varchar(60),
    CANTIDAD numeric(15,2),
    PRECIO float,
    PORC_DESC_DET float,
    ITBI_DET float,
    VALOR_SERVICIO_DET numeric(15,2),
    VALOR_TOTAL_DET numeric(15,2),
    NUM_FACTURA double precision,
    STATUS_DET char(1),
    FECHA_MOD timestamp,
    MOD_POR varchar(12),
    CANT_REGRESO numeric(15,2),
    CANT_PROMO numeric(15,2),
    MONTO_DIETA numeric(15,2),
    MONTO_AJUSTE numeric(15,2),
    SERIE_PROD varchar(50),
    STATUS_CNT char(1),
    TIPO_UNIDAD integer,
    ITBIS_EXENTO smallint,
    TIPO_VENTA smallint,
    DESCRIPCIONPRODUCTO blob sub_type 1 )
AS
BEGIN
  UPDATE VENTAS_DET_CONSIGNA
  SET
    NUMERO = :NUMERO,
    CODIGO_PROD = :CODIGO_PROD,
    --CODIGO_BARRA = :CODIGO_BARRA,
    DESCRIPCION = :DESCRIPCION,
    CANTIDAD = :CANTIDAD,
    PRECIO = :PRECIO,
    PORC_DESC_DET = :PORC_DESC_DET,
    ITBI_DET = :ITBI_DET,
    VALOR_SERVICIO_DET = :VALOR_SERVICIO_DET,
    VALOR_TOTAL_DET = :VALOR_TOTAL_DET,
    NUM_FACTURA = :NUM_FACTURA,
    STATUS_DET = :STATUS_DET,    
    FECHA_MOD = :FECHA_MOD,
    MOD_POR = :MOD_POR,
    --CANT_REGRESO = :CANT_REGRESO,
    --CANT_PROMO = :CANT_PROMO,
    --MONTO_DIETA = :MONTO_DIETA,
    --MONTO_AJUSTE = :MONTO_AJUSTE,
    SERIE_PROD = :SERIE_PROD,
    --STATUS_CNT = :STATUS_CNT,
    TIPO_UNIDAD = :TIPO_UNIDAD,
    ITBIS_EXENTO = :ITBIS_EXENTO,
    TIPO_VENTA = :TIPO_VENTA,
    DESCRIPCIONPRODUCTO = :DESCRIPCIONPRODUCTO
  WHERE
  (SERIE = :SERIE);
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE PROC_UPDATEVENTAS_DET_U1_csg TO  DIVISON;

