[Debug]
GlbEsDebugFiscal=1
GlbEsDebugEntradas=1
[Recibo]
rtipo3_pulg=1
rtipo5_5pulg=0
ncfConsFinal=1
GlbImpCodProducto=0
GlbImpReciboSinPreg=0
GlbDiaFactMensualidad=9/30/2016
[factura]
ftipo3_pulg=0
ftipo5_5pulg=1
ncfConsFinal=0
PieDePagina=Gracias por su compra
fsizeFact8x11=0
fsizeCotiza8x11=0
GlbFacturaLicoreria=0
GlbMuestraInteresFactFinac=0
[cotiza]
ctipo3_pulg=0
ctipo5_5pulg=1
[SolDatosCteVC]
SDatosCteVC=0
[SolDatosVehiculo]
SSolDatosVehiculo=0
[Label]
PrecioCodificado=0
FechaVencProducto=1
GlbInluirPrecioItbisenLabel=0
[Venta]
GlbPermiteCambioPrecio=1
GlbActF10CodBarra=0
GlbPermiteVentaInv0=1
GlbVenderDesdeAlmacenP=1
GlbTransparentaITBI=1
GlbImprimeReciboFact=0
GlbFirmaCajero=0
GlbImpTUnidadEnRcbo=0
GlbActivaCafeteria=0
GlbUsaescalaPrecio=1
GlbPermiteVtaServicioAdc=0
GlbActivaIFiscal=0
GlbTipoConduce=1
GLBImpBoucher=0
;GlbUsaPUnidadLevel permite usar precios por producto unidad por 4 niveles de precios
GlbUsaPUnidadLevel=0
;Agrega monto itbis a precio venta en undiad por niveles de precios
GLBAplicaITBISLevel=1
;GlbUsaBalanza se usa para conseguir el codigo y el peso del codigo barra generado por la balalanza
GlbUsaBalanza=0
GlbImpPDF=1
GlbUsaPUnidadStd=0
[RegOrden]
GlbPrecioMayRegOrden=0
[Aplicacion]
GlbCorriendo=0
GlbPermiteUnaInstancia=1
GlbEmailTool=IdesiToolComm.exe
[Inventario]
GlbIDAlmacenProd=5
[MenuPrincipal]
GlbActivaPanificadora=0
GlbColegio=0
GlbActivaLavanderia=0
GlbScaledform=0
GlbScreenWith=800
GlbScreenHeight=600
[Backup]
RutaBinRDB=C:\Program Files (x86)\Firebird\Firebird_2_5\bin
[IFiscal]
RutaIFiscal=C:\Proyectos\IFiscal\VB\IdesiEpsonFiscaltool\IdesiEpsonFiscaltool\bin\Release\IdesiEpsonFiscaltool.exe
;RutaIFiscal=C:\Proyectos\PointSaleSoftV4\Bin\IdesiEpsonFiscaltool\IdesiEpsonFiscaltool.exe
[DataBase]
GLBRUTADB=ifiscalmaison
[DBDGII]
Ruta=C:\Proyectos\Datos\RNC_DGII\DGII_RNC.FDB
GLBRUTABDGIITXT=C:\Proyectos\Datos\RNC_DGII\DGII_RNC.TXT
[DBAccess]
Ruta="Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\Proyectos\Datos\PuntoVenta\BarArea31\DBAccessBarArea31.mdb;Persist Security Info=False;"
[REPORTS]
Facturas=c:\Proyectos\Datafiles\Facturas
Recibos=c:\Proyectos\Datafiles\Recibos
Cotizaciones=c:\Proyectos\Datafiles\Recibos
Informes=c:\Proyectos\Datafiles\Informes
